configmap/parse.go, configmap/parse_test.go
We keep copy and pasting code that handles this, so why not make a reusable library for all our projects? :slightly_smiling_face: 
Proof it works: https://github.com/knative/serving/pull/7935
=> Add a library to parse config map values.

apis/duck/v1/kresource_type.go, apis/test/example/v1alpha1/fiz_types.go, apis/test/example/v1alpha1/foo_types.go, apis/test/pub/v1alpha1/bar_types.go, reconciler/reconcile_common.go, reconciler/reconcile_common_test.go
I had been using the GetObjectMeta accessor, but since these are inlined we can just use the metav1.Object interface directly.
Likewise we'll use the schema.ObjectKind interface to access TypeMeta information
=> Simplify the krshaped interface, just use k8s interfaces for TypeMeta and ObjectMeta

network/network.go
We have in situ constants, which are not always consistent.
/assign @markusthoemmes mattmoor
As discussed today.
=> Add a constant with default shutdown wait time

test/zipkin/util.go, webhook/env.go, webhook/env_test.go
Users can use WEBHOOK_PORT env var to configure the port that webhook uses.
To read the env var, replace `Port: 8443` with `Port: webhook.Port(8443)` in [main.go](https://github.com/knative/serving/blob/0f1c5af53e0cb5172135d0e9d2d4b7e59e276187/cmd/webhook/main.go#L220).
=> Add helper function to read webhook port number from env var

configmap/parse.go, configmap/parse_test.go, leaderelection/config.go, leaderelection/config_test.go, metrics/config_observability.go, tracing/config/tracing.go, tracing/config/tracing_test.go
- Use pkg/configmap parser for observability and leaderelection config. Logging config ain't worth it and I didn't yet dare to touch metric config.
- Adds a new helper for parsing StringSets. That one is useful in multiple places.
- Enhance the error reporting to always include the parsed key to be useful in error messages.
=> Use config map parsing lib and enhance it further.

reconciler/reconcile_common.go
We are expecting that pre-process will have added a top-level condition, but if for some reason the reconciler clears conditions we want to  log a warning. As-is this might panic.
=> add nil check to postprocess

configmap/store.go, configmap/store_test.go
Generally, the `onAfterStore` function is used to kick off a global resync, which should be a very quick operation. Having `onAfterStore` being called asynchronously on a goroutine makes it very hard or straight out impossible to control it, especially in tests.
If there's a costly operation being done `onAfterStore`, it should be up to the caller to decide to make that asynchronous and thus put it into a goroutine.
This contributes to a lot of test flakes, at least in Knative Serving.
=> Make onAfterStore synchronous to the update itself.

webhook/resourcesemantics/conversion/conversion.go
We don't log _what_ we convert, but only _what type_ it is.
And it's not very useful
So log all the stuff
/assign @dprotaso @mattmoor
=> Add the key of the object to the log context

webhook/webhook.go, webhook/webhook_test.go
Doesn't seem like it affected anything - just writes out some extra
log messages
=> Kubelet probes would result in the webhook writing the HTTP status twice

apis/duck/v1/status_types.go, apis/duck/v1/status_types_test.go, apis/duck/v1beta1/status_types.go, apis/duck/v1beta1/status_types_test.go
Some tests were failing for `nil != map{}` check (which is better off with `cmpopts.EquateEmpty` anyway, especially when considering wire roundtrip). 
But regardless, no need to create a map if source is nil.
Also apprarently beta duck is a thing.
/assign @dprotaso @vaikas
=> Fix beta duck conversion & omit conversion if nil

webhook/webhook.go, webhook/webhook_test.go
Doesn't seem like it affected anything - just writes out some extra
log messages
=> [release-0.15] Kubelet probes would result in the webhook writing the HTTP status twice

configmap/parse.go, configmap/parse_test.go
moving over [same method from serving config/defaults.go](https://github.com/knative/serving/blob/401e03a/pkg/apis/config/defaults.go#L160) so it can be used in deployment configmap also.
=> Add AsQuantity to configmap parser

webhook/webhook.go, webhook/webhook_test.go
- use standard const, which is better
- stop modifying the default in the test, which is ugh a bit :)
/assign mattmoor @dprotaso
=> Use the generic networking constant for shutdown

metrics/stackdriver_exporter.go
Found this while poking at writing an e2e test case for stackdriver.
Without this patch, I get a panic. With the patch, I get:
> unable to init: stackdriver: couldn't initialize trace client: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
/assign @jjzeng-seattle
=> Don't swallow errors from stackdriver init.

controller/controller.go, controller/controller_test.go
Without the `Unwrap()` method, `ReconcilerEvents` can't be unwrapped from `permanentError`s (L198), and we jump directly over the block (L209).
https://github.com/knative/pkg/blob/a468cb85692fc17e6abd2677f0b88f3337089723/client/injection/kube/reconciler/core/v1/namespace/reconciler.go#L196-L212
`Is()` allows for `permanentError`s to be wrapped themselves and still be considered as permanent.
=> Implement Unwrap() and Is() for permanentErrors

test/junit/junit.go, test/junit/junit_test.go, testutils/junithelper/main.go
Junithelper was previously just a command, refactoring it as a function so it can be re-used by upstream vendors.
/cc @chizhg @chaodaiG
=> Junithelper refactor into a function that can be re-used.

reconciler/reconcile_common.go, reconciler/reconcile_common_test.go
Initialize conditions in preprocess
This is an oft-repeated piece of code that we have in reconcilers. We should ensure conditions are initialized before we reconcile.
=> Initialize conditions in preprocess

configmap/example.go, configmap/example_test.go, configmap/hash-gen/main.go, configmap/hash-gen/testdata/add_want.yaml, configmap/hash-gen/testdata/update_want.yaml, configmap/testing/configmap.go, webhook/configmaps/configmaps.go
As per @julz comment on https://github.com/knative/serving/pull/8123 this is more usual. I like it better anyway as the `Checksum` function now controls the representation.
/assign @julz
=> Use a hexadecimal representation for the example checksum.

test/gcs/mock/mock.go, test/gcs/mock/mock_example_test.go, test/gcs/mock/mock_storage.go, test/gcs/mock/mock_test.go
This is needed for users of mock to create error maps.
/cc @chizhg @chaodaiG
=> Making mock.method public mock.Method

configmap/example.go, configmap/hash-gen/main.go, configmap/hash-gen/testdata/add_want.yaml, configmap/hash-gen/testdata/update.yaml, configmap/hash-gen/testdata/update_want.yaml, configmap/testing/configmap.go, webhook/configmaps/configmaps.go, webhook/configmaps/configmaps_test.go
Slightly more correct to use an annotation rather than a label since this isn't something one would select on.
=> Use annotation rather than label for configmap checksum

configmap/example.go, configmap/example_test.go, configmap/hash-gen/testdata/add_want.yaml, configmap/hash-gen/testdata/update_want.yaml
Due to the parser difference we had 2 different values in WH and in the hash gen
Fixes: https://github.com/knative/serving/issues/8211
=> Remove the trailing \n

codegen/cmd/injection-gen/generators/reconciler_reconciler.go
When an error is returned frequently the resource is nil and results in resource being set to nil. Then nil.Name being called for the error string.
=> Prevent nil access when resource is nil

webhook/certificates/resources/certs.go, webhook/certificates/resources/certs_test.go
This adds a common name to the certificates generated for the webhook service to
prevent issues with applications that do CN checking vs SAN checking.
This provides compatibilty for Istio v1.5
There should be no impacts because there was previously no CN on the certificate
Another approach would allow users to provide custom CA certs for this serivce
=> Added common name to cert tmpl

websocket/connection.go, websocket/connection_test.go
Allows sending non-gob-encoded data over the web socket, in service of https://github.com/knative/serving/pull/8266.
=> Add SendRaw to websocket client

configmap/hash-gen/main.go
So we can use one `go run` to process all the configmaps, avoiding recompilation each time (see https://github.com/knative/serving/pull/8281).
=> Allow hashgen to process multiple files

configmap/example.go, configmap/example_test.go, configmap/hash-gen/testdata/add_want.yaml, configmap/hash-gen/testdata/update_want.yaml
Fixes https://github.com/knative/serving/issues/8313
kubeclient seems to normalize newlines, which causes issues when you patch via that library.
=> Normalize newlines in webhook example checksum.

webhook/resourcesemantics/defaulting/defaulting.go, webhook/resourcesemantics/defaulting/table_test.go, webhook/resourcesemantics/validation/reconcile_config.go, webhook/resourcesemantics/validation/reconcile_config_test.go
Added a namespaces selector to the mutating webhook configuration which
allows for excluding namespaces from the webhook
Fixes #1379
=> Allows for webhooks to exclude certain namespaces

metrics/exporter.go
During the testing of stackdriver exporter with the dynamic labels in PR https://github.com/knative/pkg/pull/1392, we found out that we need to introduce a breaking change.
With the recorder extract the metric tags into resource labels, and send the measurement to the meter associated with the resource.  The problem is that currently `view.Register` is used, and the view only registered to the default meter, not the corresponding meter to the resource.  If we use `RegisterResourceView` instead, then it will work because it register the views to all meters.
If we merge that PR in its current form, we also need to fix all callers at the same time.  That will be too risky.  Therefore @evankanderson and I came up with this approach, by introducing the change up front.  After this one we will …
=> Add a passthrough method RegisterResourceView

metrics/config.go, metrics/config_test.go
- Add support for a new environment variable `METRICS_PROMETHEUS_PORT` that can override the default Prometheus port in the metrics exporter.
Rational: the default port 9090 clashes with Serving's queue proxy when a receive adapter is deployed as a Knative Service. There is currently no way to make that work without explicitly disabling metrics by setting the `K_METRICS_CONFIG` env var to `""`.
Second tentative after closing knative/eventing#3316.
=> Make Prometheus exporter port configurable via env

network/transports.go
No need to diverge from the timeout setting.
Also note that maxidle conns are also different from the upstream
/assign @tcnghia @julz
=> Reconcile the settings with net/http

reconciler/reconcile_common.go, reconciler/reconcile_common_test.go
Fixes #1401
We always want to initialize resources in case the defaults have changed or conditions have been added as we change versions (even if they haven't been written to).
We already do this for most reconcilers, but it will be easier to do in the common spot:
https://github.com/knative/serving/blob/d9d5ae4393ef31f1aa639be5bb6e9c0079e39bce/pkg/reconciler/route/route.go#L112
In the future if we can default-on-read or run this on upgrade-only it would be nice to not need to do it for every single reconciliation.
=> Always initialize conditions and set defaults when reconciling

test/spoof/spoof.go
Currently we're getting:
```
Retrying [http://activator-with-cc.default.svc.cluster.local?sleep=100 retrying for DNS error: Get http://activator-with-cc.default.svc.cluster.local?sleep=100: dial tcp: lookup activator-with-cc.default.svc.cluster.local on 10.27.240.10:53: no such host]: %!v(MISSING)
```
Which is not cool. So fix it to report proper string.
URL is known to be non-nil here.
/assign @chizhg @chaodaiG
=> Fix the logging in spoof

client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go
This aborts reconcilation if finalizers could not be patched correctly with an error and thus it retries.
We shouldn't start a reconcilation if we haven't been able to correctly add the finalizer first. Otherwise we could get into a weird spot where the resources are created before the finalizer and in a very degenerate case the finalizer wouldn't even be executed. Also, the current code has a bug where if the patch fails the resource coming back from the patch (essentially an empty object) is passed into ReconcileKind, causing headaches.
The same imo goes for removing a finalizer. Failing to remove a finalizer blocks the resource forever, thus we should retry if that happens too.
=> Abort reconcilation on finalizer patch errors.

webhook/certificates/certificates.go, webhook/certificates/certificates_test.go, webhook/certificates/controller.go, webhook/configmaps/configmaps.go, webhook/configmaps/controller.go, webhook/configmaps/table_test.go, webhook/psbinding/controller.go, webhook/psbinding/psbinding.go, webhook/psbinding/reconciler.go, webhook/psbinding/table_test.go, webhook/resourcesemantics/conversion/controller.go, webhook/resourcesemantics/conversion/reconciler.go, webhook/resourcesemantics/defaulting/controller.go, webhook/resourcesemantics/defaulting/defaulting.go, webhook/resourcesemantics/defaulting/table_test.go, webhook/resourcesemantics/validation/controller.go, webhook/resourcesemantics/validation/reconcile_config.go, webhook/resourcesemantics/validation/reconcile_config_test.go, webhook/resourcesemantics/validation/validation_admit_test.go, webhook/testing/factory.go
Detailed design: https://docs.google.com/document/d/1i_QHjQO2T3SNv49xjZLWlivcc0UvZN1Tbw2NKxThkyM/edit
Issue: https://github.com/knative/pkg/issues/1181
WIP until #1301 lands
=> Implement the second wave of per-reconciler leaderelection

injection/sharedmain/main.go
Detailed design: https://docs.google.com/document/d/1i_QHjQO2T3SNv49xjZLWlivcc0UvZN1Tbw2NKxThkyM/edit
Issue: #1181
WIP until #1302 lands
=> Implement the third wave of per-reconciler leaderelection

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go, client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go, client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/stub/reconciler.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/stub/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/controller.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/stub/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_controller.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go, hack/update-codegen.sh
Detailed design: https://docs.google.com/document/d/1i_QHjQO2T3SNv49xjZLWlivcc0UvZN1Tbw2NKxThkyM/edit
Issue: #1181
WIP until #1303 lands
=> Implement the fourth wave of per-reconciler leaderelection

apis/duck/register.go
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
fixes #1407
=> adding constant for annotation

testutils/clustermanager/perf-tests/main.go, testutils/clustermanager/perf-tests/pkg/cluster.go, testutils/clustermanager/perf-tests/pkg/cluster_test.go
Add `--delete` option for the `perf-tests` tool, which can be used to delete all the clusters for the benchmarks in one repository.
/cc @chaodaiG
=> Add --delete option for the perf-tests tool

webhook/conversion.go, webhook/conversion_integration_test.go
This is a requirement when adopting CRD v1 APIs
Addresses: https://github.com/knative/serving/issues/6584
=> Return TypeMeta as part of the conversion response

OWNERS_ALIASES, apis/OWNERS, apis/duck/OWNERS, codegen/OWNERS, controller/OWNERS, pool/OWNERS, reconciler/OWNERS, webhook/OWNERS
- Adding self [whaught] to reviewers for a few areas. 
- Also adding relevant reviewers sections to OWNERS files
Note: This is possibly broken up more than it needs to be. Also it may make sense to add @n3wscott into the controllers group
=> add self to aliases and add reviewers to OWNERS

configmap/manual_watcher.go, configmap/manual_watcher_test.go
- remove redundant checks (iterating nil/empty slice works)
- fix comments
- remove duplicate test
- map scale size fix.
=> Improve manual watcher a bit

test/gcs/gcs.go
Previous right trim and "/" addition prevented the discovery of
top-level directories under the bucket.
/cc @chizhg @chaodaiG
=> Fix gcs ListChildrenFiles and ListDirectChildren

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go, codegen/cmd/injection-gen/generators/packages.go
- Switches to always generating krshapedlogic by default
-krshapedlogic=false can be used to disable
/hold will test-integrate this with downstream
Tested and waiting on:
https://github.com/knative/eventing/pull/3356
https://github.com/knative/serving/pull/8388
=> Expect resources are krshaped by default

testutils/clustermanager/perf-tests/pkg/benchmark.go, testutils/clustermanager/perf-tests/pkg/testdir/test-benchmark
Do not consider files under the benchmark folder as benchmarks.
This PR will fix the Prow job errors after `.ko.yaml` was added to the `benchmarks` folder in serving, see https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-serving-recreate-clusters/1275330518623195136
/cc @vagababov
=> Ingore files under benchmark folder

webhook/admission.go, webhook/admission_integration_test.go
Unblocks https://github.com/knative/serving/pull/8461
This has similar semantics to conversion reviews.
=> Return TypeMeta as part of the admission response

webhook/admission.go, webhook/admission_integration_test.go, webhook/conversion.go, webhook/conversion_integration_test.go
This is required for v1 APIs and it's blocking smooth upgrades from 0.15 to 0.16
https://github.com/knative/eventing/pull/3409#issuecomment-649703275
=> [release-0.15] Have the webhook responses return TypeMeta

injection/sharedmain/main.go, leaderelection/config.go, leaderelection/context.go, leaderelection/context_test.go, leaderelection/ordinal.go, leaderelection/ordinal_test.go
This change allows for (just webhook for now) controllers going through sharedmain to opt into Yanwei's logic by setting several environment variables.
I was able to pull this change in downstream and change the webhook to use a StatefulSet with the following environment:
```
+        # These settings are used for statefulset-based
+        # leader selection.
+        - name: CONTROLLER_ORDINAL
+          valueFrom:
+            fieldRef:
+              fieldPath: metadata.name
+        - name: STATEFUL_SERVICE_NAME
+          value: "webhook"
```
Running the above with 10 replicas and 10 buckets worked as intended (keys were evenly distributed across the replicas).
=> Enable use of StatefulSet in sharedmain.

leaderelection/config.go, leaderelection/config_test.go
Prior locks were for K8s version <1.14
Fixes: #1427
I left the plumbing of the lock setting through everything since there may be a new lock in the future we would want to switch to - if folks feel like this is unnecessary let me know and I can rip it out
=> use coordination.Leases exclusively for leader election

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go, client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/controller.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_controller.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go, controller/options.go
This option is necessary to be able to create reconcilers like Serving's labeler, that is purely adding labels to resources. If that fails, the new automated observed generation handling changes the status and that gets written to the API currently, which is not desired.
=> Add an option to skip automated status updates in a reconciler.

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Slight readability update to https://github.com/knative/pkg/pull/1456
I think this better highlights the checks we do before enacting the status writeback.
Added comments for the additional cases.
=> Update generated reconciler code with a switch

configmap/hash-gen/main.go, configmap/hash-gen/testdata/add_want.yaml, configmap/hash-gen/testdata/update.yaml, configmap/hash-gen/testdata/update_want.yaml
* If you win the hashcode lottery and get a checksum that is all numeric, this parses as an int instead of a string and fails.
* Quotes ensure proper parsing
* This was mysterious and confusing in: #8582
=> Use quotation marks for generated checksums

test/spoof/spoof.go
Serving's TestShouldHaveHeadersSet expects `x-b3-spanid` and
`x-b3-traceid` headers from client, but it was removed by https://github.com/knative/pkg/commit/5658d93fb07ee641a4e0155f3f9c262da7199035.
Due to this, non-Istio ingress like Kourier and Contour started failing the conformance test:
https://testgrid.knative.dev/serving#kourier-stable&include-filter-by-regex=TestShouldHaveHeadersSet
https://testgrid.knative.dev/serving#contour-latest&include-filter-by-regex=TestShouldHaveHeadersSet
So this patch changes to use TraceContextB3Egress for spoof client.
=> Use TraceContextB3Egress for spoof client

controller/controller_test.go, injection/sharedmain/main.go, leaderelection/config.go, leaderelection/config_test.go, leaderelection/context_test.go
This consolidates the core of sharedmain around the new leaderelection logic, which will now be **enabled by default**.
This can now be disabled with `--disable-ha` or by passing `sharedmain.WithHADisabled(ctx)` to `sharedmain.MainWithConfig`.
/assign @pmorie @vagababov @markusthoemmes
=> Enable leader election by default.

leaderelection/chaosduck/main.go, test/ha/ha.go, test/ha/ha_test.go
This adds a new main package under knative.dev/pkg/leaderelection/chaosduck, which
loads the leader election configuration, and periodically enumerates the leases
in the system namespace and kills a leader pod for each sharded reconciler
under a component.
Based on #1304
=> Add a new "chaosduck" e2e test tool for leaderelection.

leaderelection/chaosduck/main.go, test/ha/ha.go, test/ha/ha_test.go
This was part of the review feedback, but it inadvertently introduced a dependency that redefined a flag causing the duck to crash loop.
This copies the function instead of pulling in the dependency.
=> Remove ha.ExtractDeployment dependency.

controller/controller_test.go, leaderelection/config.go, leaderelection/config_test.go, leaderelection/context.go, leaderelection/context_test.go
we only use a single possible way, so no need to have, parse and validate
field that is in effect a constant.
=> Remove the ResourceLock field from the pkg/LE

network/transports.go
The connTimeout parameter in newHTTPTransport isn't actually respected, better to just remove it (the actual connection timeout [happens via DialWithBackoff](https://github.com/knative/pkg/blob/6826f2137c31cbf0f03e6d7988985b353d17d883/network/transports.go#L83))
=> Remove unused connTimeout parameter

test/logstream/kubelogs.go
- watch the pods and track what we already watch
- start watchers for the new pods
For #1488
/assign @markusthoemmes mattmoor
=> Make logstream watch the pods as they change.

test/logstream/kubelogs.go
These cause a race condition as can be seen in https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-serving-continuous/1283612572876017666.
They capture `t` far beyond the test's lifetime (this is `t` of the test that first initializes the logstream).
If we alternatively think that those logs are valuable, we should probably run through the set of active tests and log it to each of them. I didn't think they're all too important to the test output though.
=> Remove logging from pod watcher to avoid race conditions.

controller/two_lane_queue.go, controller/two_lane_queue_test.go
The suggested implementation is basically a Y joint where the data flows from 2 queues into the third queue, with the caveat that one of the paths has priority over the other.
This serves as a drop-in replacement in the controller.
Which will be in a separate pr.
For #https://github.com/knative/pkg/issues/1505
=> Implement Slowlane/FastLane queues

controller/two_lane_queue_test.go
On the prow clusters which are usually strapped for CPU this fails due to wrong order of things.
So the final check should just wait for the channel to close rather than race a timer.
=> Add more time for the checks

network/error_handler.go, network/handlers/doc.go, network/handlers/drain.go, network/handlers/drain_test.go, network/handlers/error.go, webhook/webhook.go, webhook/webhook_test.go
This implements a new `http.Handler` called `Drainer`, which is intended to wrap some inner `http.Handler` business logic with a new outer handler that can respond to Kubelet probes (successfully until told to "Drain()").
This takes over the webhook's relatively new probe handling and lame duck logic with one key difference.  Previously the webhook waited for a fixed period after SIGTERM before exitting, but the new logic waits for this same grace period AFTER THE LAST REQUEST.  So if the handler keeps getting (non-probe) requests, the timer will continually reset, and once it stops receiving requests for the configured grace period, "Drain()" will return and the webhook will exit.
The goal of this work is to try to better cope with what we believe to be high tail latencies of the API …
=> Implement a new shared "Drainer" handler.

controller/controller.go, controller/two_lane_queue_test.go, webhook/certificates/certificates_test.go, webhook/configmaps/table_test.go, webhook/resourcesemantics/defaulting/table_test.go, webhook/resourcesemantics/validation/reconcile_config_test.go, webhook/resourcesemantics/validation/validation_admit_test.go
- we need to poll for len in the webhook tests because we have async propagation now, and check at the wrong time will be not correct.
- otherwise just a drop in replacement.
=> Use two lane queue instead of the regular workqueue

network/handlers/drain.go, network/handlers/drain_test.go
- introduce synthetic timer that gives us the capability to actually trigger events in the drain itself
- unfortunately we still need time.After calls in the test due to the timing for go routines to finish (they race the default: case and lose).
OTOH, the happy runs take virtually no time now.
```
>rt -count=2200
PASS
ok      knative.dev/pkg/network/handlers        1.414s
```
=> Harden the drain tests more

test/logging/logger_writer.go, test/logging/logger_writer_test.go, test/monitoring/monitoring.go, test/prometheus/prometheus.go, test/zipkin/util.go
This change modifies the signature of `PortForwarding` to include an stdout/stderr `io.Writer`. It also provides a writer that can be built from a logging function
=> Added logging of port forwarding stdout/stderr

controller/two_lane_queue.go, controller/two_lane_queue_test.go
So we have a Len() race here. Before we could have len=2, now we can have len=0. I don't know which one's better/worse, but I prefer 0.
Also harden the test to not flake.
=> Reorder statements for more precise behavior

reconciler/testing/table.go
We're playing around with writing TableTests for the Operator (which uses manifestival) and would
like to see if we can get a good comparator for the automatically added last-applied-configuration annotation.
If that ends up being general purpose we can upstream it here, but in general it's nice to be allowed to do
some application specific filtering of the desired state changes.
=> Allow passing custom cmp.Options to TableTest.

metrics/resource_view_test.go
I'm seeing [some flakiness](https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-pkg-continuous/1285092827042156545) in `TestMetricsExport/OpenCensus` which looks like:
```
TestMetricsExport/OpenCensus: resource_view_test.go:359: Unexpected OpenCensus exports (-want +got):
[]metrics.metricExtract(Inverse(Sort, []string{
"global_export_counts<>:2",
"resource_global_export_count<>:2",
- 	`testing/value<project="p1",revision="r1">:0`,
`testing/value<project="p1",revision="r2">:1`,
}))
```
I can't seem to repro locally, but I'm strongly guessing this is timing related and a slightly longer wait will allow all the RPCs to complete.
=> Wait longer for metrics collection to settle for OpenCensus

network/prober/prober_test.go, network/transports.go, network/transports_test.go
This method is not used anywhere outside pkg right now, so it's a safe change.
This will permit activator to set desired maxidle params and cache more connection for better performance
/cc @julz @markusthoemmes
=> Add a method to set possible maxidle params on the transport.

ptr/ptr.go, ptr/ptr_test.go
As per title, to be able to replace the respective workarounds in code. I got inspired by deprecated protobuf packages mostly, that ship the same wrappers.
/assign @julz
=> Add helpers for float pointers.

metrics/metricstest/resource_metrics.go, metrics/metricstest/resource_metrics_test.go, metrics/resource_view_test.go, metrics/workqueue_test.go
Call EnsureRecorded automatically in the "Assert" methods.
This should make testing serving/eventing easier.
Increase test coverage.
/assign @jjzeng-seattle
=> Make EnsureRecorded part of metricstest

controller/helper.go, controller/helper_test.go
As per title. This short-circuits the copy code if the TypeMeta is already correct. Less allocations and stuff :slightly_smiling_face: 
=> Avoid copying object if TypeMeta is already correct.

metrics/memstats_test.go, metrics/metricstest/metricstest.go, metrics/resource_view_test.go
Currently they are not. 'go test -count=2' will miserably fail.
So ensure they are. Also add a helper to return current value (this might be a better way than trying to jump through hoops to erase everything).
Other minor nits.
/assign @evankanderson @yanweiguo
=> Make sure metrics tests are re-entrant

apis/volatile_time.go
Fixes #1426
-Adds inline to the .inner structure for VolatileTime
- Note marshall/unmarshall are implemented already to bypass the default, but this will help users who may be using the tags for codegen
=> add a json tag to volatile_time

test/logstream/kubelogs.go
To enhance debuggability in flaky tests that are suspicious to be chaos induced.
/assign @vagababov @mattmoor
=> Print loglines from chaosduck to all tests.

tracing/opencensus.go
This patch allows to specify service name and hostPort for zipkin tracing.
Currently the serviceName(display in the console) and
host(endpoint) must be same name.
This patch allows to specify both serviceName and host. 
Please also refer to https://github.com/knative/serving/pull/8069.
=> Allow to specify service name and endpoint IP respectively for zipkin tracing

metrics/resource_view.go
There is currently no mechanism to resolve a resource to a unique pointer causing this map to leak
memory.
=> Remove resourceToKey map

metrics/memstats_test.go
At least twice I saw this report +1 over what we expect, which I attribute
to actual GC being collected.
E.g. https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_pkg/1580/pull-knative-pkg-unit-tests/1290650655098146816
So disable GC for the duration of this test
/assign @evankanderson mattmoor
=> Disable GC to reduce test flakiness

test/logstream/kubelogs.go
`eg.Wait` cannot be called before `eg.Go` without tripping Go's race detection.
Internally errgroup uses sync.Wait, which has [the following](https://godoc.org/sync#WaitGroup.Add) warning:
> Note that calls with a positive delta that occur when the counter is zero must happen before a Wait
When `eg.Go` isn't clearly called prior to `eg.Wait` the read of the error field in `eg.Wait` races with the
assignment of the error field in the once of `eg.Go`.
=> Fixes a race in the logstream.

test/logstream/interface.go, test/logstream/null.go
This makes things insensitive to link ordering.
Also add clarity when the null logstream is being used.
=> Replace init with sync.Once

test/logstream/kubelogs.go
The latest change makes eg never to exit. In reality we don't really need EG there at all
and can just store the error.
This will return the _latest_ error, but :shrug:
=> Remove ErrGroup from kubelogs altogether

metrics/stackdriver_exporter.go
We see timeout error logs in Stackdriver. The timeout value in Stackdriver API service side is 12 seconds while the default value of client side is 5 seconds. Increase it to see whether it reduces timeout errors.
=> Use the same timeout value for Stackdriver API

configmap/informed_watcher.go
=> Delete deprecated NewDefaultWatcher func

metrics/opencensus_exporter.go, metrics/resource_view.go, metrics/resource_view_test.go
Somehow, the timing on my machine always "wins" this race even without the sleep, but switch from a 10ms sleep to real `sync.WaitGroup`s since the race can apparently be lost, making the test flaky: https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_pkg/1588/pull-knative-pkg-unit-tests/1291443127265005569
=> Use real synchronization to make sure we get four exports in the OpenCensus test

webhook/resourcesemantics/defaulting/defaulting.go, webhook/resourcesemantics/defaulting/table_test.go, webhook/resourcesemantics/validation/reconcile_config.go, webhook/resourcesemantics/validation/reconcile_config_test.go
=> filter "control-plane" labeled namespaces out of our webhooks

go.mod, go.sum, profiling/server.go, profiling/server_test.go, vendor/modules.txt
- makes code easier to follow
- hides the int32->bool conversions inside the library
=> Switch to the atomic bool from uber package for the profiling flag

metrics/config.go, metrics/record_test.go
There's no point in even producing the metrics if they are not being surfaced in any way anyway.
/assign @vagababov @evankanderson
=> Completely skip metric reporting if backend is 'none'.

apis/duck/v1/status_types.go
Otherwise we return the temp object that loop variable points at.
=> Fix comment to ensure we tell the truth to the world

test/logstream/kubelogs.go
if we don't return the use of `stream` causes a panic
From: https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-serving-continuous/1292853671020728321
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e88beb]
goroutine 104 [running]:
knative.dev/pkg/test/logstream.(*kubelogs).startForPod.func1(0xc0014ccf20, 0xe, 0xc0000e14a0, 0xc0018806f0, 0x24, 0xc001616d20, 0x1f, 0xc001984170)
/home/prow/go/src/knative.dev/serving/vendor/knative.dev/pkg/test/logstream/kubelogs.go:87 +0x27b
created by knative.dev/pkg/test/logstream.(*kubelogs).startForPod
/home/prow/go/src/knative.dev/serving/vendor/knative.dev/pkg/test/logstream/kubelogs.go:69 +0x286
```
=> fix nil pointer

RELEASE-LEADS.md, RELEASE-MASTERS.md
Seed a release master rotation from Serving and Eventing approvers using https://www.random.org/lists/ 
Part of https://github.com/knative/serving/issues/8005
See https://docs.google.com/document/d/1woxDpdw6TrwwF-Y987OYVUFrSgGpyBiR3U8ehf0BX9o/edit#
=> Add a release leads rotation.

injection/sharedmain/main.go
Inject the config into the context.
This seems to have been accidentally removed in #1476 and is a problem for knative/operator#230.
=> Inject the config into the context.

test/logstream/kubelogs.go
Fixes #1615 
No need to really report errors if we're going to just ignore them anyway. Logging them all seems just as fine.
=> Replace error return with logging to all tests in an error case.

hash/bucketer.go, hash/bucketer_test.go
Add `BucketSet.HasBucket` func to get whether the BucketSet has the given BucketName. This will be used to filter endpoints created for leader election buckets.
=> Add a helper func for BucketSet

.github/workflows/go-build.yaml, .github/workflows/go-style.yaml, .github/workflows/go-test.yaml, .github/workflows/go-verify.yaml
Drop GOPATH from all except verify (codegen needs it), and change directories to just use workspace.
Switch to Go 1.15 (go.mod actually controls what's used IIUC).
=> Assorted tweaks to actions.

codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Fixes https://github.com/knative/serving/issues/9073
- if skipStatusUpdates is set for a controler we don't need to process conditions/observed-generation
=> don't pre/post process if skipstatusupdate

controller/controller.go
Debugging https://github.com/knative-sandbox/net-contour/issues/214 I noticed the logging was showing up as:
```
"knative.dev/key":{"knative.dev/key":"serving-tests/service-create-and-update-teaoccuu"}
```
=> Fix the logkey.Key tagging in Enqueue.

test/logstream/kubelogs.go
I see this in Serving:
```
=== CONT  TestSecretVolume
kubelogs.go:197: I 11:01:04.358 controller-79bd7dbf6b-d4fkg [revision-controller] [serving-tests/secret-volume-dgqznzoi-jq457] Reconcile succeeded. Time taken: 21.144µs
kubelogs.go:197: I 11:01:04.621 webhook-59bb47db88-wpwbw [conversion/conversion.go:133] [serving-tests/projected-secret-volume-ogqtvwfy] Converting [kind=Service group=serving.knative.dev version=v1] to version serving.knative.dev/v1alpha1
```
The projected volume inclusion is clearly a collision due to matching suffix.
Since we expect this to be a resource name prefix, expect to see the `/` delimiter prior to is in the key.
=> Make the match about smarter about filtering its own tests.

RELEASE-LEADS.md
Some `net-*` repos no longer depend on knative.dev/serving. Update the doc to reflect this.
/assign @mattmoor @tcnghia
=> Update release leader document

controller/stats_reporter_test.go, controller/two_lane_queue_test.go
The test assumes the threads would schedule in particular way, but they don't.
But what we really care to check is that we thread in the proper RL and it works.
We don't need to check that underlying queue impl works, that's done in its own tests.
So just verify these two things.
=> Fix the flaky test.

metrics/config_observability.go, metrics/config_observability_test.go
Since we have cut the 0.17, we can go for the proper toggle setup:
- if request logging is on — template must be present and the logging will be on
- if the request of logging is off — template can be present, but will not affect whether the request logs will be collected
Really
Fixes https://github.com/knative/serving/issues/8644
/assign @yanweiguo @julz
=> Fix the the request logging boolean toggle

controller/controller_test.go
A series of tweaks to reduce unnecessary pauses in `controller` tests. Most of them related to excessive Sleeps.
Each commit corresponds to 1 test suite. See individual commit messages for details.
Closes #1364
=> Reduce delays in controller tests

configmap/store_test.go, controller/controller_test.go, metrics/config_test.go, webhook/resourcesemantics/validation/validation_deprecated_test.go, websocket/connection_test.go
We need this in order to deprecate the function.
Serving is already free of those.
/assign @taragu mattmoor @tcnghia
=> Remove all ClearAll calls from pkg UTs

system/testing/names.go
Only hardcode the SYSTEM_NAMESPACE if it has not already been set.
=> only hardcode SYSTEM_NAMESPACE if not set

injection/sharedmain/main.go, leaderelection/chaosduck/main.go
Adding an easy entry method next to sharedmain to allow for utilities to leverage injection without being a controller.
Example usage in chaos duck.
=> Allows utilities easy mode for Knative Injection

leaderelection/config.go
`ComponentConfig` is marshaled into string in downstream eventing repository. How ever the newly added field `LeaseName` is a func which can't be marshaled. Ignore this field for marshaling as it is not used in eventing.
=> Ignore func filed for json marshaling

websocket/connection_test.go
This was erroneously changed in https://github.com/knative/pkg/commit/34838c4559697a4502141537a368fac1e09fccd4#diff-6c7213643bc6f930dd8cdc16121ccbc8. It's actually supposed to override the global var.
=> Make test override pongTimeout correctly.

go.mod, go.sum, vendor/knative.dev/test-infra/scripts/e2e-tests.sh, vendor/knative.dev/test-infra/scripts/infra-library.sh, vendor/knative.dev/test-infra/scripts/library.sh, vendor/modules.txt
Produced via:
`./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
=> [master] Auto-update dependencies

reconciler/testing/table.go
If you haver ever written a table test, perhaps you noticed that when several objects
are deleted you need to list them is a particular order. And if you're deleting things in parallel
it's just impossible.
But what we care is that N objects are deleted -- so verify that.
The key is type-name-ns, which should work most of the time.
I've cleaned the tests in Eventing to work with this change
and there's an open PR in serving that would make the tests pass
with this change there too
Fixes #411
=> Permit table test deletions to arrive in arbitrary order.

websocket/connection.go, websocket/connection_test.go
When using a ManagedConnection for unit test, this function can help us know whether the connection has been established so that we can start sending message. Instead of sending message and checking whether it succeeds or not, checking the return of this function is easier.
=> Add IsEstablished method to ManagedConnection to expose whether the connection has been established

apiextensions/storageversion/cmd/migrate/config.go, injection/sharedmain/main.go
This not only gets rid of the master terminology, but is also actually in-line with how `kubectl` itself behaves. Win everywhere!
=> Deprecate --master flag in favor of --server.

resolver/addressable_resolver.go, resolver/addressable_resolver_test.go, webhook/psbinding/reconciler.go
This allows for reconcile deletion to properly remove finalizer and
delete sinkbinding
Followup from #1647
=> Alter URIFromObjectReference to return apierrs

test/ghutil/fakeghutil/fakeghutil.go, test/ghutil/pullrequest.go
There's no need to reference master in these examples. Let's drop them.
=> Remove branch examples referencing master.

reconciler/retry.go, reconciler/retry_test.go
This is an expansion of the workaround that vaikas initially added to address https://github.com/knative/test-infra/issues/2346, however, a few new error types have emerged, which this will retry.
=> Create a dedicated helper for retrying API calls during tests.

webhook/psbinding/psbinding.go
do not fight with azure's webhook for webhooks
Relates to #1590
=> Exclude the control-plane from our webhooks for psbinding webhook.

webhook/configmaps/configmaps.go, webhook/configmaps/configmaps_test.go
We still see users frequently struggle with this and the error message seemingly doesn't help them. This gives a more explicit description of what the user can do to fix the situation.
=> Enhance error message on failure to update _example.

.github/workflows/knative-downstream.yaml, .github/workflows/knative-verify.yaml
Integrate the knative-sandbox/downstream-test-go action that takes two repos that are checked out and upgrades the downstream with an upstream module, and then runs the standard knative repo update-codegen and runs the unit tests.
This PR makes it an FYI that any future PR will test on the following:
- Serving
- Eventing
- Eventing Contrib
- Sample Controller
- Sample Source
=> Adding github action to test downstream repos.

test/spoof/spoof.go
Today Poll delegates to Do and has additional logic to retry certain error conditions returned by Do focused around connection issues.  This means that we are inconsistent about retrying connection issues between Poll and Do.
This change has two main parts:
1. Inline the main logic previously within Do into Poll.
2. Invert the previous relationship (Poll -> Do) to have Do effectively become "Poll once".
With this, Do should have consistent connection retry semantics to Poll (because it IS just a call to Poll).
See also: https://knative.slack.com/archives/CA4DNJ9A4/p1600011374118700
/cc @tcnghia 
/assign @tcnghia 
/hold
I want to HOLD this while I validate it downstream, since Serving is the real test.
=> Make Do have consistent retry semantics to Poll.

test/spoof/spoof.go
Not all errors result in polling stop — it must be an error we don't retry upon
=> Fix a nit in the spoof

test/ingress/ingress.go, test/spoof/spoof.go
This is loosely based on similar logic that I added to kingress conformance testing here:
https://github.com/knative/networking/blob/611f989aa593e513688d0f0047701e8352571ac4/test/conformance/ingress/util.go#L904-L912
The basic idea is that in our custom dialer we look at the requested port and translate that to the service's NodePort when present.
This is in support of running Serving's e2e testing on top of KinD environments without service `type: LoadBalancer`.
/hold
This needs to be staged as there are a few breaking changes to Serving that need to be fixed.
=> Teach the spoofing client to support NodePort.

controller/controller_test.go
Fixes flakes such as https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_pkg/1709/pull-knative-pkg-unit-tests/1305911274105737216.
the [docs for the Len() function in queue package say](https://github.com/kubernetes/client-go/blob/master/util/workqueue/queue.go#L129):
~~~~
// Len returns the current queue length, for informational purposes only. You
// shouldn't e.g. gate a call to Add() or Get() on Len() being a particular
// value, that can't be synchronized properly.
~~~~
Testing locally, when we see the flake we'll then see the correct length immediately after, so it appears to be caused by inconsistent reads. Directly sending the len to the channel when the poll finishes rather than effectively re-polling an extra time in the test seems to fix up the flakes. Since …
=> Fix flakes in EnqueueAfter tests

injection/sharedmain/main.go
Deployments that are H(P)A need to provide the pod name envvar via downward api.
Activator and QP are already doing this.
For #1408 
=> Inject the pod name into logger when provided in the envvars

logging/logkey/constants.go, webhook/admission.go
It might contain the sensitive data, so print it to debug log.
Fixes: #1397
=> Remove patch detail for webhook being logged on info

webhook/psbinding/README.md, webhook/psbinding/reconciler.go, webhook/psbinding/table_test.go
The aim of this PR is allowing for custom code to reconcile possible sub-resources related to a `Bindable` resource.
The concrete use case is for a binding for VPA (`VPABinding`) where other than `PodSpecable` target reference we need to modify other resources (`VerticalPodAutoscaler` and one other custom resource).
Sample usage:
```
type VPASubresourcesReconciler struct {
}
func (vsr *VPASubresourcesReconciler) Reconcile(ctx context.Context, fb psbinding.Bindable) error {
// reconcile VPA resource
}
func (vsr *VPASubresourcesReconciler) ReconcileDeletion(ctx context.Context, fb psbinding.Bindable) error {
// delete related resources
}
```
```
vpaReconciler := vpa.NewVPASubresourcesReconciler(...t)
c := &psbinding.BaseReconciler{
...,
SubResourcesReconciler: &vpaReconciler,
}
```
Once we …
=> add subresource reconciler for bindings BaseReconciler

webhook/stats_reporter.go, webhook/stats_reporter_test.go
Proposed in relation to https://github.com/tektoncd/pipeline/issues/2872.
Motivation: Common use cases for this webhook involve using Kubernetes's generateName API to randomise resource names (this is a good idea in Tekton pipelines, for example, where there are uniqueness constraints. That means that the webhook metrics here end up with very high cardinality, which makes Prometheus fall over. Even without generateName, it is possible to shoot oneself in the foot this way. 
This commit just removes the resource_name label altogether.
=> Remove resource_name tag from webhook stats

network/transports.go
Same as https://github.com/knative/serving/pull/9488.
Since go 1.13 http.Transport has a Clone method (more context in https://github.com/golang/go/issues/26013) which means we can inherit and override the defaults rather than re-stating them. This also makes it clear that we're overriding the http.DefaultTransport default for ForceAttemptHTTP2 here, which we are.
/assign @markusthoemmes @vagababov
=> Use http.Transport.Clone in preference to copy-pasting defaults

.golangci.yaml, codegen/cmd/injection-gen/generators/packages.go, metrics/config.go, metrics/config_test.go, metrics/exporter.go, test/logstream/kubelogs.go, webhook/conversion.go
Super useful linter to catch dead code hidden in parameters and return values.
=> Enable unparam linter to catch unused parameters

websocket/connection.go, websocket/connection_test.go
`NewDurableSendingConnection` creates a managed connection which is connecting asynchronously. We have to wait the connection to be established before sending message.
Proposed to add a function `NewDurableSendingConnectionGuaranteed` to return a connection which can be used immediately by wrapping a wait.
Also remove `IsEstablished` as we can use `Status` instead. Its downstream usage has been removed.
=> Add a func to return a connection which has been established

RELEASE-LEADS.md
- test-infra no longer deps on pkg
- Adding new repos in knative-sandbox
=> Updates to release leads workflow from 0.18 learnings

configmap/informed_watcher_test.go
The problem is that the original test presumed the 2 other backgound calls have
finished already.
Which is not really true always.
E.g. here: https://github.com/knative/pkg/pull/1746/checks?check_run_id=1179720602
So just wait for all 3 items that we expect to pass.
Also other nits around the file
=> Fix the racy test.

test/helpers/name.go, test/helpers/name_test.go
It's been a longterm pet peeve of mine that we don't name test functions TestAutoTLS etc, because this
function will mutilate the names in to t-l-s, etc.
So collect a list of well known names and catch them separately.
This is not superperformant, some trie would do this job better, but since
this is test name generation, I'll let it slide :-D
=> Fix the resource naming for known terms

injection/sharedmain/main.go
The EnableInjectionOrDie starts informers immedidately in a go
routine, which changes the order of informer start and controller
setup. As a result setting resync period to informer handler will
be ignored as the informer is already started. Though this will
likely affect more components, changing the EnableInjectionOrDie
function will break the API, so this is a temporary solution to
fix all the controllers depending on sharedmain.
This is a temporary solution to #1757 . We might change it to
use whatever solution #1757 will result in, but for now this can be
an easy fix for controllers depending on sharedmain.
=> Delay start of informers in sharedmain

metrics/resource_view.go, metrics/resource_view_test.go
Currently, pkg/metrics keeps one meterExporter for each resource the system is sending metrics about.
As resources  fall off the system and no longer send metrics (deleting a knative revision, for example), a slow leak occurs as orphaned meterExporters are never cleaned up.
This PR adds a TTL expiry bit for each meterExporter, and cleans them up when they expire.
=> Add TTL expiry for items in allMeters.meters map

injection/config.go, injection/context.go, injection/injection.go, injection/sharedmain/main.go, leaderelection/chaosduck/main.go
Supersedes https://github.com/knative/pkg/pull/1757
Reverts https://github.com/knative/pkg/pull/1767
=> Put EnableInjectionOrDie back on the main path

injection/config.go
Fixes #1700 
Add `--kube-api-qps` and `--kube-api-burst` command-line flags 
to control client QPS and Burst respectively.
The default value is set to 0 to keep backward compatibility.
=> Allow override QPS and Burst via flag

hash/bucketer.go, hash/bucketer_test.go, leaderelection/context_test.go
The `BucketList` func is only used in tests. No need to return a random order. Make the return sorted to simplify tests.
=> BucketList cleanup

pool/pool_test.go
There's one sync/atomic.Value, but value already is a wholesome
type, so no need to change that one.
I guess this one is test, so I ignored before :/
=> Final sync/atomic removals

injection/sharedmain/main.go
maxprocs.Set already [uses a no-op logger by default](https://github.com/uber-go/automaxprocs/blob/master/maxprocs/maxprocs.go#L56-L57), so no need to explicitly pass one. (The non-noop printer is [in the top-level automaxprocs package](https://github.com/uber-go/automaxprocs/blob/master/automaxprocs.go#L32), which we no longer import).
=> Use default no-op logger for maxprocs

injection/sharedmain/main.go, metrics/stackdriver_exporter.go, test/clients.go, test/ha/ha.go, test/ingress/ingress.go, test/kube_checks.go, test/logstream/interface.go, test/monitoring/doc.go, test/monitoring/monitoring.go, test/prometheus/prometheus.go, test/spoof/spoof.go, test/zipkin/doc.go, test/zipkin/util.go
Use  `kubernetes.Interface` over `*kubernetes.Clientset` and `*test.Client`.
The change to the helpers is a breaking change, but simple to fix downstream.
=> use k8s.interface

metrics/config_observability.go, metrics/config_observability_test.go
For consistency with existing `EnableReqLogKey` constant, and because otherwise the [dots don't line up when these two keys are used together outside the package, which makes the pedant in me sad](https://github.com/knative/serving/blob/3b649a8bb37ec82d54089c46774529af55acd886/test/e2e/logging_test.go#L57-L58) 😅.
=> Add EnableProbeReqLogKey constant

configmap/testing/configmap.go
This confused someone in https://github.com/knative/serving/pull/9778#issuecomment-709285563, and I can't think of any obvious downside to including a suggested fix since the person hitting this may often not know why.
=> Add suggested fix when checksums dont match

metrics/config_observability.go
this had references to the monitoring bundle which is being removed here: https://github.com/knative/serving/pull/9807
=> drop the default log url template

test/prometheus/prometheus_test.go
As per title, it's not necessary to specify all the functions that are never called anyway.
/assign @vagababov @julz
=> Simplify test helpers for prometheus API

metrics/resource_view_test.go
This should avoid failures like in https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_pkg/1818/pull-knative-pkg-unit-tests/1318114477454921728, where the test failed because of:
```
resource_view_test.go:371: failed to fetch prometheus metrics: Get "http://localhost:19090/metrics": dial tcp 127.0.0.1:19090: connect: connection refused
```
/assign @julz @vagababov
=> Wait for prometheus server to start serving before fetching metrics

controller/controller_test.go
This should avoid race conditions as seen in https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_pkg/1817/pull-knative-pkg-unit-tests/1318077986871709698.
/assign @vagababov @julz
=> Make sure all controllers finish before ending test

test/logstream/v2/stream.go, test/logstream/v2/stream_test.go
- handle `event.Object == nil` case. We have reports of this. Strange
edgecase, but :shrug:.
- add tons of tests around various cases, should raise the coverage a
bit (although, we exclude test, still should be better).
/assign @dprotaso @tcnghia @markusthoemmes
=> Various stuff around the logstream

injection/config.go, test/e2e_flags.go
This fixes test errors like in https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_serving/9864/pull-knative-serving-istio-stable-no-mesh/1318368526817300480, where the tests no longer properly default the kubeconfig variable as we have dropped said defaulting in https://github.com/knative/pkg/commit/fc447086b7b09678604d545098401f79bfa10032.
It also slightly simplifies the existing defaulting logic, as `KUBECONFIG` is read first nonetheless, so just default the flag to that.
Successfully tested in https://github.com/knative/serving/pull/9869
=> Simplify defaulting and force-default kubeconfig location in tests

configmap/hash-gen/main.go, controller/controller.go, kmeta/names.go, metrics/config.go, reconciler/events.go, test/gcs/gcs.go, test/logging/example_tlogger_test.go, test/logging/tlogger.go, test/mako/config/benchmark.go, test/mako/stub-sidecar/main.go, testutils/clustermanager/perf-tests/pkg/benchmark.go, tracing/config/tracing.go
As per title.
This gets rid of
```
WARN [runner/nolint] Found unknown linters in //nolint directives: stylecheck for backcompat., the newer package has different interface. 
```
and also adheres to the best practice of not having a space in front of `nolint`, see https://golangci-lint.run/usage/false-positives/#nolint
=> Fix nolint warnings and adhere to best practices

test/logstream/v2/stream.go, test/logstream/v2/stream_test.go
- cover the actual log parsing (without verification for now)
- cover errors from starting stream
- other nits
```
>go test -race -count=5
PASS
ok  	knative.dev/pkg/test/logstream/v2	2.625s
```
=> More test coverage for logstream

metrics/config.go, metrics/config_test.go
- use switch
- add new method that won't trigger lint, with a deprecation notice when deps are updated
- other minor things
- string(nil) actually works, so no need for an extra if
/assign @yanweiguo @evankanderson
=> Some cleanups arounds the metrics code

metrics/config.go, metrics/config_test.go
Before we roll those out, let's get rid of the new linting issues (API stuttering).
Also:
- Made the old functions deprecated.
- Fixed comments.
- Added comments to the new functions.
=> Fix API stutter in metric option functions

logging/object_encoders.go
As per title. This doesn't behave the way we expected it to. See https://github.com/knative/serving/pull/9923 for more info. This is only used in Serving now, so we can safely drop this after https://github.com/knative/serving/pull/9923 merges.
=> Remove NamespacedName logging helper

webhook/certificates/certificates.go, webhook/configmaps/configmaps.go, webhook/psbinding/psbinding.go, webhook/psbinding/reconciler.go, webhook/resourcesemantics/conversion/conversion.go, webhook/resourcesemantics/conversion/reconciler.go, webhook/resourcesemantics/defaulting/defaulting.go
zap doesn't do this well, when errors are not presented without zap.Error
=> Fix the error/warn log usage

webhook/resourcesemantics/conversion/conversion.go
Backporting #1687 
Fixes: https://github.com/knative/pkg/issues/1686
(cherry picked from commit 3ff7bcc4225975f76b6cc294a7ca9c5db32de222)
This has caused us some problems in 0.17 release.
=> [0.17] Backport 1687

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/apps/v1/deployment/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go
The returned `resource` is broken (as nothing on it) if the `Patch` operation fails, which causes the produced event to be incomplete and in the wrong namespace (`default`).
Actually using a known-to-be-correct version of the object fixes the issue.
=> Fix produced events if patching a finalizer fails

leaderelection/config.go, leaderelection/context.go
Revert "Make knativeResourceLock exported (#1656)"
This reverts commit a79802cd7814b248b4676cbe7561b81f3b6c5c83.
Discussion: https://knative.slack.com/archives/C9JP909F0/p1603733670379700?thread_ts=1603733520.379100&cid=C9JP909F0
=> Eventing no longer needs this constant

apis/duck/v1/test/fuzzer.go, apis/duck/v1/test/roundtrip_test.go, apis/duck/v1beta1/test/fuzzer.go, apis/duck/v1beta1/test/roundtrip_test.go
Signed-off-by: Ville Aikas <vaikas@vmware.com>
We currently ship fuzzers in our binaries, this is hoping to remove the last bits of them. Note that I did not inline them into the roundtrip_test because I was thinking that if downstream wants to test them, they can continue to do so.
Addresses:
https://github.com/knative/eventing/issues/4398
https://github.com/knative/serving/issues/9725
=> move fuzzers

RELEASE-LEADS.md
This patch update release schedule by moving 2 weeks for end of year holidays.
It is now sync with https://github.com/knative/community/blob/master/mechanics/RELEASE-SCHEDULE.md
/cc @tcnghia @evankanderson @slinkydeveloper
=> Update release schedule by moving 2 weeks for end of year holidays

depcheck/depcheck.go, depcheck/depcheck_test.go, go.mod, vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go, vendor/golang.org/x/tools/go/packages/doc.go, vendor/golang.org/x/tools/go/packages/external.go, vendor/golang.org/x/tools/go/packages/golist.go, vendor/golang.org/x/tools/go/packages/golist_overlay.go, vendor/golang.org/x/tools/go/packages/loadmode_string.go, vendor/golang.org/x/tools/go/packages/packages.go, vendor/golang.org/x/tools/go/packages/visit.go, vendor/golang.org/x/tools/internal/packagesinternal/packages.go, vendor/golang.org/x/tools/internal/typesinternal/types.go, vendor/modules.txt
See the example test for illustrative examples of usage.  It is notable that the gofuzz test failed until I rebased on Ville's recent change.
The goal here is ultimately to assert that our key libraries don't take on heavy dependencies to combat the binary-size bloat that currently afflicts the queue-proxy.
=> Add a test package for making assertions about dependencies.

signals/signal.go
Return a typed `context.Canceled` error following the context package
semantic.
Closes: #1854
Might break existing users if they rely on the current error string
being returned with string matching, which is unlikely though.
Signed-off-by: Michael Gasch <mgasch@vmware.com>
=> Return context.Canceled error in pkg/signals

metrics/resource_view_test.go
Ref https://github.com/knative/pkg/issues/1672
This seriously impacts developer productivity, so let's skip until fixed.
/assign @julz @vaikas
=> Skip flaky OpenCensus exporter test until fixed

reconciler/testing/reactions.go, reconciler/testing/reactions_test.go
Signed-off-by: Ville Aikas <vaikas@vmware.com>
Add a vararg that allows you to induce failures for only specific subresources.
I want that here:
https://github.com/knative/eventing/pull/4435
=> Fix issue 1876

version/version.go, version/version_test.go
This patch bumps up `defaultMinimumVersion` to v1.17.0
As per https://github.com/knative/community/issues/245#issuecomment-718316003,
v0.19(next release)'s minimum version is v1.17.
/cc @dprotaso @mattmoor @evankanderson
=> Bump kubernetes minimum version to v1.17.0

version/version.go, version/version_test.go
When we have pre-release version it is very unintuitive with the default error message, since just looking at the string
`1.15.11-abs-1234` is larger than `1.15.11`, but semver treats `-abs-1234` as a prerelease version and hence smaller than
`1.15.11`.
So expand the error in this case
Fixes #1883
=> Add tests for pre-release versions and add a better error message

RELEASE-LEADS.md
Followup of https://github.com/knative/pkg/pull/1803
As explained in https://github.com/knative/pkg/pull/1803#discussion_r512828976, the 2020-01-06 is epiphany in most european countries, so it might be problematic to reach out eu folks. I think it's safer if we cut pkg the 2020-01-07
/cc @tcnghia @evankanderson @nak3 @markusthoemmes 
=> Pushed pkg cut 2 days further for release v0.20

metrics/config.go, metrics/config_test.go, metrics/exporter.go, metrics/prometheus_exporter.go, metrics/prometheus_exporter_test.go
Right now controller, autoscaler pods etc emit metrics using "0.0.0.0" which allows an arbitrary pod to view sensitive service information eg list all svcs etc in a multi-tenancy setting. We can disable metrics by setting no metrics backend, but ideally we would like a fine-grained configuration. My use case is to allow metrics to be exposed safely via a side-car like [rbac-proxy](https://github.com/brancz/kube-rbac-proxy). In this scenario first step is to constraint metrics on localhost by using an env var to pick up the right addr.
=> Add host config option to the prometheus exporter

metrics/config_observability.go, metrics/config_observability_test.go
Turning profiling on or off toggles full rolling restart
of knative pods. And if profiling QP is not of interest, this
might be quite undesireable. To permit that.
For https://github.com/knative/serving/issues/10051
=> Add a flag to disable QP profiling.

reconciler/testing/tracker.go, reconciler/testing/tracker_test.go, tracker/enqueue.go, tracker/enqueue_test.go, tracker/interface.go
This allows an arbitrary client to fetch all the observers of a given object. Ultimately, this enables an informer setup that can use this knowledge as a filter to decide whether or not the current object is actually watched by anything.
/assign @mattmoor @dprotaso
=> Add GetObservers to tracker interface

apis/duck/cached_test.go, controller/controller_test.go, metrics/stackdriver_exporter_test.go, test/gcs/mock/mock_test.go, webhook/psbinding/table_test.go
As per title. Dummy and "sanity check" are considered divisive language.
=> Fix a few more occurrences of divisive language

resolver/addressable_resolver_test.go
I was looking at the #923 (it'll be quite some effort to get the
informer there, or create dynamic one for k8s services),
but nonetheless clean the test up.
- Rename the getters to exclude word get (as go style suggests).
- The errors test contains only errors, so stream line it
- Ensure errors are also idempotent, which wasn't.
/assign @n3wscott mattmoor
=> Some small changes for the URL test

test/upgrade/functions.go, test/upgrade/skip_at_verification_test.go
Fixes #1911 
- Issuing a `Skip` at BackgroundOperation's verify stage doesn't hang tests anymore
=> Skip at BackgroundOperation's verify stage doesn't hang tests

network/h2c.go, network/network.go
Also remove the constant that is not used anywhere.
=> Use the same dial with backoff for H2C as we do for HTTP/1.1

webhook/env.go, webhook/env_test.go
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Ref: https://github.com/knative/eventing/issues/4530
This is currently used here
https://github.com/knative/eventing/blob/52597d174b52a680756b52b377c81bfb96fb636b/pkg/logconfig/config.go#L37
Moving it to pkg to be used across all knative components
=> Add webhookname from env

metrics/prometheus_exporter.go
The logging message is quite confusing since there is an opencensus exporter.
=> Fix logging message when creating a Prometheus exporter

test/request.go, test/spoof/request.go, test/spoof/response_checks.go, test/spoof/spoof.go
This helps avoid pulling in the pkg/test globals
Note: I left aliases so this shouldn't be a breaking change
=> move some spoof helpers to the spoof package

client/injection/apiextensions/client/client.go, client/injection/kube/client/client.go, codegen/cmd/injection-gen/generators/client.go
This uses the presence of the config key to determine whether
this is an injection context, and if it is not, the panic
message includes a notice about injection context behavior.
=> Fail louder when bad context given to injection

configmap/informed_watcher_test.go
Fixes: https://github.com/knative/pkg/issues/1907
=> fixes TestInformedWatcher flake

test/mako/sidecar.go
changeset.Get does not work well when the test image is in the
vendor directory because there is no kodata setup. After this
commit, failure to get the commit id will result in a
log entry instead of failing the whole test.
=> feat/perf-test: continue test when fail to get commit id

version/version.go, version/version_test.go
As per title.
Several users have hit this inconvience already (pre-release versions are by definition smaller than "normal" versions) and we've added a more verbose log message in the past to accomodate.
I can't think of a situation where you would not want to actually allow a pre-release version of a specific Major.Minor.Patch level, if you do not specify a very specific pre-build number, so this always assumes "-0" if no other pre-release version is specified.
=> Default to the lowest pre-release version to be the minimum

profiling/server.go
With this folks can override the default 8008 with PROFILING_PORT.
Fixes: https://github.com/knative/pkg/issues/1948
=> Make the profiling port configurable via envvar.

webhook/helper.go, webhook/helper_test.go, webhook/psbinding/psbinding.go, webhook/resourcesemantics/defaulting/defaulting.go, webhook/resourcesemantics/defaulting/table_test.go, webhook/resourcesemantics/validation/reconcile_config.go, webhook/resourcesemantics/validation/reconcile_config_test.go
This is an alternative fix for #1590. Instead of arbitrarily adding a label from a different project to avoid the reconcilers racing, this adds "smart" handling of the selectors in that labels not inside the knative.dev domain are plainly ignored and our own selectors are added additively.
Fixes #1943
```release-note
Fixed an issue where our webhooks arbitrarily ignored namespaces labeled with `control-plane`.
```
/assign @mattmoor @n3wscott @dprotaso
=> Add smart handling of selectors in webhooks

leaderelection/context.go
I want to be able to use this directly (in place of `WithDynamic`) from the autoscaler, since it wants the bucket set, which `WithDynamic` builds but doesn't return 😞
=> Expose the statefulset constructor

metrics/config.go, metrics/config_test.go, metrics/exporter.go, metrics/prometheus_exporter.go, metrics/prometheus_exporter_test.go
Backporting #1882, cherry-picked c73d344c89a7e80d9e416cea5b4a797e1195cf0.
=> [0.19] Backport "Add host config option to the prometheus exporter (#1882)"

apis/testing/conditions.go, source/source_labels.go, source/source_labels_test.go, source/source_stats_reporter.go, test/upgrade/asserts_test.go, test/upgrade/execute_failures_test.go, test/upgrade/functions.go, test/upgrade/functions_test.go, test/upgrade/private_types.go, test/upgrade/steps.go, test/upgrade/suite_examples_test.go, test/upgrade/suite_execution.go, test/upgrade/testing_operations_test.go, test/upgrade/testing_types_test.go, test/upgrade/types.go, test/upgrade/vars.go, test/upgrade/zaptest_buffer_test.go
- Run `sed` on the entire codebase to format copyright headers that diverge from the project's [boilerplate](https://github.com/knative/pkg/tree/master/hack/boilerplate)
The "Boilerplate Check" GitHub Action reports those drifts on new PRs, but not for files that already existed in the repo before the check was introduced.
=> Format copyright headers to match boilerplate

metrics/resource_view.go, metrics/resource_view_test.go
Through a bit of cleanup work in Knative Serving, it got kinda apparent that our metric recording calls are kinda expensive. I triaged it down to the `resourceToKey` being quite expensive.
Discussing with @evankanderson, we came up with this quick fix to make the allocations of the functions much more reasonable without coming up with a different way of handling the keys here altogether.
```
benchmark                               old ns/op     new ns/op     delta
BenchmarkResourceToKey/0-labels-16      139           2.38          -98.29%
BenchmarkResourceToKey/1-labels-16      677           168           -75.18%
BenchmarkResourceToKey/5-labels-16      2344          802           -65.78%
BenchmarkResourceToKey/10-labels-16     4625          1645          -64.43%
benchmark …
```
=> Fix excessive allocation in the resource metrics

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/apps/v1/deployment/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go
This call is redundant as the method is already put onto the logger a few lines above.
=> Remove useless logger creation

test/logstream/README.md, test/logstream/interface.go, test/logstream/v2/stream.go, test/logstream/v2/stream_test.go
Enable e2e tests to collect logs not just from the controllers  but also containers across multiple namespaces ( like queueproxy)
Fixes #1932
=> Enable multi namespace log collection in e2e test

controller/controller.go, logging/config.go, websocket/connection.go
Ref #1968 
This removes all occurrences where we unnecessarily allocate an intermediate logger rather than using the respective logger directly. Debug statements are additionally guarded as that level is disabled in production most likely.
=> Remove unnecessary intermediate loggers

configmap/informer/informed_watcher.go, configmap/informer/informed_watcher_test.go, configmap/manual_watcher.go, configmap/manual_watcher_test.go, configmap/nodep_test.go, injection/sharedmain/main.go, tracing/setup.go
/hold
Abusing the downstream test to see what breaks 🤞
=> Splitting configmap package to avoid heavy dependencies

.github/workflows/nostackdriver.yaml, depcheck/depcheck.go, tracing/depcheck_test.go, tracing/nostackdriver.go, tracing/opencensus.go, tracing/stackdriver.go
This teaches `depcheck` to support passing build flags through, and uses it to ensure that with `-tags=nostackdriver` that the expensive stack driver libraries are not linked.
I'm starting in `./tracing` since it is considerably simpler than the mess in metrics, but my intention is to do something similar in `./metrics` next.
=> Introduce a nostackdriver build tag

network/handlers/drain.go, network/handlers/drain_test.go
- Besides of directly returning "200 OK", drainer accepts customized kubelet probe check to perform when the handler is not in Drain status.
=> Drainer supports customized kubelet probe check

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/apps/v1/deployment/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go, controller/controller.go, webhook/certificates/certificates.go, webhook/configmaps/configmaps.go, webhook/psbinding/psbinding.go, webhook/psbinding/reconciler.go, webhook/resourcesemantics/conversion/reconciler.go, webhook/resourcesemantics/defaulting/defaulting.go, webhook/resourcesemantics/validation/reconcile_config.go
This change introduces a new `controller.NewSkipKey` method to designate certain reconciliations as "skipped".
The primary motivation for this is to squelch useless logging on non-leader replicas, which currently report success with trivial latency.
I have plumbed this through existing reconcilers and the code-gen so most things downstream should get this for free.  In places where a key is observed, I do not mark the reconcile as skipped as the reconciler did some processing for which the awareness of side-effects and reported latency may be interesting.
=> Use special error type to designate skips.

apis/duck/ABOUT.md, injection/README.md, webhook/certificates/controller.go, webhook/configmaps/controller.go, webhook/psbinding/README.md, webhook/psbinding/controller.go, webhook/resourcesemantics/conversion/controller.go, webhook/resourcesemantics/defaulting/controller.go, webhook/resourcesemantics/validation/controller.go
[I dropped the queue name being added to the logger](https://github.com/knative/pkg/pull/1991/files#diff-3c5bb5f48211873c58fcba055dcae2ac7b1958969219e06e1508d76d485dace7L233) in https://github.com/knative/pkg/pull/1991 but forgot to keep the webhook logger names stable
=> preserve the stable webhook logger names we had before

webhook/certificates/certificates.go, webhook/certificates/certificates_test.go, webhook/certificates/resources/certs.go, webhook/certificates/resources/certs_test.go, webhook/certificates/resources/secret.go
- :broom: Webhook uses `ed25519` rather than RSA 2048.
- :broom: Change the expiration of the certificate to seven days and the recreation time to one day before expiration.
```release-note
NONE
```
**Docs**
```docs
```
=> Switch Webhook to ed25519 and expiration of the certificate to seven days

apis/duck/v1/addressable_types.go
-  Add kmeta.OwnerRefable support to AddressableType.
```release-note
AddressableType now implements the kmeta.OwnerRefable interface.
```
=> allow the addressable ducktype to act as an ownerref

kvstore/kvstore_cm.go, kvstore/kvstore_cm_test.go
Signed-off-by: Michael Gasch <mgasch@vmware.com>
- Fix bug in kvstore causing nil pointer panic on an empty map (map without data)
/kind  bug
Fixes #2001 
```release-note
```
**Docs**
```docs
```
=> Fix nil pointer panic in kvstore

network/h2c.go, network/transports.go
Fixes #2006.
Go's http client helpfully adds an "Accept-Encoding: gzip" header if not
already present, and unzips the response if it did so. While this is
often the right thing to do, it is not the right thing to do if we're
reverse proxying since (a) it means we add a header to the request the
client didn't actually ask for (b) it means we end up uncompressing
things in the proxy, which e.g. for activator/QP is not what we want.
- :gift: Add `NewProxyAutoTransport` which is an auto-transport with DisableCompression=true set on the underlying transports.
```release-note
Adds NewProxyAutoTransport(), this method returns a transport which automatically selects between HTTP and H2c, and which is suitable for use by reverse proxies. Specifically it sets …
```
=> Allow setting DisableCompression in NewAutoTransport

RELEASE-LEADS.md
This includes a list of updates to the release process from @nak3 and I during the 0.20 release
- Reorganized and enhanced the paragraph explaining the actual repository release
- Added additional explanation of the state of `go.mod` file before the cut
- We don't need to cut net-kourier after serving as it does not depend on Serving repo.
- Added `reconciler-test` cut
=> Updates to the release process with 0.20

metrics/e2e_test.go, metrics/resource_view.go, metrics/resource_view_test.go
- Unregisters views that cause part of https://github.com/knative/serving/issues/10516, details here: https://github.com/knative/serving/issues/10516#issuecomment-770771649
/kind bug
=> Unregister views to avoid slow oom issue during meter cleanup

metrics/resource_view.go, metrics/resource_view_test.go
Backport of #2005, need to pull it downstream as well.
/cc @markusthoemmes @evankanderson
=> [RELEASE-0.20] Unregister views to avoid slow oom issue during meter cleanup (#2005)

controller/controller.go
Most resources stamped out by knative controllers have OwnerReferences synthesized via `kmeta.NewOwnerRef`, which requires the parent resource to implement `kmeta.OwnerRefable` for accessing the `GroupVersionKind`.
However, where we setup informer watches on those same children resources we have essentially relied on direct synthesis of the `Group[Version]Kind` where we could instead provide an empty instance of the controller resource and leverage `GetGroupVersionKind` to provide the GVK used for filtration.
So where before folks would write:
```golang
FilterFunc: controller.FilterControllerGK(v1alpha1.WithKind("MyType"))
```
They may now write:
```golang
FilterFunc: controller.FilterController(&v1alpha1.MyType{})
```
The latter is preferable in part because it is more strongly typed, …
=> Add symmetric filter helped based on OwnerRefable.

metrics/exporter.go, metrics/metrics_worker.go, metrics/testing.go
- Removes the global metrics config mutex to avoid a potential deadlock when k8s client is used due to the 
registered metrics hooks in the client.
- This PR preserves the previous semantics when managing the metrics config etc so it should be transparent from a user point of view.
- It follows the worker approach in the opencensus lib.
/kind bug
Fixes #807 
/cc @vagababov @evankanderson
=> Fix potential deadlock when k8s client is used

network/handlers/drain.go, network/handlers/drain_test.go, network/network.go, network/network_test.go
And hide it, since no need to export it, if nobody's going to use it.
🧹 
/assign @tcnghia
=> Move IsKProbe to drainer, since it's the only place it's used

metrics/record_test.go
* Adds a benchmark to be used as a baseline for future changes or migrations.
This is helpful especially because metrics reporting happens in many places and after some user request eg. [eventing](https://github.com/knative/eventing/blob/149ebe660b60f43975fba414034a7c90682e8804/pkg/adapter/v2/cloudevents.go#L120).
/cc @evankanderson 
I used this benchmark to compare with branch release-0.20. Results are bellow.
Possibly due to our change in #2031 moving to a channel implementation we add some overhead ~1ms but for overloaded
pods with many goroutines things get better (I will compare in the future with using atomic values) probably due to [this](https://stackoverflow.com/questions/57562606/why-does-sync-mutex-largely-drop-performance-when-goroutine-contention-is-more-t).
It would be nice …
=> Add benchmark for metrics recording

client/injection/apiextensions/client/client.go, client/injection/apiextensions/client/fake/fake.go, client/injection/kube/client/client.go, client/injection/kube/client/fake/fake.go, codegen/cmd/injection-gen/generators/client.go, codegen/cmd/injection-gen/generators/fake_client.go, injection/clients.go, injection/clients_test.go, injection/interface.go
This is a stepping stone towards moer unit test stability around informer usage. See https://github.com/knative/serving/pull/10930 for an end to end example.
In a nutshell, we'd like to be able to fetch all injected clients generically to be able to muck with them and make sure everything is synced when we think it is.
=> Implement getter machinery to generically fetch all injected clients

reconciler/testing/context.go, webhook/webhook_test.go
Implements a helper that circumvents https://github.com/kubernetes/kubernetes/issues/95372 and makes sure the informers are **really really** running and are really really synced correctly. See https://github.com/knative/serving/pull/10930 for proof.
/assign @vagababov @julz
=> Add RunAndSyncInformers helper that makes sure informers are synced in tests

webhook/README.md
`NewAdmissionController` was moved to `resourcesemantics/validation` in #848 and this doc wasn't updated.
/kind documentation
```release-note
NONE
```
**Docs**
```docs
Small correctness change.
```
=> Update webhook/README.md to reflect current packages

version/version.go, version/version_test.go
Minimum version for k8s was v1.18.x since Knative v0.21.x but it was not updated:
https://github.com/knative/community/blob/main/mechanics/RELEASE-VERSIONING-PRINCIPLES.md#knative-serving-version-table
This patch updates it. Note, the doc was already updated.
/cc @dprotaso @evankanderson  @markusthoemmes
=> Bump k8s min version to v1.18.0

reconciler/testing/context.go
/kind bug
Update the faked testing context to facilitate the faked `filterinformaterfactory` setup. 
Without the correct faked context,  the PR https://github.com/knative/serving/pull/10266 always failed with UT by:
```
ok  	knative.dev/serving/pkg/reconciler/autoscaling/hpa/resources	0.080s	coverage: 100.0% of statements
--- FAIL: TestGlobalResyncOnUpdateAutoscalerConfigMap (0.00s)
logger.go:130: 2021-03-13T01:25:20.733Z	PANIC	fake/fake_filtered_factory.go:47	Unable to fetch labelkey from context.
panic: Unable to fetch labelkey from context. [recovered]
panic: Unable to fetch labelkey from context.
```
=> add filter label selector for serving fake pod informer factory setup

injection/config.go
`RecommendedHomeFile` seems to be precisely what we're after, dealing with some windows shenanigans probably better than we do currently, so why not? :shrug: 
/assign @n3wscott @vagababov
=> Simplify loading of local kubeconfig in sharedmain

tracing/http_test.go
* Adds a benchmark to be used as a baseline for future changes or migrations. This is helpful especially because tracing happens in several places like activator, queue-proxy. Note that eventing uses [direct calls](https://github.com/knative/eventing/blob/8f35d42544e064783f344538d2957c753e31c820/pkg/broker/ingress/ingress_handler.go#L141-L152) to opencesus lib eg. `trace.StartSpan()` in its event handlers and sets span attributes explicitly in several occasions (this is lighter compared to the handler we benchmark here). I am wondering if we can do the same for Serving as trace.StartSpan() is run anyway as part of the HTTPSpanMiddleware (worth investigating next and use this benchmark to compare changes). Maybe create an optimized handler to be used with activator, queue-proxy? …
=> Add benchmarking for the http tracing handler

OWNERS, OWNERS_ALIASES, apis/OWNERS, apis/duck/OWNERS, codegen/OWNERS, configmap/OWNERS, controller/OWNERS, hack/OWNERS, hash/OWNERS, kflag/OWNERS, kmeta/OWNERS, logging/OWNERS, metrics/OWNERS, pool/OWNERS, reconciler/OWNERS, source/OWNERS, test/OWNERS, tracing/config/OWNERS, webhook/OWNERS, websocket/OWNERS
See https://github.com/knative/community/pull/552 for the addition of groups/full OWNERS_ALIASES that will be synced.
This is a preparatory PR for landing OWNERS_ALIASES automation across the Knative org (alternative to the CODEOWNERS changes in knative-sandbox).
If this seems to be expanding permissions or otherwise likely to cause a problem, `/hold` this PR and comment here or on https://github.com/knative/community/pull/552.
=> Update OWNERS_ALIASES to match autogen in community

network/domain.go, network/domain_test.go
- :gift: Resolve cluster domain with `CLUSTER_DOMAIN` as a fallback.
This will help with tests that are attempting to resolve cluster local urls from outside the cluster, that do not have access to `/etc/resolv.conf` directly. 
```release-note
network.GetServiceHostname and network.GetClusterDomainName now respect the env var CLUSTER_DOMAIN.
```
=> resolve cluster domain using env CLUSTER_DOMAIN as a fallback

test/kube_checks.go
* Report state in kube checks
Fixes #996
=> Improve state reporting in kube checks

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/apps/v1/deployment/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, client/injection/kube/reconciler/core/v1/secret/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go, reconciler/configstore.go, reconciler/deletion.go
Fixes #2021
ObserveFinalizeKind is not guaranteed to be called for every resource
that gets deleted, even if they do have a finalizer. The leader can race
the observers in removing the finalizer so the observers would not even
see the deletion.
Using the OnDelete handler on the informer is equally racy in that it
can trigger the deletion handler while a potential "normal" reconcile is
still in-flight.
This adds an ObserveDeletedKind handler that can be implemented by
reconcilers. The events still go via the workQueue, so proper order and
deduplication is guaranteed. Observation is guaranteed as well. In most
if not all cases, this handler should replace the ObserveFinalizeKind
handler.
Will for example be used in https://github.com/knative-sandbox/net-kourier/issues/448
=> Add possibility to implement a deletion handler in a reconciler.

metrics/exporter.go
TestMetricsExport creates a lot of failures on CI lately. Here is a case where [exporter never got updated](https://storage.googleapis.com/knative-prow/pr-logs/pull/knative_pkg/2082/pull-knative-pkg-unit-tests/1380101339379404800/build-log.txt). This means most likely that a previous test already had the backend set as expected but the port was different than the [one expected later on](https://github.com/knative/pkg/pull/2005#issuecomment-776174080).
I guess this happens only in tests and https://github.com/knative/pkg/issues/1672 is not fixed. 
This fix makes logic about prometheus reconfiguration correct for testing purposes.
=> Try fix TestMetricsExport 

reconciler/events.go, reconciler/events_test.go
- :gift: `reconciler.Event`s that wrap errors can be used with the [apimachinery errors package](https://pkg.go.dev/k8s.io/apimachinery/pkg/api/errors), which uses [errors.As](https://github.com/kubernetes/apimachinery/blob/v0.21.0/pkg/api/errors/errors.go#L649-L654) to compare error types.
https://github.com/knative/eventing/issues/5146 involves a bug where we are [trying](https://github.com/knative/eventing/blob/7775e372bdc033da163cfb01194785d11a4f7d93/pkg/reconciler/subscription/subscription.go#L120) to ignore `IsNotFound`-type errors in our finalizer, but right now Events can never be used with these apimachinery predicates.
```release-note
- reconciler.Events can be cast to their underlying error types
```
=> Allow errors.As to work with reconciler.Events

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/apps/v1/deployment/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go
As per title. We use semantic equality to determine if we want to update the status in the first place. Using `reflect.DeepEqual` here means, that we're going to update status even if only the timestamp has "changed". We want to explicitly exclude that (that's why we use `VolatileTime` in the first place) so this should spare us a few unnecessary API calls.
=> Use semantic equality for status update retries

apis/volatile_time.go
This fixes https://github.com/kubernetes-sigs/controller-tools/issues/533 and is part of the ongoing work to try to use `controller-tools` for our own schema gen.
/assign @julz @vagababov @n3wscott
=> Make VolatileTime compatible with controller-gen

resolver/addressable_resolver.go
Fixes #
As we noticed from test [here](https://github.com/knative/serving/pull/10587) that using the reconcilers context with timeout makes resolver fails (for DomainMapping) as the canceled context gets cached
=> Allow URIs to be resolved without reconciler context

leaderelection/chaosduck/main.go
It's been kinda annoying trying to come up with the exact list of webhooks to ignore and this has caused intermediate flakiness. This adds the possibility to exclude components via a regex, so all webhooks can be excluded more easily and scalably.
/assign @nak3 @dprotaso
=> Allow disable via regex in chaosduck

.golangci.yaml, apis/duck/v1beta1/destination.go, leaderelection/chaosduck/main.go
See https://groups.google.com/g/golang-nuts/c/rCP70Aq_tBc/m/8QHp6_cqBgAJ
as towards golint's deprecation. revive is supposed to be a drop-in
replacement.
/assign @julz
=> Replace golint with revive

client/injection/apiextensions/informers/factory/filtered/fake/fake_filtered_factory.go, client/injection/apiextensions/informers/factory/filtered/filtered_factory.go, client/injection/kube/informers/factory/filtered/fake/fake_filtered_factory.go, client/injection/kube/informers/factory/filtered/filtered_factory.go, codegen/cmd/injection-gen/generators/fake_filtered_factory.go, codegen/cmd/injection-gen/generators/filtered_factory.go
Per discussion in https://github.com/knative/pkg/issues/2116,  we decided to change the multiple label selectors in filtered informer and factories to a single one to avoid any future confusion and bugs.
=> update the multiple label selector implemention to avoid clobber  in filtered factory

test/README.md, test/ha/ha.go, test/kube_checks.go
This changes some function definitions to accept a `kuberenetes.Interface` instead of the struct `test.KubeClient`
=> replace KubeClient instances with kubernetes.Interface

webhook/certificates/resources/certs.go, webhook/certificates/resources/certs_test.go
ED25519 is not [currently compliant with FIPS regulations](https://www.federalregister.gov/documents/2019/10/31/2019-23742/request-for-comments-on-fips-186-5-and-sp-800-186), [ECDSA with SHA256 is though](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf).
This is kind of a minor security point anyway, seeing as these certificates are only used for Webhook-cert auto-creation. It's useful to have a regulatory compliant default though.
=> Auto-generate webhook certs with ECDSA for FIPS compliance

test/clients.go
=> drop kubeclient struct

webhook/configmaps/configmaps.go, webhook/configmaps/table_test.go, webhook/resourcesemantics/defaulting/defaulting.go, webhook/resourcesemantics/defaulting/table_test.go, webhook/resourcesemantics/validation/reconcile_config.go, webhook/resourcesemantics/validation/reconcile_config_test.go
- set webhooks ownerReferences to namespace 
/kind cleanup
Fixes #2044
```release-note
NONE
```
**Docs**
```docs
```
=> set webhooks ownerReferences to namespace

resolver/addressable_resolver.go, resolver/addressable_resolver_test.go
- :bug: Fix URIResolver to verify that k8s services exist before returning their URI
/kind bug
Fixes https://github.com/knative/eventing/pull/5442
```release-note
URIResolver will now error if resolving a k8s service that does not exist
```
=> Lookup k8s services to ensure they exist

apis/duck/v1/knative_reference.go, apis/duck/v1/knative_reference_resolve_group_test.go, apis/duck/v1/knative_reference_test.go, kref/knative_reference.go, kref/knative_reference_resolve_group_test.go
Add the `KReference.Group` field and `ResolveGroup` function. Part of the experimental feature https://github.com/knative/eventing/issues/5086
- :gift: Add KReference.Group field and ResolveGroup function
=> Add KReference.Group field and ResolveGroup function

version/version.go, version/version_test.go
This patch bumps min k8s version to 1.19
Doc fixes https://github.com/knative/docs/pull/3804.
Please also see https://github.com/knative/community/blob/main/mechanics/RELEASE-VERSIONING-PRINCIPLES.md#knative-serving-version-table
/cc @dprotaso
=> Bump k8s min k8s version to 1.19

leaderelection/config.go
Fixes: https://github.com/knative/pkg/issues/1478
=> drop deprecated enabledComponents field

injection/sharedmain/main.go, logging/warning_handler.go
Instead of writing to client-go's own `klog`, this writes API warnings (see https://kubernetes.io/blog/2020/09/03/warnings/) into the respective zap logger, so they'll be "proper" warnings in the log as well, which should make them easier to catch.
/assign @dprotaso @julz
=> Print proper warning logs from API warnings

test/spoof/spoof.go
Xip.io is no more and we use sslip.io now. Updated the references in serving in https://github.com/knative/serving/pull/11589, updating here to match.
=> Replace reference to obsolete xip.io service

test/spoof/error_checks.go, test/spoof/spoof.go
As seen in net-kourier nightlies like https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-sandbox-net-kourier-nightly-release/1412336305043410944.
Things started failing with no changes done whatsoever. Upon investigation, it turned out that the test runner's Linux version was bumped from 4.19 to 5.4. The working theory is, that the error handling in the TCP stack changes slightly so that errors that would've been reported as "connection refused" (which we already retry) are now reported as "no route to host", which we might want to retry as well.
=> Retry 'no route to host' errors by default

test/request.go, test/spoof/spoof.go, test/spoof/spoof_test.go, test/spoof_test.go
- New method `CheckEndpointState` just for checking an endpoint's response
/kind api-change
Part of knative/serving#1178
```release-note
No changes to the existing WaitForEndpointState method, these changes don't fix knative/serving#1178 but help change the way some assertions work in serving e2e tests
```
=> Add CheckEndpointState method to SpoofingClient

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go, client/injection/kube/reconciler/apps/v1/deployment/controller.go, client/injection/kube/reconciler/core/v1/namespace/controller.go, client/injection/kube/reconciler/core/v1/secret/controller.go, codegen/cmd/injection-gen/generators/reconciler_controller.go, controller/options.go, injection/README.md
Currently we enqueue every object with no way to filter, which causes problems for eventing's source controller which reconciles duck CRDs.
I decided that since I didn't have justification for the changes in #2176 that I would feel better not making them. If we come up with a reason we need to support filtering `GlobalResync` from the constructor rather than just by using `FilteredGlobalResync` we can revisit that later.
ref: knative/eventing#5543
=> Add ability to filter objects on injection controller promotion

test/e2e_flags.go
Removing default setting to KUBECONFIG in e2e flags. This allows e2e testing to be done from inside a Kubernetes Cluster. 
/kind bug 
/kind cleanup
Fixes #2190
closes #2190
=> Removing default for KUBECONFIG to enable incluster e2e tests

test/request.go
The array needed to be spread using the '...' operator
=> minor bug when passing spoof options

environment/client_config.go, test/clients.go
This mimics the behavior of tools like kubectl, should work for both in-cluster and out-of-cluster usages
- :bug: Fix defaulting to `~/.kube/config` without an explicitly set KUBECONFIG
/kind bug
=> Use default Kubeconfig loading rules

controller/controller.go, controller/controller_test.go
This is modeled after some of the semantics available in controller-runtime's `Result` type, which allows reconcilers to indicate a desire to reprocess a key either immediately or after a delay.
I worked around our lack of this when I reworked Tekton's timeout handling logic by exposing a "snooze" function to the Reconciler that wrapped `EnqueueAfter`, but this feels like a cleaner API for folks to use in general, and is consistent with our `NewPermanentError` and `NewSkipKey` functions in terms of influencing the queuing behaviors in our reconcilers via wrapped errors.
You can see some discussion of this here: https://knative.slack.com/archives/CA4DNJ9A4/p1627524921161100
```release-note
Introduce a way for Knative-style controllers to requeue keys by …
```
=> Add a new mechanism for requeuing a key.

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/apps/v1/deployment/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, client/injection/kube/reconciler/core/v1/secret/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go
In https://github.com/knative/pkg/pull/2201 I introduced a wrapped error to requeue keys, but genreconciler emits undesirable `InternalError` events for this and the `NewSkipKey` wrapped errors.  This squelches those.
/kind bug
N/A
**Docs**
N/A
=> Ignore special errors in codegen for events

webhook/admission_integration_test.go, webhook/conversion_integration_test.go, webhook/webhook.go, webhook/webhook_integration_test.go
/kind cleanup
The client field in the base webhook was only being used by test code, so I removed it and changed the tests to pull the client off of `ctx` themselves.
N/A
**Docs**
N/A
=> Drop Client as it is only used in tests

resolver/addressable_resolver.go, resolver/addressable_resolver_test.go
- removes the trailing slash for the resolution of URI from k8s service. Same change in the test file too.
/kind bug
Fixes # 
The URI resolved for lets say a channel or a knative service does not have the trailing slash. For example, below is the status of a pingsource with a channel as sinkRef:
```
status:
ceAttributes:
- source: /apis/v1/namespaces/serverless/pingsources/test-ping-source
type: dev.knative.sources.ping
conditions:
- lastTransitionTime: "2021-07-01T11:20:50Z"
status: "True"
type: Deployed
- lastTransitionTime: "2021-07-01T11:20:50Z"
status: "True"
type: Ready
- lastTransitionTime: "2021-07-01T11:20:50Z"
status: "True"
type: SinkProvided
observedGeneration: 1
sinkUri: http://my-channel-kn-channel.serverless.svc.cluster.local
```
Noticed this while working on a component …
=> K8s Service trailing-slash fix in URI resolver  

webhook/admission_integration_test.go, webhook/helper_test.go, webhook/webhook.go, webhook/webhook_integration_test.go
This reworks the way we setup the TLS Config for the webhook, so that when the `opts.SecretName` is omitted we serve over non-TLS.
N/A
**Docs**
N/A
=> Support the webhook serving over non-TLS.

codegen/cmd/injection-gen/generators/packages.go
I noticed doing some tinkering that these were running on every iteration, but the inputs don't change.  This sinks the calls to below the loop, and reduces things to a single call for each.
/kind cleanup
/assign @n3wscott 
```release-note
```
**Docs**
```docs
```
=> Sink two codegen passes below loop.

webhook/configmaps/configmaps.go, webhook/psbinding/psbinding.go, webhook/resourcesemantics/validation/validation_admit.go
- :broom: Drop unnecessary double-pointers in decoding logic.
- :broom: Replace `decoder.Decode` with `json.Unmarshal` where they are equivalent anyway. This also avoids unnecessary byte buffers.
/kind cleanup
```release-note
NONE
```
**Docs**
```docs
```
/assign @julz
=> Drop redundant pointers and decoders

apis/interfaces.go, controller/controller.go, metrics/exporter.go, test/ha/ha.go, tracing/testing/zipkin.go, tracing/zipkin.go, tracker/interface.go
Not the most important thing ever (to say the least), but the canonical prefix to use for `Deprecated:` warnings in godoc is title case (and should be in its own paragraph).
- :broom: make deprecation comments use consistent case.
/kind cleanup
=> Use consistent case for "Deprecated" comments

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/apps/v1/deployment/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, client/injection/kube/reconciler/core/v1/secret/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
We've determined `ReadOnlyFinalizer` to be unsafe a while ago and hence introduced the (supposed to be safe) alternative `OnDeletionInterface`. We should nudge people to use the latter and completely fade out the former.
Note: Neither knative nor sandbox nor Tekton is using ReadOnlyFinalizer anymore, so we might also think about "just" dropping it.
/kind deprecation
```release-note
Deprecate ReadOnlyFinalizer interface over OnDeletionInterface.
```
/assign @julz @n3wscott
=> Deprecate ReadOnlyFinalizer interface over OnDeletionInterface

resolver/addressable_resolver.go, resolver/addressable_resolver_test.go
I noticed in a few places downstream that reconcilers were creating both trackers and Addressable resolvers, which seems superfluous.  As part of examining the way we use the tracker, I'm experimenting with changing this to just take a tracker.
/kind cleanup
```release-note
resolver.NewURIResolver now takes a tracker.Interface instead of a callback.
```
**Docs**
```docs
```
=> Have the addressable resolver take a tracker.

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go, client/injection/kube/reconciler/apps/v1/deployment/controller.go, client/injection/kube/reconciler/apps/v1beta1/deployment/controller.go, client/injection/kube/reconciler/apps/v1beta2/deployment/controller.go, client/injection/kube/reconciler/core/v1/namespace/controller.go, client/injection/kube/reconciler/core/v1/secret/controller.go, client/injection/kube/reconciler/extensions/v1beta1/deployment/controller.go, codegen/cmd/injection-gen/generators/reconciler_controller.go, controller/controller.go, injection/README.md, webhook/certificates/controller.go, webhook/configmaps/controller.go, webhook/psbinding/README.md, webhook/psbinding/controller.go, webhook/resourcesemantics/conversion/controller.go, webhook/resourcesemantics/defaulting/controller.go, webhook/resourcesemantics/validation/controller.go
Our generated `NewImpl` methods have long taken `context.Context`, but despite many iterations the forms we expose from our `controller` package never have.  This change contains several elements:
1. Expose a new `NewContext` method that takes `context.Context` in addition to the current `NewImplFull` signature.
2. Call `NewContext` instead of the deprecated `NewImpl` from our generated controller code.
3. Call `NewContext` from all our webhook reconcilers.
4. Introduce a `tracker.Interface` on `controller.Impl` now that we can extract the tracker lease from `ctx` (for use with https://github.com/knative/eventing/pull/5651, and https://github.com/knative/pkg/pull/2220 downstream)
/kind cleanup
```release-note
Introduce controller.NewContext and deprecate …
```
=> Introduce `NewContext`, deprecate `NewImplFull`.

client/injection/kube/client/client_expansion.go
With this change, I was able to pass some downstream e2e tests that check for event emission with this path enabled, which previously failed.
The relevant hand-rolled bits in Kubernetes client-go is here: https://github.com/kubernetes/client-go/blob/35bf219cc60981cdf318b711e2630cc05e0a83e5/kubernetes/typed/core/v1/event_expansion.go#L49
I opted to avoid copy/pasting the generated code, and instead used a trick that let me call into the generated code.
Going through this exercise also (likely) uncovered a Kubernetes bug: https://github.com/kubernetes/kubernetes/issues/104495
/assign @n3wscott 
```release-note
```
**Docs**
```docs
```
=> This implements the EventExpansion needed to emit K8s events.

configmap/parse.go, configmap/parse_test.go
🎁 Trim the space in configmap/registriesSkippingTagResolving's url. Because many develpers do like "a.com, b.com", it's easy to have this mistake.
Related to https://github.com/knative/pkg/issues/2229
Related PR
=> Trim the space in configmap/registriesSkippingTagResolving's url.

version/version.go
The comment `Compare returns 1` remains since the first implementation.
https://github.com/knative/pkg/commit/80e5f98294faeb254bbc34697932e25f1e896ed6#diff-f6bf0ae0d21c9408c6624174da11dafb369ce306f2cdcea704285d8acc87e19eR49-R53
It is unclear as we no longer check `return 1`. This patch updates the comment.
/kind cleanup
=> Update version check comment

test/helpers/name.go, test/helpers/name_test.go
`ObjectNameForTest` is used to generate names for objects (like service) used in tests. It calls `kmeta.ChildName` which allows max name length is 63 (supported by k8s). However some non-k8s implementation has a smaller limit than k8s.
This PR proposes to limit the length of generated name to 50, which is sufficient in knative tests.
=> Add length limit for the generated names used in tests

controller/controller.go, controller/controller_test.go, resolver/addressable_resolver.go
/kind cleanup
```release-note
Drop deprecated addressable resolver constructor.
Drop deprecated controller.New* constructors.
```
**Docs**
```docs
```
=> Drop several deprecated APIs

controller/controller_test.go, leaderelection/context.go, leaderelection/context_test.go, reconciler/leader.go, reconciler/leader_test.go
tl;dr Without leader election enabled, we've been suffering from double resyncs, this fixes that.
Essentially when the informers are started, prior to starting the controllers, they fill the controller's workqueue with ~the world.  Once we start the controllers, the leader election code calls `Promote` on a `Bucket` so that it starts processing them as their leader, and then is requeues every key that falls into that `Bucket`.
When leader election is disabled, we use the `UniversalBucket`, which always owns everything.  This means that the first pass through the workqueue was already hitting every key, so re-enqueuing every key results in superfluous processing of those keys.
This change makes the `LeaderAwareFuncs` elide the call to `PromoteFunc` when the `enq` function passed is `nil`, …
=> Avoid double-resyncs without leader election.

test/spoof/spoof.go
Add back `DefaultErrorRetryChecker` into the `CheckEndpointState` calls so it retries for issues caused by the network.
Problem introduced in knative/serving/pull/11680
=> fix check calls being unreliable

test/spoof/spoof.go
This'll allow us to remove `RetryingRouteInconsistency` in Serving to push "patcheable" functionality deeper into the stack. Shaking the :evergreen_tree:  to see what this'd break.
=> Widen the error checker interface to allow response error checking

test/spoof/spoof.go
This patch changes `DefaultErrorRetryChecker` to `ErrorRetryChecker`
type before adding in the interface array.
Without it, the type of DefaultErrorRetryChecker is still `func(error) (bool, error)`.
https://play.golang.org/p/CLlGbwGQeMu
/cc @markusthoemmes
=> Declare `DefaultErrorRetryChecker` as `ErrorRetryChecker` type

test/spoof/spoof_test.go
To avoid mistakes like https://github.com/knative/pkg/pull/2276 in the future, this adds a set of tests that make sure the retries are actually done. The tests fail without https://github.com/knative/pkg/pull/2276.
/assign @nak3
=> Add tests for retriable errors to the spoof client

apis/duck/v1/podspec_defaults.go, apis/duck/v1/podspec_defaults_test.go, apis/duck/v1/podspec_types.go, apis/duck/v1/podspec_validation.go, apis/duck/v1/podspec_validation_test.go
Today you can't use `duckv1.WithPod` to author webhooks because it doesn't implement the `Validate` or `SetDefaults` methods, and that makes sense since they are (by definition) a generic encapsulation of a number of types.
However, if we could infuse `ctx` with appropriate callbacks for `Validate` and `SetDefaults` then folks can use our types, but infuse `ctx` with callbacks that perform the appropriate validation.
What I have in mind is something along these lines:
```go
return defaulting.NewAdmissionController(ctx,
// Name of the resource webhook.
"foo.bar.dev",
// The path on which to serve the webhook.
"/defaulting",
// The resources to default.
map[schema.GroupVersionKind]resourcesemantics.GenericCRD{
appsv1.SchemeGroupVersion.WithKind("Deployment"):  &duckv1.WithPod{}, …
```
=> Enable using `duckv1.WithPod` with our webhook infra.

.github/workflows/knative-downstream.yaml
additionally, we re-merge upstream in case new changes appear in HEAD
Fixes: https://github.com/knative/pkg/pull/2265
=> when testing downstream use the correct release branch

version/version.go, version/version_test.go
This patch adds IsNum to true when set `-0` to minimumVersion.Pre.
For example, the version (`1.20.0-1095+9689d22dc3121e-dirty`) is not compared correctly:
```
2021/09/16 01:33:33 Failed to get k8s version kubernetes version "1.20.0-1095+9689d22dc3121e-dirty" is not compatible, need at least "1.20.0-" (this can be overridden with the env var "KUBERNETES_MIN_VERSION")
```
/cc @markusthoemmes @dprotaso
=> Add IsNum to true when set `-0` to minimumVersion.Pre

test/migrate/checks.go
- Additional check that can be reused in post-upgrade tests
- Can be reused downstream to verify migration from one version to another
- Example usage in Knative Eventing is available at https://github.com/knative/eventing/pull/5705
We have recently run into an issue after migrating from Knative Eventing 0.22 to 0.23. The v1beta1 version of apiserversources.sources.knative.dev was completely removed and it was not possible to upgrade because sometimes in the past the "migrator" did not properly migrate these resources (between 0.19.2 and 0.20.0). Adding these checks will ensure that the migration happens. 
Fixes #
```release-note
```
**Docs**
```docs
```
=> Check Knative CustomResourceDefinitions stored version

tracker/enqueue.go, tracker/enqueue_test.go
Previously we required namespace to be non-empty, but it never is for Cluster-scoped resources.
This change elides validation for missing namespaces, assuming cluster-scoping.
```release-note
tracker now supports Cluster-scoped resources.
```
**Docs**
```docs
```
=> Allow tracking Cluster-scoped resources.

leaderelection/config.go, leaderelection/config_test.go
Part of https://github.com/knative/serving/issues/7300
Majority of serving uses lowercase-hyphens - ie. some-property over
someProperty
This changes the leader election config map parsing to support formats
and to prioritize the lowercase-hyphen case
=> introduce new case convention for leader election config map

.github/workflows/knative-downstream.yaml
As per title. Some of them have started failing because of a type mismatch caused by Golang 1.16 vs 1.17.
/assign @julz
=> Build downstream tests with go 1.17

test/request.go
This patch makes a tiny change to remove unclear comment for `makeSpoofClient()` arg.
The `timeout` arg is not bool but `time.Duration` so this comment is confusing.
/cc @shinigambit
=> Remove unclear comment for `makeSpoofClient()` arg

test/spoof/error_checks.go, test/spoof/spoof.go
This patch fixes the recent flake in `service_to_service_test.go` on Kind/Istio.
istio-ingressgateway returns 502 with no such host error when it fails to resolve the cluster domain.
/cc @markusthoemmes
=> Add retry checker for DNS failure from Ingress

codegen/cmd/injection-gen/generators/comment_parser.go, codegen/cmd/injection-gen/generators/comment_parser_test.go, codegen/cmd/injection-gen/generators/packages.go, codegen/cmd/injection-gen/generators/reconciler_controller.go, codegen/cmd/injection-gen/generators/reconciler_controller_stub.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go, reconciler/filter.go
- allow multiple values for comment tag keys
- add OR filter chain
- update codegen to support multiple annotation keys
Part of: https://github.com/knative/serving/issues/12103
=> codegen - support multiple annotation keys

metrics/config.go, metrics/config_test.go
This field of the metricsConfig isn't set anywhere (and isn't exported), so it's doing nothing. Might as well simplify the code a bit by removing it.
=> Remove unused recorder field

hash/bucketer.go, hash/hash_test.go
As per title. It's unnecessary to actually create a list of the set to then only return the first element. Since the element's order is random anyway, might as well use `PopAny` in this case.
/assign @julz
=> Drop unnecessary list creation from bucketer

test/monitoring/monitoring.go
Currently we fmt.Sprintf a command string only to immediately split it
back in to args, which causes gosec to complain about unsanitised inputs
to exec.Command. Refactoring this to directly pass an args array is
clearer, more secure, and avoids needing the nosec comment.
=> Tidy helper to avoid need for nosec comment

apis/duck/v1/source_types.go
It's better to have nil checks inside the Validate method of the
type itself instead of the type that holds a field of that type
because this allows using the types in other contexts without
the types that hold a field.
=> Add nil checks for Source types validation to be pointer receiver based

apis/duck/v1/source_types.go, apis/duck/v1/source_types_test.go
- The `Sink` in `SourceSpec` is required.
- Validate the `sink` field using `Destination.Validate(ctx)`
=> Validate Sink in SourceSpec

apis/duck/v1/source_types_test.go
As per title.
Replace:
```golang
URI: func() *apis.URL {
u, _ := apis.ParseURL("https://localhost")
return u
}(),
```
with:
```golang
URI: apis.HTTP("localhost"),
```
=> Simplify URI creation in source validation tests

leaderelection/config.go, leaderelection/doc.go
Fixes: #2383
Also adds documentation for the `leaderelection` package, because I went
looking and found it wasn't there.
Verified that these settings do not seem to interfere with chaos duck integration tests in serving: https://github.com/knative/serving/pull/12499
/assign @mattmoor @dprotaso
=> Adjust leaderelection defaults

testing/resource.go, webhook/resourcesemantics/defaulting/controller.go, webhook/resourcesemantics/defaulting/defaulting.go, webhook/resourcesemantics/defaulting/defaulting_test.go, webhook/resourcesemantics/defaulting/table_test.go, webhook/resourcesemantics/defaulting/user_info.go
Issue #1140
**Proposed Changes**
Allow Defaulting webhook to register generic Unstructured callbacks so that implementers can create generic defaulting logic outside of the APIs package.
This will later be used in Eventing Kafka Broker.
- Allow Unstructured callback from Defaulting Webhook
```release-note
Allow Unstructured callback from Defaulting Webhook
```
=> Allow Unstructured callback from Defaulting Webhook

resolver/addressable_resolver.go, resolver/addressable_resolver_test.go
Errors from the tracker or the addressable resolver factory
are discarded which isn't helpful for debugging since the
error is generic `kafkachannels "Lister" not found`.
- Don't discard addressable resolver original errors
/kind bug
Fixes #2394
=> Don't discard addressable resolver original errors

apiextensions/storageversion/migrator.go, apiextensions/storageversion/migrator_test.go
storage-version-migration-serving crashes if ksvc deleted during
migration.
Please refer to the following error especially
`services.serving.knative.dev \"receiver261\" not found` message.
```
{"severity":"INFO","timestamp":"2022-01-25T14:17:19.840090884Z","caller":"logging/config.go:116","message":"Successfully created the logger."}
{"severity":"INFO","timestamp":"2022-01-25T14:17:19.840350704Z","caller":"logging/config.go:117","message":"Logging level set to: info"}
{"severity":"INFO","timestamp":"2022-01-25T14:17:19.840399959Z","caller":"logging/config.go:79","message":"Fetch GitHub commit ID from kodata failed","error":"\"KO_DATA_PATH\" does not exist or is empty"}
{"severity":"INFO","timestamp":"2022-01-25T14:17:19.854296148Z","logger":"storage-migrator","caller":"migrate/main.go:60", …
```
=> Do not block NotFound error during patching resources

apis/url.go
- This PR adds kubebuilder marker so CRDs using URL could be
generated with controller-gen.
Same change on VolatileTime: https://github.com/knative/pkg/pull/2104
- Without this marker, any CRD that uses URL fails with error below when using controller-gen
```
controller-gen crd paths="./pkg/apis/sources/v1alpha1/" output:crd:artifacts:config=config/source
/Users/clyu/.gimme/versions/go1.17.darwin.amd64/src/net/url/url.go:359:2: encountered struct field "Scheme" without JSON tag in type "URL"
/Users/clyu/.gimme/versions/go1.17.darwin.amd64/src/net/url/url.go:360:2: encountered struct field "Opaque" without JSON tag in type "URL"
Error: not all generators ran successfully
...
```
- Original issue: [Define schema for rabbitmqsources.sources.knative.dev](https://github.com/knative-sandbox/even …
=> Make URL compatible with controller-gen

controller/controller.go, injection/sharedmain/main.go
Fixes: https://github.com/knative/pkg/issues/2436
=> Wait for reconciler/controllers to return prior to exiting the sharedmain process

webhook/webhook.go, webhook/webhook_test.go
This allows users to configure a faster restart of their
webhook if desired while retaining the current behavior.
- :gift: allow users to change the webhook drain timeout
```release-note
webhook.Options now contains a GracePeriod parameter to allow modifying the http server drain time from the default of 45 seconds.
```
=> allow overriding the default grace period of 45 seconds

configmap/parse.go, configmap/parse_test.go, leaderelection/config.go, leaderelection/context.go, leaderelection/context_test.go
Add a `map-lease-prefix` prefix for config keys for
`config-leader-election` that is a map from a generated lease prefix
to a new prefix:
```yaml
map-lease-prefix.<component>.<package>.<reconciler_type_name>: <new_prefix>
map-lease-prefix.<component-x>.<package-x>.<reconciler_type_name-x>: <new_prefix>
```
- Allow overriding lease name for a reconciler
Fixes #2411
```release-note
Allow overriding lease name for a reconciler using `lease-names-prefix-remapping` config key
```
=> Allow overriding lease name prefix for a reconciler

leaderelection/config.go, leaderelection/config_test.go
A `nil` `target` passed to `AsOptionalMap` causes a panic.
=> Initialize prefix remapping map to avoid panic

configmap/parse.go, configmap/parse_test.go, leaderelection/config.go, leaderelection/config_test.go
- Other `As*` functions take pointers.
- This avoids having to initialize the map passed to the function
=> Take pointer to map in AsOptionalMap for consistency

injection/clients/namespacedkube/informers/core/v1/configmap/configmap.go, injection/clients/namespacedkube/informers/core/v1/configmap/fake/fake.go
- :gift: Add configmap informer factory
https://github.com/knative/pkg/pull/2210 introduced a new  manually crafted namespacedkube implementation for secrets. This PR adds a similar factory for configmap.
This change has no user-visible impact.
**Docs**
This change has no user-visible impact.
=> Add dynamic configmap informer factory 

.codecov.yaml
Fixes #2457. Looking at the report [here](https://app.codecov.io/gh/knative/pkg/) a few folders have low coverage leading to a low coverage overall. This PR [ignores them](https://docs.codecov.com/docs/ignoring-paths) so that CI run against PRs dont fail, however coverage should pass the threshold for the ones that are not generated code eg. tracing, injection.
=> Fix coverage settings

network/h2c.go, network/transports.go, network/transports_test.go
Part of: https://github.com/knative/serving/issues/12503
PoC: https://github.com/knative/serving/pull/12815
This patch `NewProxyAutoTLSTransport` which is `NewProxyAutoTransport + TLS config.
Current proxy does not support TLS but it needs for https://github.com/knative/serving/issues/12503.
`DialTLSWithBackOff` is also `DialWithBackOff` + TLS config. It needs
`newH2Transport` which handles HTTP2 with TLS.
/cc @evankanderson @skonto @rhuss
=> Add `NewProxyAutoTLSTransport` and `DialTLSWithBackOff` to support TLS proxy

network/transports.go, network/transports_test.go
- :bug: `TestDialWithBackoff` work without special environment
/kind bug
Fixes #2401
=> :bug: `TestDialWithBackoff` work without special environment

apis/deprecated.go, apis/field_error.go, apis/field_error_test.go, testing/inner_default_resource.go, webhook/resourcesemantics/validation/validation_admit.go, webhook/resourcesemantics/validation/validation_deprecated_test.go, webhook/testing/testing.go
- :gift: Add new feature
This extends `apis.FieldError` to support designating certain FieldErrors as "warnings" (or explicitly as "errors", however, this is the default for back-compat).
You can turn an `apis.FieldError` into a warning using: `fe.At(apis.WarningLevel)` or force it into an error using: `fe.At(apis.ErrorLevel)`.
You can get the errors at a particular diagnostic level using: `fe.Filter(apis.WarningLevel)`.
This change also hooks this into the admission webhook infrastructure to support surfacing the "warning" level `apis.FieldError`s via the `Warnings` section of the `AdmissionResponse`.
Fixes: #2497
```release-note
Knative admission webhooks can now surface warnings (e.g. deprecations, "warn mode" policies).
```
**Docs**
```docs
```
/hold …
=> Add support for admission webhook warnings.

network/transports.go, network/transports_test.go
Fixes: #2502
This adds extra logging so we can determine if a dial timeout like in #2502 was
hitting the expected port.
/assign @cardil
/cc @dprotaso
=> Fix timeout test on darwin and log dial destination on timeout.

apis/field_error.go
See discussion in: https://github.com/knative/pkg/pull/2498
This allows for a slightly cleaner backwards-compatible implementation 🎉 
This drops the `Matches` method, since we can now simply use `==`.
- :broom: Update or clean up current behavior
/kind cleanup
/assign @evankanderson 
```release-note
```
**Docs**
```docs
```
=> Switch to iota/fmt.Stringer-based diagnostic levels.

logging/config.go, metrics/metrics_worker.go, metrics/prometheus_exporter.go
- :broom: Log metrics/logging init messages at `debug` level instead of `info`
After analyzing the logs emitted by our Knative Services, we realized that 90% of them were these 5 log entries related to the initialization of the metrics exporter and logger, over and over again.
I believe that silence is golden for this kind of setup operations, especially when the logger and metrics exporter aren't part of the business logic of the application that's running inside those services.
Regular scaling of these applications (including to 0) makes this "issue" even more visible.
```release-note
Initialization messages related to loggers and metric exporters are now logged at the `debug` level
```
**Docs**
```docs
```
=> Log metrics/logging init messages at debug level

webhook/admission.go
This can get big, and can contain mildly sensitive data that some users don't want showing up in logs.
If we keep this, than we should perhaps restrict what we tag to one of the less unbounded fields (e.g. don't include `Extra`)
/kind cleanup
```release-note
webhook no longer logs full UserInfo, just the Username field
```
**Docs**
```docs
```
cc @dprotaso @n3wscott
=> Drop `UserInfo` from logger tagging in webhook.

changeset/commit.go, changeset/commit_test.go, logging/config.go, test/mako/sidecar.go
We simply return 'unknown' if we can't read the build info. We already return 'unknown' if the vcs.revision key is missing from the build settings
Discussion: https://github.com/knative/pkg/pull/2548#discussion_r923510432
/assign @imjasonh
=> Drop error from changeset.Get signature

test/presubmit-tests.sh
Addresses https://github.com/knative/hack/issues/200
/kind cleanup
=> 🧹 remove defunct markdown linting variable

tracing/http_test.go, tracing/opencensus.go, tracing/opencensus_test.go, tracing/setup.go, tracing/zipkin_test.go
…acer
* The caller can then call Shutdown() to properly flush buffered Spans
before shutdown
This is incompatible change that will require updates in many repositories. I can either prepare those PRs so that they can be merged when this change propagates to those repositories or I can keep the old implementation and also provide a new impl that returns the OpenCensusTracer. Whatever works best.
Initially, I will provide an example PR for knative/eventing that will show the required updates.
Fixes #2475
```release-note
```
**Docs**
```docs
```
=> SetupStaticPublishing and SetupDynamicPublishing returns Tracer with Shutdown function

network/handlers/drain.go, network/handlers/drain_test.go
Replaces https://github.com/knative/pkg/pull/2491
We need a reset so that downstream for serving to work around containers that are failing their liveness probe see: https://github.com/knative/serving/issues/12571
=> allow drainer to be reset

test/kube_checks.go
`Endpoints` are created asynchronously so it might not exists as soon
as a sertvice is created.
We're occasionally getting:
```
did not reach the desired number of endpoints, got: 0: endpoints "trans-pod" not found
```
=> WaitForServiceEndpoints doesn't take into account not found endpoints

webhook/admission.go, webhook/admission_integration_test.go
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>
🐛 Fix #2581 
If warnings contain newlines, split on them, and create a new warning for each of them.
/kind <kind>
Fixes #
```release-note
* Fixes a bug (#2581) where (most if not all) warnings were silently ignored by k8s apiserver due to having newlines on them.
```
**Docs**
```docs
```
=> split warnings. Fix issue: 2581

webhook/resourcesemantics/interface.go, webhook/resourcesemantics/validation/controller.go, webhook/resourcesemantics/validation/reconcile_config.go, webhook/resourcesemantics/validation/validation_admit.go, webhook/resourcesemantics/validation/validation_admit_test.go
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>
Currently when we create the validatingwebhookconfiguration, there's couple of wonky things with it:
1. Always includes status as a subresource and there are cases where we do not need it (#2115 )
2. Always includes all the verbs in the configuration even though they will later on get filtered, but the call to webhook is still made.
Also the API is widely used so I wanted to investigate what could be a smallest change using what we currently have to make this configurable.
So, the idea is that we have a way to customize additional validation logic via `Callbacks`, so if we utilize that struct we do not have to change the signature, but can piggyback off of it to provide ways to customize the actual webhook configuration without breaking …
=> Fix #2115, allow selective verbs / subresources for webhooks.

.github/workflows/knative-boilerplate.yaml
Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
Uses go v1.18 in the boilerplate action (same as the others)
=> Updates boilerplate action to use go v1.18

injection/sharedmain/main.go
The Knative controller infrastructure uses by default two threads per controller. This setting is not configurable in Knative itself while [Tekton allows to configure it](https://github.com/tektoncd/pipeline/blob/v0.38.2/cmd/controller/main.go#L46). [I was playing around with that setting in Knative](https://knative.slack.com/archives/C0186KU7STW/p1659968402805789) and saw massively better numbers to bring Knative up when it reconciles everything in the system.
- :gift: introduce `threads-per-controller` flag to configure the number of go routines per controller
```release-note
You can now provide a `threads-per-controller` command line flag to configure the number of go routines per thread, the default is 2
```
**Docs**
Please let me know if this needs …
=> Allow configuration of threads-per-controller

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/admissionregistration/v1/mutatingwebhookconfiguration/reconciler.go, client/injection/kube/reconciler/admissionregistration/v1/validatingwebhookconfiguration/reconciler.go, client/injection/kube/reconciler/admissionregistration/v1beta1/mutatingwebhookconfiguration/reconciler.go, client/injection/kube/reconciler/admissionregistration/v1beta1/validatingwebhookconfiguration/reconciler.go, client/injection/kube/reconciler/apps/v1/deployment/reconciler.go, client/injection/kube/reconciler/apps/v1beta1/deployment/reconciler.go, client/injection/kube/reconciler/apps/v1beta2/deployment/reconciler.go, client/injection/kube/reconciler/batch/v1/cronjob/reconciler.go, client/injection/kube/reconciler/batch/v1beta1/cronjob/reconciler.go, client/injection/kube/reconciler/core/v1/configmap/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, client/injection/kube/reconciler/core/v1/node/reconciler.go, client/injection/kube/reconciler/core/v1/pod/reconciler.go, client/injection/kube/reconciler/core/v1/secret/reconciler.go, client/injection/kube/reconciler/extensions/v1beta1/deployment/reconciler.go, client/injection/kube/reconciler/extensions/v1beta1/networkpolicy/reconciler.go, client/injection/kube/reconciler/networking/v1/networkpolicy/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go
I noticed that the finalizer manipulation code was performing a second fetch of the resource from the lister cache to determine the differences in finalizers when the finalizers are being modify immediately above each callsite.
This changes both call sites to simply pass through the "desired finalizers" as a new parameter (instead of assigning them), which lets us use the unmodified resource and avoid the redundant lister cache fetch.
- :broom: Update or clean up current behavior
/kind cleanup
```release-note
Eliminate a redundant lister cache fetch in the knative reconciler codegen.
```
**Docs**
```docs
```
cc @vaikas @dprotaso @tcnghia
=> Avoid second lister fetch during finalizer reconciliation.

reconciler/reconcile_common.go
Serving currently uses a fixed constant for the context timeout on reconciliation, which is causing some bad interactions with certain policy webhooks.
Based on feedback on https://github.com/knative/serving/pull/13323 I am hoisting this into a shared variable, so that folks can turn it into a flag, so it is configurable.
```release-note
```
```docs
```
=> Define a global for `reconciler.DefaultTimeout`.

webhook/helper.go, webhook/resourcesemantics/validation/reconcile_config_test.go
I have a webhook with this definition and the reconciler is removing the `namespaceSelector.matchLabels` field:
Current resource:
```
namespaceSelector:
matchExpressions:
- key: webhooks.knative.dev/exclude
operator: DoesNotExist
objectSelector:
matchLabels:
app.kubernetes.io/component: kafka-dispatcher
```
Applied resource:
```
namespaceSelector:
matchExpressions: [ ]
matchLabels:
app.kubernetes.io/name: knative-eventing
objectSelector:
matchLabels:
app.kubernetes.io/component: kafka-dispatcher
```
- Preserve webhook namespaceSelector.matchLabels
/kind bug
```release-note
Preserve webhook namespaceSelector.matchLabels
```
=> Preserve webhook namespaceSelector.matchLabels

metrics/config.go, metrics/config_test.go
Related to https://github.com/knative/pkg/pull/2614
We currently panic when `METRICS_DOMAIN` isn't set but this setting is only needed when using OpenCensus
=> make METRICS_DOMAIN optional when backend is not OpenCensus

injection/sharedmain/main_test.go, metrics/config_observability.go
- Defaults the observability config. Currently with [this change](https://github.com/knative/pkg/pull/2610), there is an implicit requirement that `METRICS_DOMAIN` is set which is unexpected for users that have not enabled observability before.
- 🐛 Fixes crashing introduced in #2610 
The current build of `knative/pkg` will crash on startup because of [this line](https://github.com/knative/pkg/blob/main/injection/sharedmain/main.go#L118). Rather than introduce a nil-check, we should simply have observability disabled by default (as was the previous behavior) but now accessible from `context.Context`
```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x15c5568]
goroutine 1 [running]: …
```
=> Default ConfigMap if ObservabilityConfig is nil

webhook/resourcesemantics/validation/validation_admit.go
:broom: Previously we lacked a public method for turning our `apis.FieldError` multi-error into a list of constituent error messages, so when we turned things into a webhook warning we simply used the combined serialization of all of the warnings.  Thanks to Nghia's recent change, we can now access the list of warnings to return as a list of errors.
This also has the nice property that we lower the risk of potential message truncation due to the assorted limits imposed by both upstream and the warning-header medium that's used to send these to clients.
/cc @vaikas @tcnghia @evankanderson 
/kind cleanup
```release-note
Multiple apis.FieldError style "warnings" will now be returned as separate warnings from resource validation webhooks.
```
**Docs**
```docs
```
=> Cleanup: Turn multiple warnings into multiple warnings.

reconciler/testing/reactions.go
See https://github.com/knative/serving/pull/13399#issuecomment-1280033374
When we added warning-level `api.FieldErrors`, we missed filtering the warnings from `ValidateCreates` and `ValidateUpdates`.
For https://github.com/knative/serving/pull/13399, we want to be able to issue warnings on insecure default values for containers, but we don't want to force all our existing tests to use secure default values (and we want to validate that the insecure values will still work for controllers, etc).
=> Filter reactor FieldErrors on validation to only error-level alerts.

client/injection/kube/client/client.go, codegen/cmd/injection-gen/generators/client.go
:gift: Now that the K8s client libraries have an Apply method for the dynamic client, plumb it through the client code generation.
/kind feature
cc @k4leung4 @tcnghia 
```release-note
Dynamic client-based codegen now support Apply[Status] 🎉 
```
**Docs**
```docs
```
=> Feature: Implement `Apply` codegen.

reconciler/testing/table.go
This allows us to pass options to ignore unexpected fields in structs 
/assign @AngeloDanducci @nak3 
/cc @a7i
=> CmpOpts overrides should be passed through

webhook/resourcesemantics/validation/validation_admit.go
:bug: My previous change has revive/stylecheck warnings because I made the `warn` return value `[]error` and it wants the `error` last, which is kind of silly.
This mutes the linter on this signature, since it hits both revive and stylecheck
/kind bug
/assign @dprotaso 
```release-note
```
```docs
```
=> Fix: Mute the linter on error return values.

changeset/commit.go, changeset/commit_test.go
The main reason for this is to support cases where the `go build` happens on a non git folder but we want to pass a revision anyway.
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
/cc @imjasonh @dprotaso 
```release-note
NONE
```
=> changeset: allow override the revision through ldflags

apis/duck/v1/destination.go, apis/duck/v1/destination_test.go
To use `SetDefaults` on the `Destination` type, the caller must check that the destination is not nil currently:
e.g.
```
if subscriber != nil {
subscriber.SetDefaults(ctx)
}
```
Some other `SetDefaults` implementations, check this internally to prevent panics. E.g.: https://github.com/knative/eventing/blob/7e899fd166deb40c885d3fc4fb9e2901375a7bff/pkg/apis/duck/v1/delivery_defaults.go#L22-L24
This makes it easier to directly call `SetDefaults` without surrounding it with `nil` checks.
This PR addresses it and includes the "nil check" into the `SetDefaults` methods of a `Destination`
=> Make SetDefaults of Destination duck type nil safer

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/apps/v1/deployment/reconciler.go, client/injection/kube/reconciler/apps/v1beta1/deployment/reconciler.go, client/injection/kube/reconciler/apps/v1beta2/deployment/reconciler.go, client/injection/kube/reconciler/batch/v1/cronjob/reconciler.go, client/injection/kube/reconciler/batch/v1beta1/cronjob/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, client/injection/kube/reconciler/core/v1/node/reconciler.go, client/injection/kube/reconciler/core/v1/pod/reconciler.go, client/injection/kube/reconciler/extensions/v1beta1/deployment/reconciler.go, client/injection/kube/reconciler/extensions/v1beta1/networkpolicy/reconciler.go, client/injection/kube/reconciler/networking/v1/networkpolicy/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go
The state comparison using `kmp.SafeDiff(existing.Status, desired.Status)` in the `reconcilerImpl.updateStatus` method is costly and performed for debug logging purposes.
-  :bug: improve reconciler `updateStatus` performance by eliminating the existing and desired state calculation in none debug mode
/kind performance
Fixes https://github.com/knative/pkg/issues/2677
=> fix: `reconcilerImpl.updateStatus` calculates state difference in debug mode only

client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go, client/injection/kube/reconciler/admissionregistration/v1/mutatingwebhookconfiguration/controller.go, client/injection/kube/reconciler/admissionregistration/v1/validatingwebhookconfiguration/controller.go, client/injection/kube/reconciler/admissionregistration/v1beta1/mutatingwebhookconfiguration/controller.go, client/injection/kube/reconciler/admissionregistration/v1beta1/validatingwebhookconfiguration/controller.go, client/injection/kube/reconciler/apps/v1/deployment/controller.go, client/injection/kube/reconciler/apps/v1beta1/deployment/controller.go, client/injection/kube/reconciler/apps/v1beta2/deployment/controller.go, client/injection/kube/reconciler/batch/v1/cronjob/controller.go, client/injection/kube/reconciler/batch/v1beta1/cronjob/controller.go, client/injection/kube/reconciler/core/v1/configmap/controller.go, client/injection/kube/reconciler/core/v1/namespace/controller.go, client/injection/kube/reconciler/core/v1/node/controller.go, client/injection/kube/reconciler/core/v1/pod/controller.go, client/injection/kube/reconciler/core/v1/secret/controller.go, client/injection/kube/reconciler/extensions/v1beta1/deployment/controller.go, client/injection/kube/reconciler/extensions/v1beta1/networkpolicy/controller.go, client/injection/kube/reconciler/networking/v1/networkpolicy/controller.go, codegen/cmd/injection-gen/generators/reconciler_controller.go, controller/options.go
The current approach doesn't allow controllers to hook 
additional logic when a reconciler is promoted for buckets,
only when it is demoted with `DemoteFunc` passed through
the `controller.OptionsFn` function.
In eventing, we have components running in the background
(aka detached to resource created/update/delete),
which should only take action when a given reconciler
is the leader ([the autoscaler](https://github.com/knative/eventing/blob/main/pkg/scheduler/statefulset/autoscaler.go)).
Fixes #2675 
```release-note
Allow reconcilers to listen to leader promotion events 
```
=> Allow reconcilers to listen to leader promotion events 

webhook/env.go, webhook/env_test.go
- Add certificates k8s secret name read from environment variables
- I want to change secret name when I use knative operator. 
```release-note
```
**Docs**
```docs
```
=> Add certs secret name read from env

.github/workflows/knative-downstream.yaml
Fixes the operator downstream test which had their go version bumped to go1.19
=> bump golang version in downstream tests

webhook/env.go
Tiny fix to parameterize `WEBHOOK_NAME` env in an error message correctly.
=> Parameterize `WEBHOOK_NAME` env key in error message

.github/workflows/knative-downstream.yaml
It's not being maintained so it's always failing
/assign @pierDipi
=> drop eventing natss from downstream tests

injection/health_check.go
---
name: Bug Fix
about: Fixes a bug in knative/pkg
title: 'print log message with the proper type'
labels: kind/bug
assignees: ''
---
Fixes:
This will show up like this in the log
13:35:17 Probes server listening on port %!s(int=8080)
with proper type casted it will look a bit better !
Signed-off-by: Chmouel Boudjnah <chmouel@chmouel.com>
=> Printf log message with the right type when showing port

metrics/opencensus_exporter.go, network/transports_test.go, webhook/env.go, webhook/env_test.go, webhook/webhook.go, webhook/webhook_test.go
- :gift: make TLS minimum version configurable via environment variables for webhooks
- changes the TLS minimum version to 1.3
TLS 1.3 comes with numerous enhancements, such as a quicker TLS handshake and more secure cipher suites, which make it simpler to use. Additionally, the introduction of Zero Round-Trip Time (0-RTT) key exchanges further simplifies the TLS handshake. 
```release-note
- Added an additional option when creating a webhook, which allows to configure the minimum TLS version acceptable to communicate with the API server.
- The default TLS version was also changed from TLS 1.2 to TLS 1.3.
```
**Docs**
N/A
=> Make minimum TLS version configurable for webhooks

injection/clients/namespacedkube/informers/core/v1/configmap/configmap.go, injection/clients/namespacedkube/informers/core/v1/secret/secret.go
Follow up of https://github.com/knative/pkg/pull/2742
I didn't realize these were manual created - so deleting the code manually.
Part of https://github.com/knative/pkg/issues/2739
=> drop dynamic client wrappers in namespaced informers

webhook/admission_integration_test.go, webhook/conversion_integration_test.go, webhook/helper_test.go, webhook/webhook.go, webhook/webhook_integration_test.go, webhook/webhook_test.go
Contributing to the webhook package is a bit annoying
- Some tests couldn't be run in parallel
- Verbose log messages about tls handshake EOF
- Races occur with ephemeral ports since we temporary allocate them to discover which ones are free but then release them in order for the webhook to bind to them
=> Fix some webhook testing tech debt

.github/dependabot.yml, .github/workflows/knative-dependabot.yaml
As per title, this is same with https://github.com/knative-sandbox/net-gateway-api/pull/498.
Fix https://github.com/knative/pkg/issues/2759
=> Add dependabot and auto update deps

apis/duck/cached_test.go, controller/controller_test.go, go.mod, metrics/metrics.go, profiling/server.go, reconciler/testing/context.go, reconciler/testing/hooks.go, test/spoof/spoof_test.go, test/zipkin/util.go
Since Go 1.19, new type for sync/atomic was introduced like Int32 and Bool so it is possible to replace `go.uber.org/atomic`.
This patch makes the change.
```release-note
NONE
```
=> Use go sync/atomic instead of go.uber.org/atomic

apis/duck/v1/source_types.go, apis/duck/v1/zz_generated.deepcopy.go
Add `SinkAudience` to `SourceStatus` so that we store the Audience of the resolved sink's destination.
=> Add `SinkAudience` to `SourceStatus`

reconciler/testing/context.go
When we use `testing.SetupFakeContext`, we create a rest.Config, but don't add this to the context. Some reconcilers might need this config in the context.
This PR adds the rest.Config to the context (as it is created anyhow).
- :broom: Add rest.Config to fake context from `SetupFaceContextWithCancel`
=> Add rest.Config to fake context

environment/client_config.go, environment/client_config_test.go
- Fix potential redefined error with kubeconfig flag
The `--kubeconfing` flag is a popular one. I've run into a case with `sigs.k8s.io/controller-runtime` & `/pkg` when vendoring together there's `flag redefined` error thrown. Depending on the order of package inits.
This change should make `/pkg` safer to use alongside other K8s libs.
=> Fix potential `--kubeconfig` redefined error

go.mod, go.sum, vendor/golang.org/x/net/http2/server.go, vendor/modules.txt
- Update x/net to fix cve-2023-44487
-
-
/kind <kind>
```release-note
Fix cve-2023-44487
```
=> Updated x/net to v0.17.0 to fix cve-2023-44487

test/upgrade/shell/executor.go
This is a follow-up on https://github.com/knative/serving/pull/14495#discussion_r1357018523
- Prints each line separately so that the output is nicely formatted:
```
{Failed  === RUN   TestServingUpgrades/Run/Steps/UpgradeWith/ServingHead
executor.go:189: Oct 16 07:12:49.696 install_head_reuse_ingress [OUT] =============================================================
executor.go:189: Oct 16 07:12:49.696 install_head_reuse_ingress [OUT] ==== INSTALLING KNATIVE HEAD RELEASE AND REUSING INGRESS ====
executor.go:189: Oct 16 07:12:49.696 install_head_reuse_ingress [OUT] =============================================================
executor.go:189: Oct 16 07:12:49.698 install_head_reuse_ingress [OUT] ==== 2023-10-16 07:12:49.697870734+00:00
executor.go:189: Oct 16 07:12:49.698 …
```
=> Print each line separately in shell executor

apiextensions/storageversion/migrator.go, apiextensions/storageversion/migrator_test.go
- :bug: Fixed an issue where the [storage version migrator ](https://github.com/knative/pkg/blob/efe9f4a7b3f33a9db1a355b5375136b3a8c0fb1d/apiextensions/storageversion/migrator.go#L57)was running on CRDs that only had one storage version (related [comment](https://github.com/knative/serving/issues/14029#issuecomment-1741550974) for context).
Fixes #2845
=> Don't migrate storage version if CRD has one storage version

webhook/webhook.go
- Disables http2 by default for webhooks. Allows to set it on demand via options.
- Similar to https://github.com/prometheus-operator/prometheus-operator/pull/6028.
Fixes # CVE-2023-44487 (partially)
```release-note
Due to CVE-2023-44487 webhooks will use http1 by default, until the issue is fixed properly.
```
=> [CVE-2023-44487] Disable http2 for webhooks

webhook/webhook.go
- Similar to #2871  
```release-note
Due to CVE-2023-44487 webhooks will use http1 by default, until the issue is fixed properly.
```
=> [release-1.10] Allow to disable http2 for the webhook

client/injection/apiextensions/informers/factory/filtered/fake/fake_filtered_factory.go, client/injection/apiextensions/informers/factory/filtered/filtered_factory.go, client/injection/kube/informers/factory/filtered/fake/fake_filtered_factory.go, client/injection/kube/informers/factory/filtered/filtered_factory.go, codegen/cmd/injection-gen/generators/fake_filtered_factory.go, codegen/cmd/injection-gen/generators/filtered_factory.go
- Copy the value of `selector` in `withInformerFactory` within the for loop to avoid issues in func()
/kind bug
Fixes #2883
/hold verifying this in Serving
=> fix closure variable in filtered factory

go.mod, go.sum, vendor/modules.txt
As per title to fix current update-deps issues with knative.dev/hack (https://cloud-native.slack.com/archives/C04LY4Y3EHF/p1706520424682969)
/cc @ReToCode
=> Update knative.dev/hack to latest main

go.mod
I missed that we bumped some non-dependency properties in the go.mod file in https://github.com/knative/pkg/pull/2964
We shouldn't need to specify the `toolchain` directive - this oddly this breaks our go-licenses tool.
Bumping go version to v1.21 should be fine
see failure: https://github.com/knative-extensions/net-http01/pull/593
/assign @izabelacg @ReToCode @skonto
=> drop toolchain directive

.github/workflows/knative-downstream.yaml
This is deprecated - ﻿https://github.com/knative/serving/issues/14640
=> drop http01 from downstream testing

codegen/cmd/injection-gen/args/args.go, codegen/cmd/injection-gen/generators/informer.go, codegen/cmd/injection-gen/generators/packages.go, codegen/cmd/injection-gen/main.go
- Allows to kip the generation of the init func for an informer
- Based on the suggestion here https://github.com/knative/pkg/pull/2976#issuecomment-1994401541
- Replacement for https://github.com/knative/pkg/pull/2976
- Tested locally and here: https://github.com/knative/serving/pull/14955.
- It can be used as follows:
```
Knative Injection (for cert-manager)
${KNATIVE_CODEGEN_PKG}/hack/generate-knative.sh "injection" \
knative.dev/serving/pkg/net-certmanager/client/certmanager github.com/cert-manager/cert-manager/pkg/apis \
"certmanager:v1 acme:v1" \
--skipInitFuncForInformer \
--go-header-file ${REPO_ROOT_DIR}/hack/boilerplate/boilerplate.go.txt
```
and then on demand register the right informer:
```
if shouldEnableNetCertManagerController(ctx, client) { …
```
=> Optionally generate an init func for an informer

injection/sharedmain/main.go, webhook/stats_reporter.go, webhook/stats_reporter_test.go, webhook/webhook.go
To add some context, historically, `resource_name` was removed from this tag list due to its high potential of causing high metrics cardinality. See [knative/pkg#1464][1] for more information.
While that's great, but it might not be sufficient for large scale use cases where namespaces can be super dynamic (with generateName, too) or grows fase enough. There is an issue report from
[tektoncd/pipeline#3171][2] which talks about this.
This proposal makes it possible to disable `resource_namespace` tag via an option function. The default behavior is not changed, so no user impact if any of existing users rely on this tag. There is no API contract change either due to the beauty of variadic functions.
Now downstream projects can consume this by override `StatsReporter` in webhook context …
=> webhook: add options to disable resource_namespace tag in metrics

controller/two_lane_queue_test.go, injection/sharedmain/main.go, metrics/e2e_test.go, metrics/resource_view_test.go, reconciler/testing/context.go, test/cleanup_test.go, test/ha/ha.go, test/kube_checks.go, test/logstream/v2/stream_test.go, test/spoof/spoof.go, webhook/certificates/certificates_test.go, webhook/configmaps/table_test.go, webhook/helper_test.go, webhook/psbinding/table_test.go, webhook/resourcesemantics/defaulting/table_test.go, webhook/resourcesemantics/validation/reconcile_config_test.go, webhook/resourcesemantics/validation/validation_admit_test.go, websocket/connection_test.go
- Replace usages of deprecated wait.PollImmediate with wait.PollUntilContextTimeout
/kind <kind>
Fixes #
```release-note
NONE
```
**Docs**
```docs
```
=> Replace all usages of deprecated wait.PollImmediate with wait.PollUntilContextTimeout

.github/workflows/knative-downstream.yaml
This reverts commit bea88256cb23aa54c5ead0e4c25a831557f745c1.
Part of https://github.com/knative/eventing/issues/7670
/assign @ikavgo 
/assign @mkuratczyk 
/assign @Zerpet 
This ensures when people make changes to the shared library here we'll know if it breaks rabbitmq downstream
=> Revert "drop eventing-rabbitmq downstream testing (#2969)"

apis/duck/v1/auth_types.go, apis/duck/v1/zz_generated.deepcopy.go
Some components can have multiple identities for sending events (e.g. the Parallel). Therefor the AuthStatus should support exposing multiple IDs.
=> Update AuthStatus to have list of ServiceAccountNames

reconciler/configstore.go
In some repositories, we used multiple ConfigStores to store feature flags, for example, in eventing kafka broker, we use the Eventing core feature flags store and the EKB feature flags store
- Add composite ConfigStore to combine multiple `ConfigStore`
=> Add composite ConfigStore to combine multiple `ConfigStore`

network/network.go, network/network_test.go
- Deprecates k-kubelet-probe header
Part of https://github.com/knative/serving/issues/14981
=> drop special logic when handling kubelet probe header for istio mTLS

.github/workflows/knative-downstream.yaml, go.sum
:bug: Fix bug of release branch cut:
Added following additional steps to downstream.yaml for the scenario if the checkout fails - it should fallback and checkout the main branch downstream
- **Set Branch to Main if Checkout Fails:** Sets the BRANCH environment variable to main if the downstream checkout fails.
- **Set Branch to PR Base Ref if Checkout Succeeds:** Sets the BRANCH environment variable to the PR base branch if the checkout succeeds.
- **Checkout Downstream with Fallback Branch:** Uses the fall back branch main if the checkout failed or the PR base branch if it succeeded.
cc: @dprotaso 
- Fixes #2508
=> fix: downstream tests assume release branch was cut

.github/workflows/knative-downstream.yaml
=> drop eventing kafka from downstream tests - repo is archived

test/logstream/v2/stream_test.go
Fixes: https://github.com/knative/pkg/issues/3063
/assign @izabelacg 
Like 302-303 kills the context passed to logstream. This context was being used when polling which isn't correct
```go
// Kill the context.
cancel()
```
=> [logstream] test polling should use a different context

apis/duck/v1/register.go
In #3056 if didn't register the new `AuthenticatableType` in the scheme. This PR fixes it
=> Register `AuthenticatableType` in scheme

test/helpers/name.go
- Fixes issue with rand source concurrent access. See https://github.com/knative/serving/pull/15354
=> Fix rand source in name

test/crd.go
Partially https://github.com/knative/serving/issues/15521
* Use istio.sidecar.inject label instead of annotation
/assign @skonto
=> Use istio.sidecar.inject label instead of annotation

webhook/configmaps/configmaps.go, webhook/configmaps/controller.go, webhook/resourcesemantics/defaulting/controller.go, webhook/resourcesemantics/defaulting/defaulting.go, webhook/resourcesemantics/validation/controller.go, webhook/resourcesemantics/validation/reconcile_config.go, webhook/webhook.go
Allow users to configure `DisableNamespaceOwnership` in webhook options. This ensures that users that have other manifest managers of ValidatingWebhookConfigurations and MutatingWebhookConfigurations don't hit conflicts when ownership is overridden.
This has specific detrimental impact when using ArgoCD which [checks for ownerReferences before determining whether it should prune a resource](https://github.com/argoproj/gitops-engine/blob/master/pkg/cache/cluster.go#L1167). This has [caused issues for `kubernetes-sigs/karpenter`](https://github.com/aws/karpenter-provider-aws/issues/6982), which uses `knative/pkg` for webhook management.
I've tested this change in the `sigs.k8s.io/karpenter` codebase with [this commit](https://github.com/jonathan-innis/karpenter/commit/0922f28fae7718a3f46912c …
=> :broom: Give users the ability to disable namespace ownership of webhook configurations

webhook/env.go, webhook/webhook.go
- Added a new environment variable `WEBHOOK_DISABLE_NAMESPACE_OWNERSHIP` to set the `DisableNamespaceOwnership` webhook option added by https://github.com/knative/pkg/pull/3095
- This allows the downstream apps (like Knative Serving) to make use of the ability to not have the Namespace own the webhook configurations, which breaks ArgoCD: https://github.com/knative/serving/issues/15483
Related https://github.com/knative/serving/issues/15483
```release-note
Added `WEBHOOK_DISABLE_NAMESPACE_OWNERSHIP` env-var to set `DisableNamespaceOwnership` in `webhook.Options`
```
**Docs**
```docs
```
=> Add `WEBHOOK_DISABLE_NAMESPACE_OWNERSHIP` env-var

webhook/configmaps/controller.go, webhook/resourcesemantics/defaulting/controller.go, webhook/resourcesemantics/validation/controller.go, webhook/webhook.go
- Fixes the implementation from https://github.com/knative/pkg/pull/3103
- Previously, the env-var would not properly apply for knative-serving, because the controller (which adds the owner references) is initialized before the webhook starts (so we need to move the env-var override to the controller constructor).
/kind bug
Related https://github.com/knative/serving/issues/15483
```release-note
Fixed `WEBHOOK_DISABLE_NAMESPACE_OWNERSHIP` env-var
```
**Docs**
```docs
```
=> Fix `WEBHOOK_DISABLE_NAMESPACE_OWNERSHIP` env-var

hack/update-codegen.sh
- As per title
- Introduced [here](https://github.com/knative/pkg/pull/3084/files#diff-149dfe7bb29d1191dceae3a52915e750e64b7f87257a5fb309c29d3056e2a95d)
=> Fix codegen script

.github/workflows/knative-dependabot.yaml
/assign @skonto 
Got the idea from - https://github.com/dependabot/dependabot-core/issues/935#issuecomment-698481919
=> run dependabot workflow only on dependabot branches

.golangci.yaml, apis/testing/roundtrip/roundtrip.go, controller/controller.go, controller/controller_test.go, controller/two_lane_queue.go, controller/two_lane_queue_test.go, hash/hash.go, hash/hash_test.go, kmeta/names_test.go, metrics/config.go, metrics/memstats.go, metrics/record_test.go, metrics/resource_view_test.go, test/imports/banned_deps_test.go, tracing/http_test.go, webhook/admission_integration_test.go, webhook/testing/factory.go
see individual commits for details
=> Satisfy linter

.github/dependabot.yml
this groups the golang.org/x/ dependencies which frequently conflict with each other when their versions are bumped
=> group golang.org/x dependencies

configmap/parse.go, configmap/parse_test.go, configmap/parser/parse.go, configmap/parser/parse_test.go
We want to parse configmaps but not don't want a heavy dependency on k/k libs
Part of https://github.com/knative/serving/issues/9957
This will matter as a part of the OTel migration - since we will want to parse the config in the queue-proxy
=> pull configmap parsing into separate package

injection/sharedmain/main.go
I noticed a misconfigured metrics URL would prevent the process
from quiting because it was trying to flush metrics forever.
=> When shutting down the OTel providers have a ten second timeout.

configmap/parser/parse.go, observability/metrics/provider.go, observability/metrics/provider_test.go, observability/tracing/provider.go, observability/tracing/provider_test.go
When testing prometheus endpoints I entered
`some.domain.com:9090/some/path`
And this took `some.domain.com` as the scheme. To avoid this landmine
if we end up with an opaque URL we prepend the 'https' scheme to
the endpoint
=> [observability] Default missing endpoint scheme to HTTPS

go.mod, go.sum, observability/tracing/config.go, observability/tracing/provider.go, vendor/go.opentelemetry.io/otel/exporters/stdout/stdouttrace/LICENSE, vendor/go.opentelemetry.io/otel/exporters/stdout/stdouttrace/README.md, vendor/go.opentelemetry.io/otel/exporters/stdout/stdouttrace/config.go, vendor/go.opentelemetry.io/otel/exporters/stdout/stdouttrace/doc.go, vendor/go.opentelemetry.io/otel/exporters/stdout/stdouttrace/trace.go, vendor/go.opentelemetry.io/otel/sdk/trace/tracetest/README.md, vendor/go.opentelemetry.io/otel/sdk/trace/tracetest/exporter.go, vendor/go.opentelemetry.io/otel/sdk/trace/tracetest/recorder.go, vendor/go.opentelemetry.io/otel/sdk/trace/tracetest/span.go, vendor/modules.txt
Setting up a collector or jaeger for manual testing is a bit much  - looking at the stdout is sometimes easier.
Thought this would be useful to have
=> [observability/trace] allow for stdout exporter for tracing - to allow for debugging

controller/controller.go, controller/controller_test.go, controller/queue_metrics.go, controller/two_lane_queue.go, controller/two_lane_queue_test.go, injection/sharedmain/main.go, observability/metrics/k8s/noop.go
`k8s.io/client-go` workqueue package will report metrics for named queues. Our two lane queue was reporting three different metrics named `name-slow`, `name-fast`, `name-consumer` 
The metrics from these queues don't really paint the entire picture of how long a resource is queued in the two lane queue.
This change duplicates/forks some k8s code so that we can properly report 'accurate' metrics for our two lane queue.
/hold for review
/assign @Cali0707 @evankanderson @skonto
=> [controller/observability] adjust metrics reporting for the two lane queue

profiling/server_test.go
Profiling test package doesn't need a reference to the metrics package anymore. This indirectly keeps opencensus dep around
=> drop dependency on metrics package

observability/metrics/prometheus_enabled.go
There was a typo in a comment https://github.com/knative/pkg/issues/3224
This change will update the OTel prom exporter metric names to match
what will become the default in the future. If N is the current
SDK version the N+2 is when the new default will apply.
In the N+1 release - a new TranslationStrategy option will be introduced and we
will want to set the strategy to 'UnderscoreEscapingWithSuffixes'.
Then in N+2 we can drop that option as it will become the default
(or leave it explicitly).
=> Fix prometheus exporter names

controller/queue_metrics.go, controller/two_lane_queue.go
Fixes: https://github.com/knative/pkg/issues/3242
- **fix two lane workqueue depth metric calculation by decrementing when we have something in the queue metrics tracking map**
- **fix var name to reflect it's true purpose**
I think the bug occurs when we have something in the consumer work queue and then something is added to the fast queue. We skip the `add` time recording on the second entry (and depth increment) and we end up with multiple `Get` calls that decremented the queue depth by too much.
Thus right now the depth metric is 'best-effort' since we're not really counting duplicate entries in the queue (that can't be deduped)
To address this we'd probably have to fork the client-go code to better instrument the metrics, or write our own queue implementation
=> [controller] fix depth metrics
