logging/config_test.go
Use more verbose error msg in config test.
=> Verbose error msg for config test

Gopkg.lock, controller/OWNERS, controller/controller.go, controller/controller_test.go, vendor/golang.org/x/sync/AUTHORS, vendor/golang.org/x/sync/CONTRIBUTORS, vendor/golang.org/x/sync/LICENSE, vendor/golang.org/x/sync/PATENTS, vendor/golang.org/x/sync/errgroup/errgroup.go, vendor/k8s.io/client-go/util/workqueue/default_rate_limiters.go, vendor/k8s.io/client-go/util/workqueue/delaying_queue.go, vendor/k8s.io/client-go/util/workqueue/doc.go, vendor/k8s.io/client-go/util/workqueue/metrics.go, vendor/k8s.io/client-go/util/workqueue/parallelizer.go, vendor/k8s.io/client-go/util/workqueue/queue.go, vendor/k8s.io/client-go/util/workqueue/rate_limitting_queue.go
The `controller.go` is from: https://github.com/knative/serving/pull/1770, however, this adds 100% coverage of `controller.go`, which we have been missing in `knative/serving`.
Fixes: https://github.com/knative/pkg/issues/8
WIP until https://github.com/knative/serving/pull/1770 lands.
=> Move our base controller infrastructure into knative/pkg.

Gopkg.lock, apis/volatile_time.go, apis/volatile_time_test.go, vendor/k8s.io/apimachinery/pkg/api/equality/semantic.go
`VolatileTime` is a type that enables us to exclude certain volatile timestamp fields from causing semantic equality to report a difference when only that field changes.
We use this in `knative/serving` for `LastTransitionTime`, which can drift forward during reconciliation if different phases of the reconcile flip-flop a condition.
=> Move VolatileTime into knative/pkg

webhook/webhook.go, webhook/webhook_integration_test.go, webhook/webhook_test.go
In order to have a single webhook support multiple domain contexts, this reworks the `Handlers` argument to embed the `schema.GroupVersion` by wrapping the existing keys with it as a `schema.GroupVersionKind`.
This is mostly straightforward, but one oddity is that I discovered that `AdmissionRequest` gets this same tuple as the less capable `metav1.GroupVersionKind`, so there's a silly conversion we have to do.
I tried this manually vendored in serving with KPA and things worked great.
=> Support multiple group/kind contexts in shared webhook.

webhook/webhook.go, webhook/webhook_test.go
Eventing uses names like "dev.knatave.github.pullrequest" as a event type name. This fails the generic validation added for serving. Moving this logic to serving and removing from pkg.
=> Remove strict name metadata check to be shareable in eventing

controller/controller.go, logging/logkey/constants.go
This adds a logkey.Key for attaching the key being reconciled to a logger we embed into the context passed to Reconcile.  The point of this is to enable us to eliminate [this](https://github.com/knative/serving/blob/928d580756855f24d400104ad4d4cc628a8a841f/pkg/reconciler/v1alpha1/service/service.go#L101-L104) boilerplate from each of the Reconcilers.
These aren't identical, this has the form:
```
knative.dev/key: foo/bar
```
What it's replacing has the form:
```
knative.dev/namespace: foo
serving.knative.dev/service: bar
```
However, the type information present in the latter is redundant with the controller type that [should already be embedded](https://github.com/knative/serving/blob/928d580756855f24d400104ad4d4cc628a8a841f/pkg/reconciler/reconciler.go#L80) in the logger.
cc @mdemirhan
=> Add a logkey for the reconcile key.

test/request.go
Return the spoof response when checking endpoint state. Some serving e2e tests use this.
=> Update WaitForEndpointState to return response

Gopkg.lock, Gopkg.toml, hack/update-codegen.sh, hack/update-deps.sh, hack/verify-codegen.sh, test/presubmit-tests.sh, vendor/github.com/knative/test-infra/scripts/README.md, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh, vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh, vendor/github.com/knative/test-infra/scripts/release.sh
* shared scripts from test-infra live in //vendor/github.com/knative/test-infra/scripts;
* update `update-deps.sh` to keep only the scripts folder;
* all bash scripts were updated to use the vendored scripts;
Part of knative/test-infra#30.
=> Vendor the test-infra scripts

test/e2e_flags.go
The flag docer repo gets different values based on the repo and should be in that repo. For eg. serving images are placed under knative-serving/.*
=> Remove docker repo from e2e flags

hack/verify-codegen.sh
OS X's `mktemp` has no `-p` flag.
=> Make verify-codegen.sh compatible with OS X

apis/field_error.go, apis/interfaces.go
I found it a bit odd that Defaultable interface was in a single file, yet the other interfaces immutable / validatable were in field_error.go. Obviously no functional changes, just thought this is cleaner. Thoughts?
=> Move interfaces into single file.

test/e2e_flags.go
Part-1 of fixing https://github.com/knative/pkg/issues/60. Will update serving to call parse once this is merged.
=> Dont call flag.parse in pkg/test

logging/config.go, test/logging/logging.go
Previous, since we weren't skipping, the logged caller would be 'logging.go'
For example see conformance logs [here](https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-serving-continuous/1037642038863990784)
```
info TestBlueGreenRoute logging/logging.go:141 Creating a Configuration
```
Will become
```
info TestBlueGreenRoute  conformance/blue_green_test.go:183 Creating a Configuration
```
=> The test logger will now log the correct caller

kmeta/OWNERS, kmeta/doc.go, kmeta/labels.go, kmeta/labels_test.go
This bootstraps this package with a useful collection of label methods for managing sub-resources.  I'd initially written this as a way of managing versioned DaemonSet resources as part of WarmImage ([see here](https://github.com/mattmoor/warm-image/blob/62cad8045a6bb4bbc42bc1556beba47a73f081b9/pkg/reconciler/warmimage/resources/meta.go#L28)).
I am upstreaming this here because I want to take advantage of it in Build for managing Image cache subresources of [Cluster]BuildTemplate resources.
=> Create a kmeta package for libraries acting on ObjectMeta.

apis/interfaces.go, kmeta/owner_references.go
An OwnerRefable type provides sufficient information that we can
construct a metav1.OwnerReference from it, e.g. for
kmeta.NewOwnerReference, which does just that.
Addresses comment from: https://github.com/knative/serving/pull/2014
=> Introduce an OwnerRefable interface

kmeta/owner_references.go, kmeta/owner_references_test.go
This is more accurate, since we're creating a controller ref (and keeps
the naming consistent with metav1).
Also, adds a test!
=> Rename kmeta.NewOwnerReference to NewControllerRef

apis/field_error.go, apis/field_error_test.go
I have found situations where I want to do the following:
```
for i, c := range spec.Collection {
if err := doValidation(c); err != nil {
return err.ViaIndex(i).ViaField("collection")
}
}
```
OR
```
for k, v := range spec.Bag. {
if err := doValidation(v); err != nil {
return err.ViaKey(k).ViaField("bag")
}
}
```
This adds helpers to do that.
=> Adding ViaIndex, ViaKey, ViaFieldIndex, ViaFieldKey to FieldErrors

apis/field_error.go, apis/field_error_test.go
Found an issue integrating with serving that `nil.also(nil)` should be `nil`, but it was returning an empty object. Fixed that.
=> Adding also always to return nil for nil errors

apis/kind2resource.go, apis/kind2resource_test.go
We've got a few of these evolving, and so I wanted to create a helper (in the hopes that someone will solve our pluralization properly).
[knative/eventing](https://github.com/knative/eventing/pull/437/files#diff-df3ef4686fadf4bf98714d6163f81654R277)
[knative/serving](https://github.com/knative/serving/blob/69811e7a9158732d29963ebb13193c33b51dd313/pkg/reconciler/v1alpha1/autoscaling/kpa_scaler.go#L119)
=> Create a common way for turning GVK into GVR.

controller/controller_test.go
The rate limiting queue makes the sleep necessary.  Locally I see 0-2 failures when this is run with -count=10000.  This bumps the sleep slightly to reduce this further.
Fixes: https://github.com/knative/pkg/issues/56
=> Bump the sleep in the controller testing.

apis/duck/patch.go, apis/duck/patch_test.go, webhook/webhook.go
This creates a helper for synthesizing JSON patches from before/after objects.
This aliases `[]jsonpatch.JsonPatchOperation` as `JSONPatch` to provide `MarshalJSON` as a convenience, since this is what needs to be passed to `Patch()` on K8s clients.
=> Create a helper for synthesizing patches.

Gopkg.lock, apis/duck/cached.go, apis/duck/cached_test.go, apis/duck/enqueue.go, apis/duck/enqueue_test.go, apis/duck/interface.go, apis/duck/typed.go, apis/duck/typed_test.go, apis/duck/unstructured_test.go, hack/66078.patch, hack/update-deps.sh, testing/register.go, vendor/k8s.io/client-go/dynamic/fake/simple.go, vendor/k8s.io/client-go/dynamic/interface.go, vendor/k8s.io/client-go/dynamic/scheme.go, vendor/k8s.io/client-go/dynamic/simple.go
This starts to sketch common libraries for instantiating informers/listers for a particular GroupVersionResource as one of our duck types.
You can instantiate a duck.InformerFactory like so:
```go
dynaClient, err := dynamic.NewForConfig(cfg)
if err != nil {
logger.Fatalf("Error building dynamic clientset: %v", err)
}
dif := &duck.CachedInformerFactory{
Delegate: &duck.TypedInformerFactory{
Client:       dynaClient,
Type:         &duckv1alpha1.Target{},
ResyncPeriod: 30 * time.Second,
StopChannel:  stopCh,
},
}
```
Then, as you come across new GroupVersionResources that you want to handle:
```go
informer, lister, err := dif.Get(gvr)
if err != nil {
logger.Fatalf("Error starting shared index informer: %v", err)
}
```
With the `duck.TypedInformerFactory` the objects will be returned as the …
=> Informers / Listers for Duck Types.

apis/duck/podspec_test.go
This defines a simple test duck type called PodSpecable, which has the same shape for embedding a corev1.PodTemplateSpec as numerous core Kubernetes resource: ReplicaSet, Deployment, StatefulSet, DaemonSet, and Job.
=> Add an example / test that we can Duck type Core K8s resources.

Gopkg.lock, Gopkg.toml, apis/duck/unstructured_test.go, logging/testing/util.go, vendor/go.uber.org/zap/internal/ztest/doc.go, vendor/go.uber.org/zap/internal/ztest/timeout.go, vendor/go.uber.org/zap/internal/ztest/writer.go, vendor/go.uber.org/zap/zapcore/memory_encoder.go, vendor/go.uber.org/zap/zaptest/doc.go, vendor/go.uber.org/zap/zaptest/logger.go, vendor/go.uber.org/zap/zaptest/testingt.go, vendor/go.uber.org/zap/zaptest/timeout.go, vendor/go.uber.org/zap/zaptest/writer.go, webhook/certs_test.go, webhook/helper_test.go, webhook/webhook_test.go
This changes the `TestLogger` and `TestContextWithLogger` to use the `zaptest` `Logger` 
This has two benefits 
- logs are suppressed when running unit tests unless a test fails or `-v` flag is supplied
- logs will be printed with the correct indentation wrt to `go test` output
I made some changes in some of the tests to use this logger
The output format changes
```
=== RUN   TestUpdatingWebhook
2018-09-24T11:32:57.956-0400	INFO	webhook/webhook.go:400	Webhook already exists
2018-09-24T11:32:57.956-0400	INFO	webhook/webhook.go:406	Updating webhook
--- PASS: TestUpdatingWebhook (0.00s)
```
becomes
```
=== RUN   TestUpdatingWebhook
--- PASS: TestUpdatingWebhook (0.00s)
logger.go:130: 2018-09-24T09:23:34.222-0400	INFO	webhook/webhook.go:400	Webhook already exists
logger.go:130: …
```
=> Use zaptest logger for our TestLogger

tracker/doc.go, tracker/enqueue.go, tracker/enqueue_test.go, tracker/interface.go
To use this with a typical informer, e.g. the way `Route` would monitor `Configurations` and `Revisions`, you'd do something like:
```go
c := &Reconciler{
Base:                 reconciler.NewBase(opt, controllerAgentName),
...
}
impl := controller.NewImpl(c, c.Logger, "Routes")
t := tracker.New(impl.EnqueueKey, 30*time.Minute)
configInformer.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
AddFunc:    t.OnChanged,
UpdateFunc: controller.PassNew(t.OnChanged),
})
revisionInformer.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
AddFunc:    t.OnChanged,
UpdateFunc: controller.PassNew(t.OnChanged),
})
// Now use c.tracker.Track(revisionRef, route) or c.tracker.Track(configRef, route)
// each Reconcile(route) to refresh the cross-object leases.
c.tracker = t
```
To use …
=> This change implements a more generalized form of the BuildTracker.

apis/duck/podspec_test.go, apis/duck/v1alpha1/channelable_types.go, apis/duck/v1alpha1/conditions_types.go, apis/duck/v1alpha1/generational_types.go, apis/duck/v1alpha1/implements_test.go, apis/duck/v1alpha1/legacy_targetable_types.go, apis/duck/v1alpha1/sinkable_types.go, apis/duck/v1alpha1/subscribable_types.go, apis/duck/v1alpha1/targetable_types.go, apis/duck/verify.go, apis/duck/verify_test.go, testing/resource.go, testing/resource_test.go, webhook/webhook.go
Those calls to `duck.VerifyType` are done at runtime and thus could be
costly at program startup. Putting them under tests ensure we still
assert those types but during unit testing.
This is part of #97 (not clusing it as there will be PRs on `serving`, `eventing` and `build` to follow :wink: 
cc @dprotaso 
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>
=> Move the use of `VerifyType` in tests

apis/duck/proxy.go, apis/duck/typed.go, apis/duck/typed_test.go
The watch logic returns events containing `unstructured.Unstructured`.  This adds a proxy that converts those to the appropriate structured type.
=> Add logic to convert the watch.Interface.

hack/update-codegen.sh, hack/update-deps.sh, hack/verify-codegen.sh, test/presubmit-tests.sh
Some systems may not have `/bin/bash` (NixOS for example)… Using
`/usr/bin/env bash` has the benefit of looking for whatever the
default version of the program is in your current environment.
/assign @adrcunha
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>
=> Use `/usr/bin/env bash` instead of `/bin/bash`

test/README.md
While working on knative/build-pipeline#16
I started trying to build some integration tests, and I wanted to use
the code which had been moved to knative/pkg, but it turned out the docs
hadn't been ported with the code, so I am moving the docs relevant to
knative/pkg/test to that repo.
Removing docs from knative/serving in https://github.com/knative/serving/pull/2097.
=> Move docs from knative/serving to knative/pkg

apis/duck/scale_test.go
There are a number of notable differences:
* Selector is part of Spec not Status,
* Selector is structured vs. `string`,
* The Replicas in Spec is a pointer.
=> Add a test that shows modeling /scale as a duck for core K8s types.

kmeta/labels.go, kmeta/labels_test.go
Unlike `ResourceVersion`, which changes whenever the resource changes at all (including `/status` which can be high churn), `Generation` only changes when the `/spec` of a CRD changes (for CRDs starting in 1.11, right now they are locked at `generation: 1`).
These methods are useful for interacting with K8s resource now, and will be useful for CRDs soon.
Fixes: https://github.com/knative/pkg/issues/116
=> Add Generation variants of kmeta/labels.go

test/logging/logging.go
@mdemirhan It seems like the zap logger needs a key defined for a field for it to be printed, even when using the console encoder.
=> Add timeKey so time is actually logged in e2e tests.

configmap/filter.go, configmap/filter_test.go, configmap/store.go, configmap/store_test.go, controller/controller.go, controller/controller_test.go
- Add GlobalResync(cache.SharedInformer) method to *controller.Impl (knative/serving#2182)
- Move UntypedStore from serving/pkg/config to pkg/configmap (knative/serving#2184)
- Add onAfterStore callbacks to UntypedStore
- Add TypeFilter to enable composable construction of such callbacks
=> Prepare for global resync on ConfigMap changes

webhook/webhook.go, webhook/webhook_integration_test.go, webhook/webhook_test.go
Fixes: #130 
* Exit when bootstrap http server of webhook error
* Clean useless newRunningTestAdmissionController func
=> Exit when bootstrap http server of webhook error

webhook/webhook.go, webhook/webhook_integration_test.go, webhook/webhook_test.go
Fixes: #124 
Make clientAuth of webhook server into a configuration option
=> Make clientAuth of webhook server into a configuration option

apis/duck/v1alpha1/channelable_types.go
Make Channelable match the definition in https://github.com/knative/eventing/pull/482.
=> Make Channelable match the definition in https://github.com/knative/eventing/pull/482.

test/e2e_flags.go
Avoid segmentation fault when the user is not returned correctly. This might happen when the tests are run from within a Docker container which runs as a non-root user and entries in /etc/passwd or /etc/group are not set. This is common when running on OpenShift. 
If the default kubeconfig is not set correctly the user can still pass their own config through the kubeconfig flag.
=> Check error condition when setting default kubeconfig

test/spoof/spoof.go
We need to expose this so as to call the endpoint using the perf generator as well.
=> Export method to get service endpoint from spoof client

test/spoof/spoof.go, test/zipkin/util.go
Change adds Zipkin Tracing header to each HTTP request made through
SpoofingClient to knit together Zipkin traces on the backend to requests
made through the client. To use the support tests needs to call into
SetupZipkinTracing(..) in their Setup method to setup Zipkin tracing.
This method setups Port-Forwarding from the machine(Port 9411) where tests are run
to Zipkin Pod on the Knative setup.  TearDown/Cleanup method needs to call KillZipkinPortFowardingProcess(..) to cleanup Zipkin tracing setup.
=> Adding Zipkin tracing support for SpoofingClient

controller/controller.go, controller/controller_test.go
Fixes: https://github.com/knative/serving/issues/2350
Here I also introduce an error wrapper `permanentError`, which allow users to decide to requeue/not requeue a key on certain error(I meant to make it `transientError`, but considering the fact we will have to wrap existing errors in serving controllers that way, I make it the opposite).
/assign @mattmoor @tcnghia
=> requeue keys on error in controller

controller/controller.go, kmeta/accessor.go, kmeta/accessor_test.go
This promotes the private deletion-handling helper wrapping `meta.Accessor` into `kmeta`.  The wordy name is based on the wordier `cache.DeletionHandlingMetaNamespaceKeyFunc`, since it serves a similar purpose.
=> Move the `getObject` method into `kmeta`

Gopkg.lock, cloudevents/doc.go, cloudevents/encoding_binary.go, cloudevents/encoding_structured.go, cloudevents/event.go, cloudevents/event_test.go, cloudevents/handler.go, cloudevents/handler_test.go
Adding cloudevents sdk for working with cloud event producers and consumers.
This will be used in `knative/eventing` and `knative/eventing-sources`.
=> Adding cloudevents lib to pkg

apis/duck/v1alpha1/condition_set.go, apis/duck/v1alpha1/condition_set_impl_test.go, apis/duck/v1alpha1/condition_set_test.go, apis/duck/v1alpha1/conditions_types.go
This change updates the `ConditionSet` datatype to treat the set of conditions that it is initially supplied with as the set of "terminal" conditions, where as before:
1. If all `True`, results in `Ready=True`
2. If any `False`, results in `Ready=False`
3. Otherwise, `Ready=Unknown`
However, in additional to this initial "terminal" set, other conditions may be set that are "non-terminal" and have no influence over the "happy" condition (e.g. `Ready`).
Related to: https://github.com/knative/serving/issues/2394
I'm putting a `/hold` on this until we discuss at next week's API WG.
=> Update the ConditionSet to support non-terminal conditions.

cloudevents/event.go
`fieldEventTime` was not used, not is it required on the fieldXy list of required attributes
=> Removing eventTime for required attrs.

controller/controller.go, controller/controller_test.go
Update the `EnqueueLabelOf` func to be able to replace funcs like `EnqueueEndpointsKPA`, `EnqueueEndpointsRevision`
=> Update EnqueueLabelOf to handle resources in same namespace

Gopkg.lock, vendor/github.com/knative/test-infra/Gopkg.lock, vendor/github.com/knative/test-infra/Gopkg.toml, vendor/github.com/knative/test-infra/OWNERS, vendor/github.com/knative/test-infra/ci/prow/config.yaml, vendor/github.com/knative/test-infra/ci/prow/plugins.yaml, vendor/github.com/knative/test-infra/ci/testgrid/config.yaml, vendor/github.com/knative/test-infra/dummy.go, vendor/github.com/knative/test-infra/images/prow-tests/Dockerfile, vendor/github.com/knative/test-infra/scripts/README.md, vendor/github.com/knative/test-infra/scripts/dummy.go, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh, vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh, vendor/github.com/knative/test-infra/scripts/release.sh, vendor/github.com/knative/test-infra/test/presubmit-tests.sh, vendor/github.com/knative/test-infra/test/unit/e2e-custom-flag-tests.sh, vendor/github.com/knative/test-infra/test/unit/library-tests.sh, vendor/github.com/knative/test-infra/test/unit/presubmit-full-custom-integration-tests.sh, vendor/github.com/knative/test-infra/test/unit/presubmit-integration-tests-common.sh, vendor/github.com/knative/test-infra/test/unit/presubmit-partial-custom-integration-tests.sh, vendor/github.com/knative/test-infra/test/unit/release-tests.sh, vendor/github.com/knative/test-infra/tools/apicoverage/apicoverage.go, vendor/github.com/knative/test-infra/tools/dep-collector/imports.go, vendor/github.com/knative/test-infra/tools/gcs/gcs.go, vendor/github.com/knative/test-infra/tools/testgrid/testgrid.go
Old images cleanup is no longer part of e2e test, this functionality will be moved to a separate job runs periodically.
*This part is done in knative/test-infra, updating dependencies in this repo to include this update.
Link to the issue in test-infra: knative/test-infra#276
=> Remove images deletion step from e2e test / Update test-infra

controller/controller.go, controller/controller_test.go
I was hoping to switch from a simple string key to a struct to include additional metadata into our workqueue item (in particular the time at which it was queued), but the great unit tests here reminded me that this would not properly deduplicate keys (they would have different queue times!), so I'm settling for simplifying the loop in a few ways:
1. Keys can only be strings, so remove some error checking and a test.
1. We were wrapping a block in a `func` because it contained `defer`, but the outer function had nothing in it.
I'd still like to try and find a way to track queue times for keys, so that we can surface two interesting metrics:
1. How long are things spending queued?
1. How long between events being observed and us responding? (above + reconcile latency)
/assign @mdemirhan
=> Simplify the core controller logic.

DEVELOPMENT.md, README.md, apis/istio/v1alpha3/README.md, code-of-conduct.md, test/README.md
Produced via: `prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github)`
=> Format markdown

apis/duck/patch.go, apis/duck/patch_test.go, testing/resource.go, webhook/webhook.go, webhook/webhook_test.go
Immutable fields with default values may now be changed iff they change is to populate their default value.  This is to support defaulting in the scenario where an object was created long ago and a new field (with a default!) is added.  When controllers attempt to mutate the object status today, this would create a webhook rejection!  With this change, we compare against a freshly defaulted "old" object to exclude newly defaulted fields from the immutability check.
We saw this in knative/serving for the newly added TimeoutSeconds field in Revision (otherwise immutable), which I believe it leading to upgrade testing flakes since post-upgrade Revision status updates will fail.
=> This exempts defaulting from the rules governing field immutability.

apis/duck/patch.go, apis/duck/patch_test.go, webhook/webhook_test.go
My prior change added sorting to the duck.CreatePatch method to try and stabilize the result of jsonpatch.CreatePatch, which is otherwise non-deterministic (probably walking a map?).
My bad assumption was that the patch operations this generated wouldn't conflict, e.g. it should use `replace` vs. `remove` and `add`.
Clearly this was bad because we start getting really strange errors trying to import this into knative/serving, e.g.
https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_serving/2646/pull-knative-serving-integration-tests/1070435951391543298/
=> Undo the patch sorting.

apis/field_error.go, apis/field_error_test.go
- rename FieldError.getNormalizedError to be normalized:
- Go kind of discourages GetA() vs A()
- it's an error, so normalizing itself is also an error, so
normalizedError() is a tautology at this point
- flatten was doing a[x]=fmt.Sprintf("%s%s", a[x],y), which is a very
expensive substitution for a[x]+=y
- some minor test cleanups (fix strings, streamline `got, want:=`
pattern, etc.
=> Some clean ups in the FieldError code and its tests.

test/spoof/spoof.go
Today, `GetServiceEndpoint` will exit if the first given ingressName does not contain a valid endpoint, even though the second one does.
I noticed this when testing using Docker for Mac, where I have a defunct knative-ingressgateway (which is only there for compatibility reasons anyway).
This enables `GetServiceEndpoint` to search through the whole list to find something fitting.
=> Enable 'GetServiceEndpoint' to search through all given ingress names.

.gitattributes
This allows running `./hack/update-deps.sh` on Windows if you have `dep` and `go` on your PATH, and you have GOPATH set.
=> Check out shell scripts with unix line endings, even on windows.

version/version.go, version/version_test.go
Knative meanwhile relies on at least Kubernetes 1.11 and I've been bitten by this requirement at least once. This utility can be built into each of our controllers, webhooks etc. to notify/crash if the version is not compatible.
Initially proposed at https://github.com/knative/build/pull/503.
=> Add a utility to check against a minimum required version number.

test/kube_checks.go
In some cases, pods have entered 'Terminating' state, and we're only
waiting for K8s to kill the pods which unfortunately could go over the
5 minutes timeout here.
=> Increase pod termination wait time a little bit.

apis/duck/verify.go, apis/duck/verify_test.go, kmp/diff.go, kmp/diff_test.go
Unlike `VerifyType`, `ConformsToType` will return the following:
- an error when any marshalling/unmarshalling fails
- false when the concrete type does not implement the duck type
- true when the concrete type implements the duck type
=> 🦆 Duck Typing - add a ConformsToType helper

metrics/config.go, metrics/config_test.go
Propose:
1. Set metrics backend to the value from an environment variable first. Then override it to the value from config map, if any. This gives the ability to set metrics backend when rolling out a new knative serving components while keep existing config map unchanged.
1. Do not panic the process if the backend is not supported. Activator and autoscaler should continute to work without emitting metrics to any backend.
=> Read metrics backend from environment variable

metrics/exporter.go, test/cleanup.go, test/spoof/spoof.go
While reviewing some other CL, I saw some avenues for improving
spoof.go, to log the URL that's being fetched, which would help in test
debugging and to use switch construct, rather than nested if's.
While testing the change, I noticed some shifty loggin from the
exporter, so I fixed that as well while I was there.
=> Some fixes to the spoof.go and exporter.go

apis/duck/v1alpha1/condition_set.go
Addresses: https://github.com/knative/serving/issues/2849
This is because the condition set in serving is a global variable.
=> Conditions implementation no longer mutates the underlying dependents array

metrics/metricskey/constants.go
Change the label sent to Stackdriver `knative_revision` resource type from `project` to `project_id`. The later is the actual key defined in Stackdriver.
=> Stackdriver resource label change for knative_revision resource type

metrics/metricskey/constants.go
Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -type f -name '*.go' -print))`
`goimports -w $(find -name '*.go' | grep -v vendor)`
=> golang format tools

test/kube_checks.go
These are generally usable test cases for K8s and as such should live in
pkg/test
=> Move crd checks from serving in to test

system/clock.go, system/names.go, system/testing/names.go
synchronize with https://github.com/knative/serving/pull/2708
=> Add namespaces in knative/pkg

test/spoof/spoof.go
Utility method to retrieve zipkin traces had missed a defer Close call. This change fixes that
=> Fix to add defer Close in Spoof Client zipkin tracing

cloudevents/doc.go, cloudevents/encoding_binary.go, cloudevents/encoding_structured.go, cloudevents/event.go, cloudevents/event_test.go, cloudevents/event_v01.go, cloudevents/handler.go
In-progress: #193 
This PR renames `CloudEventsVersion` and `EventContext` to `V01...`, and leaves legacy aliases to allow seamless upgrades.
Additional changes:
* Introduces `SendContext`/`LoadContext` interfaces to support read/write of arbitrary CloudEvents versions.
* Makes `CloudEventsVersion` required per v0.1 spec.
The next step is to change the return type on `FromRequest` to `(LoadContext, error)` and introduce the `V02EventContext` file. This will also necessitate changing the tests (and therefore downstream code), so I'd prefer to do this in a separate PR (see 366 in `handler.go` for an example of the work needed -- basically calling `AsV01()` or `AsV02()` in locations which expect a particular version).
=> CloudEvents v0.2 support, step 1: interfaces and versioned types.

tracker/enqueue.go, tracker/enqueue_test.go
This change adds an immediate callback to the tracker when a key is added to track an entity that previously lacked coverage.
Fixes: https://github.com/knative/serving/issues/2954
=> Add an immediate callback for new registrations in Tracker.

cloudevents/builder.go, cloudevents/builder_context_test.go, cloudevents/builder_test.go, cloudevents/client_test.go
Allow event type to be overridden in cloudevent client.
Also fix issue where context was not tested after overrides.
fixes: https://github.com/knative/pkg/issues/249
=> Allow event type to be overridden in cloudevent client.

test/kube_checks.go
This was hardcoded from when we moved it in from serving - it needs to
be configurable here.
=> Remove knative-serving in test/kube_checks

apis/duck/v1alpha1/conditions_types.go
This restores the appearance of "terminal" conditions to what is was prior to the separation of "terminal" and "non-terminal" conditions.
Terminal conditions with an "Error" severity will simply omit the field.
This keeps coming up, and came to a head when both Evan and Ville bugged me about it in the same day.
Fixes: https://github.com/knative/serving/issues/2507
=> Make "Severity: Error" conditions less scary.

apis/field_error.go, apis/field_error_test.go
This is useful when we are dealing with primite leaf list (e.g.
a list of strings).
The alternative are
a) creating dummy error and then executing ViaFieldIndex(), which is
plain ugly
b) implementing Validate() on the primitive type via type aliasing and
then collecting errors, which seems an overkill.
In addition it seems ViaFieldIndex was not covered by unit tests,
so I've added one to take care of that.
=> Add `AtIndex` method to deal to attach index at the current error.

test/README.md, test/clients.go, test/e2e_flags.go, test/spoof/spoof.go
When testing locally its common to use a cluster which both does not
have resolvable dns for ksvcs and does not have public IPs. Support
overriding the endpoint for knative's ingress controller to a static
value which can be set to e.g. the knative-ingressgateway nodeport.
=> Add static endpoint override to test/spoof

logging/testing/util.go, test/logging/logging.go
This helps with running tests with `-count=X`, since test loggers hog T objects and they are not reusable.
/cc @mattmoor
=> Clean test loggers

apis/duck/typed_test.go
No reason to specify empty receiver if there's no need for one.
=> remove the redundant receiver

websocket/connection.go, websocket/connection_test.go
This should further increase the durability of our websocket connections. See https://github.com/knative/serving/issues/3138
Ping messages are sent to actively probe the websocket connection. By default, the websocket servers we use send a pong message back. This can be used to break indefinite read calls.
=> Add ping message verification to the websocket connection.

test/helpers/data.go
Fixes: #226
I have added the helper function`AppendRandomString` into `test/helpers` module (helpers being a new module), sample usage:
```go
package pkg
import (
"github.com/knative/pkg/test/helpers"
"testing"
"strings"
)
func TestAppendRandomString(t *testing.T) {
s := helpers.AppendRandomString("myprefix")
if !strings.HasPrefix(s, "myprefix") {
t.Fatalf("Failed to verify prefix: %s", s)
}
if len(s) != 18 {
t.Fatalf("Failed to verify string size: %d", len(s))
}
t.Logf("---%s---", s)
}
```
I was looking for a first good issue and this one looked simple enough :)
=> test/helpers module to store AppendRandomString helper fn

webhook/webhook.go
As per net.http package for `http.Request.Body`
```
The Server will close the request body. The ServeHTTP
Handler does not need to.
```
=> Don't close the http.Request body

test/helpers/data.go, test/helpers/data_test.go
Port and rewrite the comment from the original.
Remove the sync.Once(). Initializing during package initialization is just as good.
Mutex doesn't have to be a pointer
/cc @mattmoor @srinivashegde86
=> Simplify and comment AppenRandomString

test/clients.go, test/request.go, test/spoof/spoof.go
This is a breaking change, that can be fixed up by replacing `logger,` with `logger.Infof,` in the argument lists for these functions.
This is part of a larger cleanup to allow us to use alternate log methods like `t.Logf` in place of `BaseLogger`.
=> Adapt the spoofing client to take a "FormatLogger" instead of a BaseLogger

test/request.go
As proposed by @mattmoor in [#3259 (comment)](https://github.com/knative/serving/pull/3259#discussion_r257887741) this makes it possible to use `IsStatusOK` without the additional parentheses.
=> Make it possible to use 'IsStatusOK' without parentheses.

test/spoof/spoof.go, test/zipkin/doc.go, test/zipkin/util.go
Existing support for Zipkin tracing pushes the responsibility of logging zipkin traces to individual tests. This change moves the responsibility to SpoofClient, so that all tests get it by default. Individual tests
can disable this functionality by just disabling a ZipkinTracingEnabled flag in zipkin package.
Zipkin tracing in Spoofing client checks to see if the ZipkinTracingEnabled flag is enabled and only logs traces for requests that have encountered Server errors i.e if the http.Response.StatusCode between 500 to 599.
For SpoofingClient.Poll calls we only log trace of the final SpoofingClient.Do made.
=> Adding support for Zipkin tracing in SpoofClient

test/README.md, test/cleanup.go, test/clients.go, test/logging/logging.go, test/request.go, test/spoof/spoof.go
This also moves the FormatLogger from spoof to logging package
Part of https://github.com/knative/test-infra/issues/530
=> Remove baselogger and use FormatLogger everywhere

test/monitoring/doc.go, test/monitoring/monitoring.go, test/zipkin/util.go
Part of https://github.com/knative/test-infra/issues/540
This removes some things from the zipkin package into a separate monitoring package that can be used for all monitoring components like the prometheus package as well. This will help us consolidate things for monitorng usage in our tests
=> Separate common monitoring methods into monitoring package

test/request.go, test/spoof/spoof.go
See knative/serving#3396 for in-context use of this. When an error occurs in a test using `client.Poll` we usually want to report all the information we can on the failed request.
=> Consistently log the full response on errors in tests.

apis/istio/v1alpha3/virtualservice_types.go, apis/istio/v1alpha3/zz_generated.deepcopy.go
Hello,
The CORS policy was missing from the Istio HTTPRoute definition.
Signed-off-by: stefanprodan <stefan.prodan@gmail.com>
=> Add missing CORS Policy to Istio HTTP route

test/request.go
Nothing should use this matcher anymore. It allows for any kind of failed request and hides errors badly.
=> Remove 'MatchesAny'.

controller/stats_reporter_test.go, metrics/record.go, metrics/record_test.go
`metrics.Record` adds a layer around `stats.Record` to guide what metrics can be record based on package level config.
Expected:
If the config is not set, do record. User should make sure the config is set before using `metrics.Record` otherwise it just proxies to `stats.Record` based the assumption that users expect the metrics to be recorded when they call this function.
Actual:
If the config is not set, don't record.
=> Record metrics if config is nil

test/monitoring/monitoring.go, test/zipkin/util.go
Some monitoring components are in knative-monitoring namespace, namely pronetheus while a few like zipkin are in istio namespace. Make this generic so that each component can define this.
=> Dont use istio-system namespace as default for monitoring components

webhook/webhook.go
This change enables us to define a duck type that applies to a whole class of GroupVersionKinds and leverage it to perform generic validation, defaulting, etc.
Fixes: #322
=> Modify the webhook to allow the use of duck types.

test/clients.go, test/crd.go, test/e2e_flags.go, test/kube_checks.go
This PR adds:
1. Export GetConfigMap method
1. Create methods for working with k8s pods
1. Create a new file `crd.go` that adds few methods to deal with crd's. 
1. Add `DOCKER_REPO` and `TAG` flags here as we need it in other repos.
1. Add a few wait cheks for k8s pods
=> Add some more common test componets in pkg/test/

apis/duck/v1alpha1/conditions_types.go
The new conditions does not tell k8s client how to patch merge. Adding those annotations.
=> Need to use patch merge for conditions.

test/spoof/spoof.go
Some of the integration tests fail after Istio reprogramming
with `connection refused` errors.
They are usually transitive and are happening due to the Istio probes
temporarily failing after reprogramming.
With this change we'll retry those errors, hopefully reducing the
flakes.
/cc @tcnghia @mattmoor 
Should help with https://github.com/knative/serving/issues/3452
=> Retry the connection refused errors.

apis/duck/v1alpha1/condition_type_test.go, apis/duck/v1alpha1/conditions_types.go
I wanted this when rewriting the Pipeline e2e test in Serving to use the dynamic client and checking status via this duck type.
See here: https://github.com/knative/serving/blob/b0ad29dbc869716cf5d80b7557d14472e33fc03f/test/e2e/build_pipeline_test.go#L84
=> Add a GetCondition method to Status

testing/resource.go, webhook/webhook.go, webhook/webhook_integration_test.go, webhook/webhook_test.go
Clients of webhook can now decorate the request context with additional metadata via:
```
ac := &AdmissionController{
... // As before
WithContext: func(ctx context.Context) context.Context {
// logic to attach stuff to ctx
}
}
```
This metadata can then be accessed off of the context in methods like
`SetDefaults` and `Validate` on types registered as webhook handlers.
Fixes: https://github.com/knative/pkg/issues/306
=> This creates a way for clients of the webhook to decorate the request context.

test/spoof/error_checks.go, test/spoof/error_checks_test.go, test/spoof/spoof.go
Adding retries for DNS error to prepare for using `.xip.io` or `.nip.io` in our tests.
=> Retry DNS errors in spoof client.

test/ingress/ingress.go
This matches the directory structure, and avoids confusion in some tools that expect/require package names to match the directory they're in.
=> Define package ingress for ingress.go

apis/istio/v1alpha3/gateway_types.go
Add `CredentialName` into `Gateway` for TLS configuration.
Note that this feature depends on Istio 1.1. So don't check it in until Istio 1.1 is landed within Knative.
=> Add CredentialName into Gateway

apis/testing/conditions.go
Add the test helpers to simplify and unify the condition checking.
Although I am not a big fan of the utils taking in `testing.T`, but I think it should be fine here.
/cc @mattmoor
=> Condition checkable utilities

Gopkg.lock, apis/metadata_validation.go, apis/metadata_validation_test.go, vendor/k8s.io/apimachinery/pkg/api/validation/doc.go, vendor/k8s.io/apimachinery/pkg/api/validation/generic.go, vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta.go, vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
This assumes that we want to strictly allow DNS labels in names everywhere.
=> Share the common parts of Serving ObjectMeta validation

apis/testing/conditions.go
Upon actually using the helpers, I found fatal's annoying and I think we should resort to the plain old error'ing instead.
/cc @mattmoor
=> Switch to error from fatal

apis/contexts.go, apis/contexts_test.go, apis/interfaces.go, testing/inner_default_resource.go, testing/resource.go, webhook/webhook.go, webhook/webhook_test.go
Deprecate apis.Immutable and apis.Annotatable.
This deprecates the `apis.Immutable` and `apis.Annotatable` interfaces,
which were both awkward niche extensions of `apis.Validatable` and
`apis.SetDefaults` for specific contexts that the former set didn't
cover well.
With this change, the expectation is that types that want to check
for immutability will instead access the "baseline" object via the
context from within updates.  For example:
```
func (new *Type) Validate(ctx context.Context) *apis.FieldError {
if apis.IsInUpdate(ctx) {
old := apis.GetBaseline(ctx).(*Type)
// Update specific validation based on new and old.
}
}
```
For applying user annotations, the type writer can write:
```
func (new *Type) SetDefaults(ctx context.Context) {
if apis.IsInCreate(ctx) {
ui := …
```
=> Deprecate apis.Immutable and apis.Annotatable.

apis/condition_set.go, apis/condition_set_impl_test.go, apis/duck/v1beta1/status_types.go, apis/duck/v1beta1/status_types_test.go, apis/interfaces.go
The backbone of our Condition system is our "happy" condition and
the semantics governing how other subconditions influence that condition.
When looking towards Conversion, it is possible for the set of conditions
to vary between `v1alpha1` and `v1beta1`, but the "happy" condition should
remain consistent across versions.
The main changes:
1. Provide a `ConvertTo` helper for "converting" between `duckv1beta1.Status`
types in this "lowest common denominator" sense, where we just copy the
happy condition.
2. When `InitializeConditions()` (plural) is called, seed the initial state
of sub-conditions from the initial state of the "happy" condition, if True.
This change enables us to completely change the condition space across
versions, while maintaining the consistency of the happy condition. …
=> Start to lay the groundwork for Status conversion.

test/spoof/error_checks.go
It seems that typed-check aren't robust enough, so we are switching to
checking the error message here.
=> Use string match to classify DNS error.

test/clients.go, test/kube_checks.go
I think it's better to let user specify the `namespace`, rather than hard code it with the one passed as a flag, since it's not mandatory for the user to pass the `namespace` flag. 
Other functions in the `kube_checks.go` file are actually either allowing passing `namespace` or directly using the `pod` or `deployment` reference.
=> Do not hard code namespace when checking pod logs

controller/controller_test.go, controller/helper.go, controller/helper_test.go
This allows impl to apply filtering and queuing logic of their own,
instead of calling Enqueue() for everything.
Currently ConfigMap update event triggers GlobalResync which will evade the filtering logic like ClusterIngress class annotation (or KPA class annotation).  Once this is checked in we can switch ConfigMap update to use this version instead.
=> Add a version of GlobalResync that calls an event handler.

apis/field_error.go, apis/field_error_test.go
Adds a new function in FieldErrors for validating against fieldmasks.
See https://github.com/knative/serving/pull/3779 for usage.
=> Add CheckDisallowedFields

metrics/config.go, metrics/exporter.go, metrics/exporter_test.go, metrics/stackdriver_exporter_test.go
We need to flush metrics before replacing the exporters and also before shutting down the processes. This PR adds a public func FlushExporter and calls it when replacing exporters. This func will also be called in serving repo when the processed are shutting down.
=> Add support to flush the metrics exporter

reconciler/testing/table.go
Currently we're collecting and printing extra objects
as VerbActions, which of course is not what's extra, the extra is the
object wrapped around them. So print that insted.
/cc @mattmoor
=> Fix the display in the table tests.

reconciler/testing/table.go
This PR enables `Fields` validation on delete actions. I ran into this while writing tests in eventing.
cc @mattmoor @vaikas-google
=> Enable fields validation on delete actions

controller/controller.go, controller/controller_test.go
This is needed for the positive handoff, so that we can enqueue
the KPA after we received the positive answer from the activator
but still want to have buffer time to make sure the network
changes propagate everywhere.
/cc @mattmoor
=> Expose the EnqueueKeyAfter function on the controller

controller/controller.go, controller/controller_test.go
This will help to hide the key formatting altogether in the reconciler code.
/cc @mattmoor
=> add addafter method that permits enqueueing the objects themselves

configmap/informed_watcher.go, configmap/informed_watcher_test.go, configmap/manual_watcher.go, configmap/manual_watcher_test.go, configmap/static_watcher_test.go, configmap/store.go, configmap/watcher.go
Fixes: #412 
- Extend the existing `configmap.InformedWatcher` to use code provided defaults if the real ConfigMap does not exist.
- Existing usage will not require any changes. All new functionality is strictly opt-in.
=> Defaulting watcher

controller/controller.go, controller/controller_test.go
Also adds a method for tracker leases, which should be a multiple of the resync period.
This is broken off of #423 (and friends)
=> Add methods for attaching resync duration to context.

logging/config.go, metrics/config.go
This also adds a way to fetch the metrics "domain" following a similar pattern to `system.Namespace()`.
=> Share the configmap name logic for Logging and Metrics.

controller/controller.go, controller/controller_test.go
In serving we have `reconciler.Handler` that wraps a handler function
(e.g. `Enqueue`) in the `cache.ResourceEventHandlerFuncs`.  This pattern
was becoming pervasive, so this simpler handler dramatically reduced our
boilerplate.
=> This upstreams a useful helper from serving.

metrics/config.go, metrics/testing/config.go
This mirrors what we do for `system.Namespace()` today.
=> Add a testing package to setup metrics.Domain()

test/helpers/data.go, test/helpers/data_test.go
These two functions `MakeK8sNamePrefix` and `GetBaseFuncName` can be used for both `Serving` and `Eventing` E2E test, so move them here for sharing and simplicity.
=> Move common helper functions to pkg test

controller/controller.go, controller/controller_test.go, controller/stats_reporter.go
A while back we added a "StatsReporter" argument to `controller.NewImpl`,
but in serving every callsite of this is passing:
```
controller.NewImpl(r, logger, "my-string", MustNewStatsReporter("my-string", logger))
```
Where `MustNewStatsReporter` is just a form of knative/pkg's `controller.NewStatsReporter`
that logs fatally when an error is returned.  It is notable that Serving's logic has been
duplicated to both Build and Eventing.
There are a handful of changes here:
1. Move MustNewStatsReporter into knative/pkg
2. Expose the current interface as NewImplWithStats
3. Drop the StatsReporter from NewImpl and default to `MustNewStatsReporter()`
This is a breaking change for downstream repositories, but should make their callsites universally simpler.
/hold
I am going to stage this change …
=> Simplify the default controller.Impl constructor.

reconciler/testing/table.go
Without this fix you can't expect unstructured.Unstructured object creations which are needed for some duck related stuff.
=> change metav1.Object to runtime.Object so we can test moar objects

logging/config.go, logging/config_test.go
Logging config parses all components, rather than just a list passed in.
The current API exposed before this change is easy to get wrong. For example, knative/serving's cmd/controller/main.go doesn't pass in the components list, so dynamic updates never occur.
=> Logging config parses all components, rather than just a list passed in.

hack/update-deps.sh
This form should be more hospitable to running things to auto-update `knative/test-infra`.
I canaried this change in `knative/sample-controller`, and was able to produce: https://github.com/knative/sample-controller/pull/11
=> Make a small adjustment to hack/update-deps.sh

test/helpers/name.go, test/logstream/doc.go, test/logstream/interface.go, test/logstream/kubelogs.go, test/logstream/null.go
This also upstreams the utility for generating test resource names upon which it builds.
/hold
@ImJasonH @bobcatfish @vdemeester  This is probably useful for tekton as well.
@n3wscott This is probably interesting for eventing.
=> Upstream the logstream package from knative/serving.

injection/informers/kubeinformers/rbacv1/role/fake/fake.go, injection/informers/kubeinformers/rbacv1/role/fake/fake_test.go, injection/informers/kubeinformers/rbacv1/role/role.go, injection/informers/kubeinformers/rbacv1/role/role_test.go
Adds injection for rbacv1.role; code adapted from rolebinding which was pre-existing.
=> Add injection for rbacv1.role

metrics/gcp_metadata.go
Use cluster-location GCP metadata as the location value so that `location` will be region for regional clusters and zone for zonal clusters.
=> Use cluster-location GCP metadata as the location value

configmap/store.go, configmap/testing/configmap.go
This useful constant currently lives in a testing package, which leads to production code importing test packages. That feels kinda awkward.
=> Move ExampleKey constant to 'official' package.

test/logstream/kubelogs.go
- Level is very useful to spot errors at a glance.
- Time is very helpful to be able to order the statements and notice time gaps.
- Key helps identifying which ressource is being reconciled (could be a child resource).
/assign @mattmoor 
Let's discuss here if this is what we want/need for now. Just printing time without ordering things is not ideal, but maybe a good first step?
=> Enrich the logs streamed in tests with useful information.

tracker/enqueue_test.go
Stop using `t.Run` to segment things, since they aren't truly independent tests.
Use a longer lease/sleep as I have concerns that slow execution may be a part of the flakiness here.
=> Refactor the tracker testing.

test/logstream/kubelogs.go
In our structured logging we use `logger.Errorw(..., zap.Error(err))` to log errors in a structured way. As such, they are not part of the actual log message. They are however of utmost importance when debugging issues so this adds `err={ERROR}` to the logline if the error key is present and not empty.
=> Add 'error' field to extracted logs, if available.

apis/interfaces.go, apis/user_info.go, testing/resource.go, webhook/helper_test.go, webhook/user_info.go, webhook/user_info_test.go, webhook/webhook.go, webhook/webhook_integration_test.go, webhook/webhook_test.go
Fixes https://github.com/knative/pkg/issues/457
Moving the user annotation logic done in Knative eventing in https://github.com/knative/eventing/pull/1293 to Knative `pkg`.
Once these changes are merged, the only thing to do at Knative modules is making the resources implement `HasSpec` interface to get them annotated with `abc.knative.dev/creator` and `abc.knative.dev/updater` annotations. See the reason for `HasSpec` interface here: https://github.com/knative/pkg/pull/467#pullrequestreview-250415818
~~I will adapt the tests after I get a quick feedback on the direction.~~
Tests are also adapted.
=> #457 Duck type user annotation logic

injection/informers/kubeinformers/corev1/limitrange/fake/fake.go, injection/informers/kubeinformers/corev1/limitrange/fake/fake_test.go, injection/informers/kubeinformers/corev1/limitrange/limitrange.go, injection/informers/kubeinformers/corev1/limitrange/limitrange_test.go, injection/informers/kubeinformers/corev1/resourcequota/fake/fake.go, injection/informers/kubeinformers/corev1/resourcequota/fake/fake_test.go, injection/informers/kubeinformers/corev1/resourcequota/resourcequota.go, injection/informers/kubeinformers/corev1/resourcequota/resourcequota_test.go
These informers are missing from the builtin set and are necessary from some of the controllers we're building for `kf`. Since they're native to K8s we'd like to contribute them upstream so the set becomes more complete.
=> added limitrange and resourcequota informers

Gopkg.lock, Gopkg.toml, vendor/k8s.io/client-go/discovery/cached_discovery.go, vendor/k8s.io/client-go/discovery/round_tripper.go, vendor/k8s.io/client-go/rest/transport.go, vendor/k8s.io/client-go/tools/cache/reflector.go, vendor/k8s.io/client-go/tools/clientcmd/client_config.go
In knative/serving#4588, the Kubernetes dependency was updated to 1.12.9. This PR puts `pkg` on the same version.
=> Upgrade kubernetes-1.12.6 -> kubernetes-1.12.9

metrics/metricstest/metricstest.go, metrics/record.go, metrics/record_test.go, webhook/stats_reporter.go, webhook/stats_reporter_test.go, webhook/webhook.go, webhook/webhook_integration_test.go, webhook/webhook_test.go
Metrics added:
- "request_count": the number of AdmissionReview requests the webhook received and responded to (invalid requests are ignored)
- "request_latencies": the time in ms it took from receiving the request to sending the response
Other:
- Refactor reused metrics testing code into "metricstest" package that can be shared
See https://github.com/knative/serving/issues/1279
=> Add metrics to webhook package

webhook/webhook.go, webhook/webhook_test.go
Fixes #517 
Also add constructors for consumers to use.
=> Add check for nil StatsReporter in webhook package

webhook/user_info.go, webhook/user_info_test.go, webhook/webhook_test.go
Both eventing and serving curretly use lastModifier. Nothing seems to
implement the pkg 'HasSpec' interface yet so this should be a safe
change. This brings the annotation in-line with currentb behavior
Fixes #511
=> Change 'updater' to 'lastModifier' in webhook

apis/condition_types.go, apis/duck/v1beta1/status_types.go, apis/volatile_time.go
Since we want to create openapi spec for [Kubeflow KFServing](https://github.com/kubeflow/kfserving/pull/218) that depends on knative, but no "+k8s:openapi-gen=true" comments in the knative structs so that the openapi-gen will not load the knative structs. 
The PR is going to add "// +k8s:openapi-gen=true" comments for some knative structs. Thanks.
=> add openapi-gen=true for some structs

kmp/diff_test.go, kmp/reporters.go, kmp/reporters_test.go
Fixed knative/serving#4655
* Both are invalid throw an error
* If x is invalid and y is valid, add '+' prefix and no '-'
* If x is valid and y is invalid, add '-' prefix and not '+'
=> Improve kmp.ShortDiff when one object is invalid

Gopkg.lock, Gopkg.toml
License is present in the package now
=> Move rogpeppe/go-internal to modern version

kmeta/ownerrefable_accessor.go, kmeta/ownerrefable_accessor_test.go
This PR adds a new type `OwnerRefableAccessor` to kmeta. `OwnerRefableAccessor` is a combination of `OwnerRefable` and `Accessor`.
I plan to use `OwnerRefableAccessor` to replace `IngressAccessor` in https://github.com/knative/serving/blob/master/pkg/reconciler/ingress/resources/secret.go#L50 to make this file more reusable.
=> Add OwnerRefableAccessor into kmeta

apis/condition_set.go, apis/condition_set_impl_test.go
This implements ClearCondition to remove a non terminal condition that matches
the condition type. 
Related: https://github.com/kubeflow/kfserving/pull/253
=> Implement ClearCondition for ConditionManager

apis/field_error_test.go
Adding a nil error to a FieldError should be a NOP and there was no test for it. The implementation is already correct; this just adds a test for it.
=> Test for FieldError.Also(nil)

apis/metadata_validation.go, apis/metadata_validation_test.go, webhook/user_info.go
Fixes https://github.com/knative/serving/issues/4648
`ValidateCreatorAndModifier` function will be used by all the CRD's which will be created by user like
Service, Configuration, Route to validate `/creator` and `/lastModifier` annotation
/assign @markusthoemmes @dgerd
=> Add validation for creator and lastModifier annotation

configmap/store.go
Now we just print a struct, which is unparseable.
With this change in hand each field will have a name.
=> This prints better log when CM is loaded.

injection/sharedmain/main.go
This makes it possible to run our controllers locally which can be super handy for quick development cycles.
=> Read the logging configmap via API, not from the file system.

kmeta/names.go, kmeta/names_test.go
currently if the suffix is longer than 31 characters the function would panic.
This fixes that by adding additional checks and trimming. Plus in this case
it will hash the whole string, to ensure uniqueness.
=> Fix the panics in the naming functions.

testutils/OWNERS, testutils/README.md, testutils/clustermanager/boskos/boskos.go, testutils/clustermanager/client.go, testutils/clustermanager/doc.go, testutils/clustermanager/gke.go, testutils/common/common.go
This is part of test infra 2.0 work, aiming to provide a lib for managing life cycles of k8s clusters for testing purpose. This PR includes a skeleton lib, once this is merged, all other functionalities(Marked as TODOs) can be implemented and reviewed in parallel.
Part of: https://github.com/knative/test-infra/issues/1186
/cc @adrcunha 
/cc @srinivashegde86
=> Test Infra 2.0: Add cluster management lib skeleton

testutils/clustermanager/client.go, testutils/clustermanager/gke.go, testutils/clustermanager/gke_test.go, testutils/clustermanager/util.go, testutils/clustermanager/util_test.go
Add logic of checking for local environment, i.e. uses existing cluster if kubeconfig is set, uses existing gcp project if gcloud is set.
Part of: https://github.com/knative/test-infra/issues/1186
/cc @adrcunha
=> Add cluster creation logic for local users

apis/url.go
If I call `apis.ParseURL(...)` and it returns a nil error, I should be able to use the resulting `apis.URL`.
It returns a nil error and a nil URL if passed the empty string, resulting in nil ptr errors.
I've changed the documentation comment to explain how the API differs from the `net/url.Parse` method so that developers are not surprised by this behavior.
@mattmoor
=> Document ParseURL non-conformance with the net/url.Parse api

testutils/clustermanager/gke.go, testutils/clustermanager/gke_test.go, testutils/clustermanager/util.go, testutils/clustermanager/util_test.go, testutils/common/common.go, testutils/common/common_test.go
Turns out to be `StandardExec` needs to be mocked in more than one place for unit testing, move it out of `GKECluster` struct to make it simpler. Also, add more common functions as well as unit tests
/cc @adrcunha
=> clustermanager: move common helpers and add more helpers

configmap/testing/configmap.go
=> Fix licence to have spaces and comment to match the function

configmap/store.go, configmap/store_test.go
I read this code by accident and was wondering why we do all of the reflection shenanigans when the Constructor functions are in fact fairly strongly typed. Maybe I'm missing something and this is bogus though.
=> Remove reflection from generic store code.

tracing/config/tracing.go, tracing/config/tracing_test.go, tracing/http_test.go, tracing/opencensus.go, tracing/opencensus_test.go, tracing/sampler_test.go, tracing/testing/zipkin.go, tracing/zipkin.go, tracing/zipkin_test.go
This makes an assortment of changes to support the use of non-Zipkin tracing backends for publishing traces from system components based on config-tracing.
The changes to the config are modeled after config-observability, which already has support for prometheus and stackdriver backends for metrics.
/hold
This is on hold until I can properly stage downstream changes to serving and eventing.
=> Expand the tracing package to support stackdriver.

configmap/store.go, configmap/store_test.go
Reverts knative/pkg#583
Go lacks return type covariance, so `func(*ConfigMap) (T, error)` unfortunately does not implement `func(*ConfigMap) (interface{}, error)`.
This breaks (at least) serving.
cc @dprotaso
=> Revert "Remove reflection from generic store code."

OWNERS_ALIASES
Authored the store thing here https://github.com/knative/serving/pull/2009
Previous clean up of the watchers https://github.com/knative/pkg/pull/59
=> Add dprotaso to the configmap-approvers

apis/url.go, apis/url_test.go
There was an issue when trying to marshal the addressable struct if the url was an empty string. We do not hit this today because addressable address struct has only one thing and if the url is not set, we omit the outer object.
=> Correct a unmarshal error for non pointer members of apis.URL if empty string.

controller/controller.go, controller/controller_test.go, controller/helper.go, controller/helper_test.go
This consolidates the logic for how we do GlobalResyncs in a few ways:
1. Remove SendGlobalUpdates and replace it with FilteredGlobalResync.
2. Have GlobalResync go through the FilteredGlobalResync with a tautological predicate.
3. Change the way we enqueue things during a global resync to avoid flooding the system
by using EnqueueAfter and wait.Jitter to stagger how things are queued.
The background for this is that when I started to benchmark reconciliation of a large
number of resources we'd see random large stalls like [this](https://mako.dev/run?run_key=4882560844824576&~dl=1&~cl=1&~rl=1&~rvl=1&~il=1&~sksl=1&~pal=1)
fairly consistently.  Looking at the logs, these stalls coincide with incredibly deep
work queues due to global resyncs triggers by configmap notifications. When I …
=> Rework how we GlobalResync.

test/ingress/ingress.go, test/spoof/spoof.go
There is no reason to use a string pointer here.
It makes the calling code weird since string pointers are pretty much never used in Go.
=> Replace string pointer with plain string

OWNERS_ALIASES, reconciler/OWNERS
Extend reconciler and controller owners with engineers mostly working on the reconcilers
/cc @dgerd
=> Extend reconciler and controller owners with engineers mostly working on the reconcilers

reconciler/testing/table.go
Currently the table tests do not annotate the context logger with the key
which means we puts lots of unnecessary logging in the reconcilers to log the key that is being reconciled.
So this fixes that.
Also precreates some containers to the needed size.
=> Improve the logging situation in table tests

codegen/cmd/injection-gen/generators/factory.go, codegen/cmd/injection-gen/generators/fakefactory.go, injection/context.go, injection/context_test.go, injection/doc.go, injection/informers/apiextinformers/factory/factory.go, injection/informers/apiextinformers/factory/factory_test.go, injection/informers/apiextinformers/factory/fake/fake.go, injection/informers/apiextinformers/factory/fake/fake_test.go, injection/informers/kubeinformers/factory/factory.go, injection/informers/kubeinformers/factory/factory_test.go, injection/informers/kubeinformers/factory/fake/fake.go, injection/informers/kubeinformers/factory/fake/fake_test.go
_I've imported it into serving [here](https://github.com/knative/serving/compare/master...mattmoor:namespace-scoping?expand=1) to verify the code generator works._
Sometimes controller authors want to restrict the scope of a controller to a single namespace, which can dramatically reduce the level of privilege the controller needs from cluster to namespace scope.  This adds some logic that enables folks building around the injection-based setup to plumb through a namespace, which will be supplied to the various `informers.NewSharedInformerWithOptions()` calls via `informers.WithNamespace()`.
It would be nice to have a way to attach more generalized `informers.SharedInformerOption`, but unfortunately each of these types seem bound to particular code-generation, so I went with this more …
=> Add the ability to scope informers to a namespace with injection.

test/clients.go, test/request.go, test/spoof/spoof.go
Fixes #621.
Currently, Spoofing is done at the request layer, meaning `http.Request.Host` and `http.Request.URL.Host` are modified. This doesn't work with HTTPS because `http.Request.URL.Host` must match the TLS certificate Common Name or Subject Alternative Names, and therefore cannot be tempered. The solution is to spoof at the DNS resolution.
This also contains a minor change to accept a custom http.Transport that will be used in HTTPS E2E tests.
=> Spoof at the Resolver layer, not the Request layer

test/request.go
This should surface better info from the 502s we've been seeing (I hope).
=> Report the status text in addition to the code on failure.

reconciler/testing/context.go
This will help tests to terminate their informer loops.
Otherwise they don't and that's no good, since we get panics and race conditions.
=>  Add SetupFakeContextWithCancel so that context can be canceled. 

websocket/connection.go
For example, when serving activator fails to ping autoscaler, it fails
with `Failed to send ping message` message. However, it does not print
target peer's name so it is difficult to debug.
This patch changes to print the target name.
BEFORE:
```
{"level":"error","ts":"2019-09-04T06:13:07.543Z","logger":"activator","caller":"websocket/connection.go:158","msg":"Failed to send ping message","commit":"c2b0a5e","knative.dev/controller":"activator","error":"connection has not yet been established","stacktrace":"knative.dev/serving/vendor/knative.dev/pkg/websocket.NewDurableConnection.func3\n\t/home/knakayam/.go/src/knative.dev/serving/vendor/knative.dev/pkg/websocket/connection.go:158"}
```
AFTER:
```
{"level":"error","ts":"2019-09-04T06:23:13.689Z","logger":"activator","caller":"websocket/conn …
```
=> Print target name when failed to ping

test/logstream/kubelogs.go
If the source is activator or autoscaler, we'd just print  in the logstream
making it not very useful for searching.
Replace it with call site, if the controller is not set all.
=> Fix the problem in kubelogs when source is not controller.

test/webhook-apicoverage/coveragecalculator/calculator.go, test/webhook-apicoverage/coveragecalculator/coveragedata.go, test/webhook-apicoverage/tools/tools.go, test/webhook-apicoverage/view/aggregate_coverage.html, test/webhook-apicoverage/view/html_display.go, test/webhook-apicoverage/view/type_coverage.html, test/webhook-apicoverage/webhook/apicoverage_recorder.go
This change changes webhook apicoverage HTML display to use to templates
moving away from current approach of using string buffers
This change does not take display-rules into account as its not being
used at the moment. When there is a use-case the template hanlding needs
to be modified accordingly.
=> test/webhook-apicoverage: Changing html display to use go templates

tracing/http.go, tracing/http_test.go
Add tracing.HTTPSpanMiddlewareIgnoringPaths which will turn off tracing for the specified paths.
This is intended to allow us to ignore automated requests, such as liveness and readiness checks.
=> tracing.HTTPSpanMiddlewareIgnoringPaths

apis/duck/v1/addressable_types.go, apis/duck/v1/addressable_types_test.go, apis/duck/v1alpha1/addressable_types.go, apis/duck/v1alpha1/addressable_types_test.go, apis/duck/v1beta1/addressable_types.go, apis/duck/v1beta1/addressable_types_test.go
v1alpha1 embeds v1beta1 which makes them easily convertible. However, we
cannot embed both v1beta1 and v1 into v1alpha1 easily. Updating to just
use v1 in v1alpha1 is breaking so this change implements converters
to enable moving between v1 and v1beta1/v1alpha1 without having to
implement the logic in every client needing to convert.
=> Add Addressable type converters to v1 Addressable

apis/testing/v1/conditions.go, apis/testing/v1beta1/conditions.go
This version the condition testing helper functions so that they can be used for either duck v1 Status type or v1beta1 duck Status type.
=> Version condition testing helper functions

tracing/opencensus.go, tracing/opencensus_test.go, tracing/zipkin.go
ConfigOptions return an error, so we can react to things failing, rather than only reading it in the logs.
=> ConfigOptions return an error

testutils/clustermanager/client.go, testutils/clustermanager/gke.go, testutils/clustermanager/gke_test.go
Previous implementation waits on cluster creation operations indirectly by querying cluster status, which might not work all the time. Switch to wait on `*container.Operation` returned by cluster creation method instead, this should be much more reliable. Also, the same wait mechanism can be reused by `delete` and any other future operations.
By the way introduce protection for protected projects and cluster as currently supported
/cc @adrcunha
=> Cluster operations wait for *Operation object directly

apis/duck/patch.go, apis/duck/patch_test.go
We have been maintaining a copy of this helper function in the Knative
Serving tests. Moving it here and adding tests so it can be used more
generally. The function allows creating a []byte patch without having to
check two levels of error conditions.
=> Move duck patch helper function from Knative Serving to pkg

controller/stats_reporter.go, metrics/metrics.go, metrics/metricstest/metricstest.go, metrics/record.go, metrics/record_test.go, metrics/workqueue.go, metrics/workqueue_test.go
The kubernetes workqueue provides a facility for collecting metrics by registering a `workqueue.MetricsProvider` via `workqueue.SetProvider`.
This change implements that interface to expose the workqueue metrics into opencensus.
This is loosely based on some work started by @grantr [here](https://github.com/kubernetes-sigs/controller-runtime/compare/master...grantr:opencensus-replace#diff-bb94124aff8d568cb4e82854c7d44fd1)
Fixes: https://github.com/knative/pkg/issues/522
=> Implement workqueue.MetricsProvider

Gopkg.lock, controller/stats_reporter.go, metrics/client.go, metrics/client_test.go, metrics/metrics.go, metrics/reflector.go, metrics/reflector_test.go, metrics/workqueue.go
This adds logic to hook into two other metric systems:
1. `cache.SetReflectorMetricsProvider`, which doesn't seem hooked up in Kubernetes yet, but would theoretically give us metrics about the mechanisms underpinning informers.
2. `metrics.Register`, which hooks us into the rest client infrastructure to give us metrics about low-level API server calls.
Fixes: https://github.com/knative/pkg/issues/679
Fixes: https://github.com/knative/pkg/issues/680
This is WIP until https://github.com/knative/pkg/pull/678 lands.
=> Hook into two other Kubernetes metric subsystems.

Gopkg.lock, Gopkg.toml, testutils/clustermanager/gke.go, testutils/clustermanager/gke_test.go, vendor/google.golang.org/api/container/v1beta1/container-gen.go
Some options are only available in GKE SDK v1beta1, like Istio Addon which is required for other repos setting up serving. So switch to use v1beta1
/cc @adrcunha 
/cc @mattmoor
=> Cluster creation lib uses GKE SDK v1beta1 instead of v1

testutils/clustermanager/doc.go, testutils/clustermanager/example_test.go, testutils/clustermanager/gke.go, testutils/clustermanager/gke_test.go
Initially planned to have `SetAddon` as an exported function to be used as an option, which didn't work as it took far more than 5 minutes to get `Istio` addon installed on an existing cluster. And when installed as part of cluster creation it doesn't seem to add much time on top of cluster creation time, so switch to have addons as a param to cluster creation.
This PR also does:
- Update doc
- Consolidate unit tests
- Prettify unit test error message with cmp.Diff
/cc @adrcunha
=> Cluster management lib: create cluster with addon

reconciler/testing/generate_name_reactor.go, reconciler/testing/generate_name_reactor_test.go
The 1.14 K8s test libs introduce changes that broke how we were testing this, but it still works in the cases we care about, so this adjusts the test to more accurately test the reactor in the way we actually care about.
=> Change how we test the generateName reactor.

test/zipkin/util.go
Remove CheckZipkinPortAvailability.
The check did not work well on Macs, where calling JSONTrace would fail immediately because the check failed.
---
The problem was found and fixed by @Fredy-Z, I am merely the one merging it.
=> Remove CheckZipkinPortAvailability.

testutils/clustermanager/boskos/boskos.go, testutils/clustermanager/boskos/boskos_test.go, testutils/clustermanager/boskos/fake/fake.go, testutils/clustermanager/example_test.go, testutils/clustermanager/gke.go, testutils/clustermanager/gke_test.go, testutils/clustermanager/util.go, testutils/clustermanager/util_test.go, testutils/common/common.go, testutils/common/common_test.go
Autoscaling is enabled by default for all e2e test in knative, adding this function as default. By the way fixed a bug in existing project set by `gcloud`, as well as some cleanups of switching from `nil ==` style to `== nil` style.
/cc @adrcunha 
Part of: https://github.com/knative/test-infra/issues/1186
=> Cluster management lib: Add autoscaling to cluster creation

apis/url.go, test/request.go
Fixes https://github.com/knative/serving/issues/5419 - Part I
See corresponding `knative.dev/serving` change: https://github.com/knative/serving/pull/5503
/hold
=> Use *url.URL instead of string in request.go

version/version.go, version/version_test.go
This will be the lowest supported version of upstream Kubernetes, once 1.16 has cut.
Fixes: https://github.com/knative/serving/issues/5180
/hold
Even though the other repos have pinned to `release-0.9` I'd like to keep a lid on this until the cut's actually done in case we decide to roll-up.
=> Bump the minimum Kubernetes version to 1.14.x

signals/signal_posix.go
By default raised SIGPIPE signal will cause the program to exit immediately[1]
and bypass any shutdown logic.
Add syscall.SIGPIPE to the signals we get notified to disable this behavior.
[1] https://golang.org/pkg/os/signal/#hdr-SIGPIPE
=> Add SIGPIPE signal handler to the signals package

configmap/static_watcher.go
Last user, in `knative.dev` was the eventing repo.
That is cleaned up here:
https://github.com/knative/eventing/pull/1927
/hold
=> Remove deprecated NewFixedWatcher

controller/controller.go, controller/controller_test.go
As per title, this is an attempt to introduce a structured key to be used by our reconcilers to remove unnecessary boilerplate.
=> Plumb through a structured key, keep current behavior.

resolver/addressable_resolver.go, resolver/addressable_resolver_test.go, tracker/enqueue.go, tracker/enqueue_test.go
This is a followup for #703. We didn't actually keep current behavior correctly so this is fixing forward what I broke.
Related to https://github.com/knative/serving/pull/5620 and https://github.com/knative/eventing/pull/1942
=> Adjust tracker to take structured keys as well.

signals/signal_posix.go
This reverts commit 1fb9a433083f3e74ff9de88a5ff6bd37ab7bd709.
As per the doc (https://golang.org/pkg/os/signal/#hdr-SIGPIPE)
> If the program has not called Notify to receive SIGPIPE signals, then the behavior depends on the file descriptor number. A write to a broken pipe on file descriptors 1 or 2 (standard output or standard error) will cause the program to exit with a SIGPIPE signal. A write to a broken pipe on some other file descriptor will take no action on the SIGPIPE signal, and the write will fail with an EPIPE error. 
> If the program has called Notify to receive SIGPIPE signals, the file descriptor number does not matter. The SIGPIPE signal will be delivered to the Notify channel, and the write will fail with an EPIPE error. 
>  This means that, by default, command line …
=> Revert "Add SIGPIPE signal handler to the signals package (#689)"

injection/sharedmain/main.go, metrics/memstats.go, metrics/memstats_test.go
This exposes metrics for the properties available through [here](https://godoc.org/runtime#MemStats) so that we can get some better visibility into things like GC pressure.
Here's an example of Prometheus showing `HeapAlloc` for our controller process:
=> Expose Go memstats as metrics.

configmap/filter.go, configmap/store.go, webhook/config_validation_controller.go, webhook/config_validation_controller_test.go, webhook/resource_admission_controller.go, webhook/resource_admission_controller_test.go, webhook/webhook.go, webhook/webhook_integration_test.go, webhook/webhook_test.go
This PR implements the proposal discussed in https://github.com/knative/serving/issues/4610
It adds a validating webhook on ConfigMaps in a knative component namespace.
=> add config validation as admission controller

testutils/clustermanager/gke.go
Two minor changes:
1. Remove `return err` as VS Code shows it's unreachable
2. Exchange the compare expression, since it looks more natural to put the variable `i` at the left.
/cc @chaodaiG
=> Minor changes to gke.go

test/spoof/spoof.go
My original implementation logs the original address and the spoofed address at each resolution but these values can't change and pollute the logs in E2E tests.
=> Log spoofing details only once

testutils/clustermanager/gke.go
Cluster creation function returns cluster struct fetched before applying autoscaling, correct it in this PR and add log describing cluster to be created
/cc @adrcunha
=> Fix cluster creation lib return not up-to-date cluster issue

testutils/clustermanager/example_test.go, testutils/clustermanager/gke.go, testutils/clustermanager/gke_test.go
Allow custom cluster name to be used for cluster creation. 
Cluster management lib switch to accept `GKERequst` struct as input rather than more than 5 positional string + int64 + []string params.
Fixes https://github.com/knative/test-infra/issues/1393
/cc @adrcunha 
/cc @Fredy-Z
=> Cluster management lib: allow custom cluster name

testutils/clustermanager/gke.go
GKE SDK creates cluster with "stable" version by default instead of "latest": https://cloud.google.com/kubernetes-engine/docs/release-notes, explicitly set "latest" to get latest cluster version
/cc @adrcunha
=> Explictly set GKE cluster version to 'latest'

Gopkg.lock, vendor/github.com/openzipkin/zipkin-go/noop.go, vendor/github.com/openzipkin/zipkin-go/reporter/http/http.go, vendor/github.com/openzipkin/zipkin-go/span.go
Update zipkin-go to v0.2.2 to pickup recent fix of unbounded goroutine
creation when the zipkin backend is down.
See https://github.com/openzipkin/zipkin-go/pull/146 for more details.
=> Update zipkin-go to v0.2.2

test/mako/stub-sidecar/main.go
Without this, calling the ShutdownMicroservice API twice will cause a panic due to closing a closed channel.
Related to #694
/cc @slinkydeveloper @antoineco
=> Close the stop channel only once

Gopkg.toml
The build fails against more recent versions of this package because `stackdriver.Options.GetMonitoredResource` was removed. That struct attribute is used in metrics/stackdriver_exporter.go. Relevant [commit](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/commit/b0cbe77587ebe726c8dc9d4d00101c28c7ac2527). 
I don't have a good sense for what follow-on work should be done to reach compatibility with the lastest opencensus exporter, but would be happy to open an issue if this should be tracked.
=> Pinning opencensus stackdriver exporter in Gopkg.toml to avoid build breakage

test/spoof/spoof.go
`spoof.New` requires many parameters that we don't necessarily need.
Make `Logf` public for `SpoofingClient` so that we can initialize the struct with its definition, and use it in non-e2e tests.
/cc @adrcunha
=> Make Logf public for SpoofingClient struct

test/mako/stub-sidecar/main.go
This should mitigate the #694
/assign grantr
/area test-and-release
=> Increase maxRecvMsgSize in grpc server of mako-stub

testutils/clustermanager/client.go, testutils/clustermanager/example_test.go, testutils/clustermanager/gke.go, testutils/clustermanager/gke_test.go
`initialize` is a prerequisite for calling `Acquired` and `Delete`, which is not supposed to serve any other purpose any way, so make it private and call it internally instead of exposing it to save one step in using this lib. By the way also allows:
- Skip cluster creation: which can be used for acquiring cluster from environment
- Force cluster cleanup: there is a `NeedsCleanup` switch, which was implemented to be true only if the cluster is created by the same client. However this is never true in CI since cluster creation and deletion will be invoked by separate processes. Adding this additional flag so that we can enforce cleanup
Part of: https://github.com/knative/test-infra/issues/1186
/cc @adrcunha
=> Clustermanager lib: don't expose initialize, calling it internally only, also allow skip cluster creation and force cleanup options

test/mako/alerter/alerter.go, test/mako/alerter/github/issue.go, test/mako/config/configmap.go, test/mako/config/environment.go, test/mako/sidecar.go
Make `repository` to be optional in `config-mako` configmap, since it's only required for Github operations. This PR is unblocking `eventing` since they don't want setting up alert for now.
/cc @adrcunha 
/cc @chaodaiG 
/cc @grantr
=> Make repository optional in config-mako

test/mako/sidecar.go
The secret path should be the same as the `mountPath` in benchmark jobs - https://github.com/knative/serving/blob/e2791cbda767191e089a7a0ca8eae8ec6cd2ecd3/test/performance/dataplane-probe/dataplane-probe.yaml#L283.
This PR changes it to be the correct one - `var/secrets` -> `var/secret`, also make them constants at the top of the file.
/cc @adrcunha
=> Fix the token path for perf tests

test/spoof/error_checks.go, test/spoof/error_checks_test.go, test/spoof/spoof.go
Some E2E are flaky because we do not handle the transient `connection reset by peer` errors.
Examples: [[1]](https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-serving-istio-1.3-mesh/1179951947675865088), [[2]](https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-serving-istio-1.2-mesh/1179919241718009856), [[3]](https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-serving-istio-1.2-mesh/1179979633756475392).
These errors are expected and should simply be retried.
=> Handle and retry 'connection reset by peer' errors

test/mako/sidecar.go
Temporary fixes issue #721 in order to unblock perf test in eventing, by using a new makoSetup `SetupWithBenchmarkConfig` to allow pass benchmark id.
=> Allow passing benchmark ids to mako setup

test/mako/alerter/alerter.go, test/mako/alerter/github/issue.go, test/mako/alerter/github/issue_test.go, test/mako/sidecar.go
Improve mako alerter:
1. Edit the old comment if there is an existed Github issue
2. Code clean up
=> Improve Github alerter for Mako

testutils/gke/client.go, testutils/gke/fake/client.go
For performance test cluster lifecycle management, we need to list all clusters under a project. Add the support in our library.
/cc @chaodaiG
=> Support listing all clusters under a project'

websocket/connection.go
1. %q are very annoying when actually trying to read logs and the address is obvious (and zap quotes them)
2. there's no reason to have external error (and we were swallowing the timeout error, should it happen)
/assign @evankanderson @markusthoemmes
=> Clean up websocket code a bit.

OWNERS_ALIASES, websocket/OWNERS
Alias it to the controller approvers which seem more or less reasonable
/assign @mattmoor @vaikas-google
=> Add OWNERS to the websocket which was missing before.

testutils/clustermanager/example_test.go, testutils/clustermanager/gke.go, testutils/clustermanager/gke_test.go, testutils/gke/fake/client.go
Discovered a few problems in cluster manager lib while working on integrating it with test-infra e2e tests in this PR: https://github.com/knative/test-infra/pull/1449
1. When running in Prow, it started with `gcloud` configured to point to `knative-tests` project, which caused this lib fail since it's protected
1. When running in Prow, `initialize` acquires a Boskos project every time it runs. This is problematic since it's invoked by both `Acquire` and `Delete`
1. `initialize` is doing extra setup that's not needed by `Delete` function
Solutions:
1. Blindly use Boskos to acquire project when running in Prow and needs to create Cluster
1. Move Boskos acquisition from `initialize` to `Acquire`
1. Remove `initialize`, and let `Acquire` and `Delete` invoke `checkEnvironment` instead
This …
=> Modify cluster manager lib to make it work better with Prow

OWNERS_ALIASES, source/OWNERS, source/doc.go, source/source_labels.go, source/source_labels_test.go
=> Adding common sourceLabels func

test/zipkin/util.go
Helps with knative/eventing#2040.
Changes:
* jsonTrace errors are retried until the timeout.
* jsonTrace json.Unmarshal errors include the string being unmarshaled.
=> jsonTrace errors are retried until the timeout.

testutils/gke/addon.go, testutils/gke/request_test.go
Support adding `HorizontalPodAutoscaling`, `HttpLoadBalancing` and `CloudRun` addons for GKE clusters in the gke lib.
/cc @chaodaiG
=> Add support for new addons for GKE cluster

test/gke/client.go
The parameters defined in functions of an interface should be named, otherwise users will not know which values to provide if calling the function with an interface.
/cc @chaodaiG 
/cc @adrcunha
=> Name the parameters of functions in GKE SDK interface

test/gke/client.go, test/gke/fake/client.go
Since some unit tests use go routines, modify the fake GKE client to be thread-safe.
/cc @chaodaiG
=> Modify GKE fake client to make the operations thread-safe

metrics/config.go, metrics/config_test.go, metrics/exporter.go
Fixes #768 
Lock during entire process of reading ConfigMap "config-observability" and updating Stackdriver exporter.
Also, move functions in config.go that touch variables declared in exporter.go to exporter.go.
=> Fix race condition when updating Stackdriver exporter

logging/config.go, logging/config_test.go
Given a ConfigMap named "config-logging" with the following data:
```yaml
data:
zap-logger-config: { "level": "debug" }
```
The log level of the main component is set to `info` regardless of the value configured in the Zap logger config.
`config.LoggingLevel[name]` returns a default value of `int8(0)` if `name` is not in the `config.LoggingLevel` map. This value corresponds to `zapcore.InfoLevel`.
We must ensure that `name` is actually an element of the map before passing the override value to `config.NewLogger()`. Same thing inside `UpdateLevelFromConfigMap()`. 
- Set the override value to `""` by default, and use an actual log level _only_ if the user explicitly defined a log level for the given component.
- Ensure the atomic level is reset to the global log level when the component log …
=> Do not override log level if component is undefined in logging config

Gopkg.lock, Gopkg.toml, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/resolve.go, vendor/gopkg.in/yaml.v2/scannerc.go
As per title, just to make sure we're not vulnerable to CVE-2019-11253. See kubernetes/kubernetes#83253.
It's unclear if we are even vulnerable against this at all. Doesn't hurt to bump/override the dep though.
```release-note
NONE
```
=> Bump YAML library to latest release

.gitattributes, test/gke/client.go
As we talked in the meeting, now we should enable go test coverage  check for `pkg/test`.
/cc @adrcunha
=> Enable coverage for test code

Gopkg.lock, test/logging/logging.go
As described in https://github.com/knative/pkg/issues/766, `glog` will cause some issues and is not suggested to be used, and all Knative projects are using either zipkin logger or simple `log`.
This PR remove `glog` from test/logging/logging.go.
/cc @grantr 
/cc @adrcunha
=> Remove glog from test/logging

apis/url.go, apis/url_test.go
In particular, this adds:
* Two constructors for common cases, one for HTTP and one for HTTPS URLs
* An `IsEmpty` method to automate the `nil`-or-empty checks
=> Add utility methods for api.URL

testutils/metahelper/client/client.go, testutils/metahelper/client/client_test.go, testutils/metahelper/main.go
Add a testutil that helps with reading/writing `metadata.json`, the file can be read by Prow and displayed in spyglass. This can be used by both go package and from command line. See https://github.com/knative/test-infra/pull/1460 for it's usage
/cc @adrcunha 
/cc @chizhg
=> Add metahelper for reading/writing metadata in Prow

testutils/clustermanager/prow-cluster-operation/README.md, testutils/clustermanager/prow-cluster-operation/actions/create.go, testutils/clustermanager/prow-cluster-operation/actions/delete.go, testutils/clustermanager/prow-cluster-operation/actions/get.go, testutils/clustermanager/prow-cluster-operation/main.go, testutils/clustermanager/prow-cluster-operation/options/options.go
Add a prow-cluster-operation package as a wrapper of clustermanager/e2e-tests package, which can be invoked from command line. See https://github.com/knative/test-infra/pull/1460 for it's usage
For reviewers:
This PR is copied directly from https://github.com/knative/test-infra/pull/1460, the only changes are importing paths updated since `metahelper` was moved to pkg
/cc @adrcunha 
/cc @chizhg
=> Add prow-cluster-operation package

metrics/config_test.go, metrics/metricskey/constants_serving.go, metrics/record_test.go, metrics/stackdriver_exporter_test.go
The internal ones accept pod and container names in order to fix https://github.com/knative/serving/issues/5691
=> Change built-in metrics to use internal ones for activator and revision

metrics/metricstest/metricstest.go
Currently we only check got metrics tags are in the expected tags, but not in reverse. We should verify that got and expected tags are equal.
=> Add metrics tags length verification

apis/v1alpha1/destination.go, apis/v1alpha1/destination_test.go, apis/v1alpha1/zz_generated.deepcopy.go, resolver/addressable_resolver.go, resolver/addressable_resolver_test.go
Regarding discussion of https://github.com/knative/eventing/issues/1918, to avoid the breaking api change for sources, we can add DeprecatedObjectReference in Destination to support backwards compatibility. This is a suggestion change. We have not made a decision yet.
- added DeprecatedObjectReference in Destination to support backwards compatible
- Added unit tests for new business logic
```release-note
This is a suggestion change. We have not made a decision yet. Please don't merge it now.
```
=> add DeprecatedObjectReference in Destination to support backwards compatibility

apis/v1alpha1/destination.go, apis/v1alpha1/destination_test.go
Helps with knative/eventing#1918
- Add Destination.GetRef() to abstract out the ref vs deprecated ref.
=> Add Destination.GetRef() to abstract out the ref vs deprecated ref.

metrics/config.go, metrics/config_test.go, metrics/exporter.go, metrics/exporter_test.go, metrics/gcp_metadata.go, metrics/stackdriver_exporter.go, metrics/stackdriver_exporter_test.go
Add ability to configure Stackdriver client metadata for the metrics package's Stackdriver exporter.
Currently, Stackdriver metrics rely on the Google Compute Engine metadata server, which is only accessible on GCE, to configure the Stackdriver client. This allows sending metrics to Stackdriver on any compute platform.
The new fields are optional and purely additive and do not break existing usage. If omitted, Stackdriver will fall back on Google Application Credentials defaults (https://cloud.google.com/docs/authentication/production).
Configuration required for knative/serving#5777
=> Add field to metrics config for configuring Stackdriver exporter client

webhook/config_validation_controller.go, webhook/config_validation_controller_test.go, webhook/resource_admission_controller.go, webhook/resource_admission_controller_test.go, webhook/webhook.go, webhook/webhook_test.go
This changes the model by which we manage the lifecycle of our
`{mutating,validating}webhookconfiguration`, which previously used an owner ref
from the cluster-scoped configuration to the namespace-scoped Deployment.  The
new model adds an explicit yaml file for the webhook, which omits the fields
filled in by the deployment as it starts.
A few notable elements of this change:
1. Clear out OwnerReferences explicitly (avoids the linked bug),
2. Periodically reruna `Register()` to ensure our webhook exists,
3. Simplified logic around registration (all we need now is update!).
Related: https://github.com/knative/serving/issues/5845
=> Stop using OwnerRefs for webhook config lifecycle

injection/clients/dynamicclient/dynamicclient.go
The current error message gets formatted as `Unable to fetch <nil> from context.`, which is not useful.
`injection-gen` makes the type part of the error string, unformated, so I just did the same here.
=> Log type instead of <nil> in injection panic message

injection/README.md
I stumbled upon a few references to outdated package paths while writing tests for a controller that uses injection and figured it might be useful for future readers to update them.
=> Update outdated package paths in injection usage doc

controller/controller.go, controller/controller_test.go
This is a precursor to reconciling named webhook configurations, and largely a copy of `FilterByNameAndNamespace`.
=> Add FilterByName for cluster-scoped resources.

webhook/helper_test.go, webhook/webhook.go, webhook/webhook_test.go
This is the first of a series of breaking changes that I'll stage and land in the downstream repositories after the 0.10 cuts happen.
=> Eliminate the Namespace config option in favor of system.Namespace.

webhook/config_validation_controller.go, webhook/config_validation_controller_test.go, webhook/resource_admission_controller.go, webhook/resource_admission_controller_deprecated_test.go, webhook/resource_admission_controller_test.go, webhook/webhook.go, webhook/webhook_integration_test.go, webhook/webhook_test.go
This builds on https://github.com/knative/pkg/pull/817 and makes further
breaking changes. The options pertinent to each admission controller are
now passed to their respective constructors, which leads to a cleaner
options struct, and better prepares for greater webhook diversity.
This is WIP until the baseline change merges.
=> Move hook-specific configuration options out of shared options.

webhook/context.go, webhook/helper_test.go, webhook/webhook.go, webhook/webhook_test.go
This now pulls most of its configuration from context, which brings it a step closer to aligning with our `sharedmain` package.
This is WIP until https://github.com/knative/pkg/pull/820 merges.
=> Streamline webhook.New

webhook/webhook.go, webhook/webhook_integration_test.go, webhook/webhook_test.go
We don't use this anywhere in Knative downstream and it adds a bunch of complexity.
=> Remove options to specify ClientAuth.

test/mako/alerter/slack/message.go, test/mako/alerter/slack/message_test.go, test/mako/sidecar.go, test/slackutil/message_read.go
Slack MessageHistory should only return messages sent by the current user.
/cc @vagababov
=> Slack MessageHistory only returns messages sent by the current user

webhook/stats_reporter.go, webhook/stats_reporter_test.go
With this change folks will need to call `webhook.RegisterMetrics()` to register the opencensus view with the metrics for the webhook's StatsReporter.  This is needed to avoid having `sharedmain` crashloop the activator due to linking multiple on-`init()` views that register metrics named `request_latencies`.
In general, I believe that we should move away from registering these views via `init()` and more towards the broader K8s MetricsProvider pattern.
=> Avoid registering webhook metrics with init()

webhook/config_validation_controller_test.go, webhook/resource_admission_controller_test.go, webhook/webhook_integration_test.go
This is no longer necessary now that we have eliminated our usage of OwnerReferences in the webhook.
=> Remove vestigial createDeployment

injection/sharedmain/main.go
With the simplified `webhook.New` signature, this supports detecting when one or more of the controllers we have launched has a `Reconciler` that implements `webhook.AdmissionController` and launching the webhook with this admission controllers registered.
There is still work that needs to be done to refactor the webhooks to follow this shape, but this hopefully starts to paint the picture of where things are headed.
=> Expand sharedmain to support launching our webhook.

Gopkg.lock, test/webhook-apicoverage/webhook/apicoverage_recorder.go, test/webhook-apicoverage/webhook/webhook.go, webhook/README.md, webhook/configmaps/configmaps.go, webhook/configmaps/configmaps_test.go, webhook/configmaps/controller.go, webhook/configmaps/table_test.go, webhook/helper_test.go, webhook/resourcesemantics/controller.go, webhook/resourcesemantics/resourcesemantics.go, webhook/resourcesemantics/resourcesemantics_deprecated_test.go, webhook/resourcesemantics/resourcesemantics_test.go, webhook/resourcesemantics/table_test.go, webhook/resourcesemantics/user_info.go, webhook/resourcesemantics/user_info_test.go, webhook/testing/listers.go, webhook/webhook.go, webhook/webhook_integration_test.go, webhook/webhook_test.go
This is the culmination of a large number of changes to refactor our webhook logic, and adopt a reconciler-based approach to make it resilient to unexected system events (e.g. rogue GCs!).
For more details on how this is consumed, see the new `webhook/README.md`.
Fixes: https://github.com/knative/pkg/issues/782
Closes: https://github.com/knative/pkg/issues/529
Fixes: https://github.com/knative/pkg/issues/450
Related: https://github.com/knative/pkg/issues/141
/hold
... as I stage downstream changes.
=> This refactors our core webhook logic to be reconciler-based.

Gopkg.lock, apis/duck/cached_test.go, cloudevents/event_v01.go, cloudevents/handler_test.go, codegen/cmd/injection-gen/generators/fakeinformer.go, controller/stats_reporter.go, injection/informers_test.go, kmp/reporters_test.go, logging/config.go, test/ghutil/fakeghutil/fakeghutil.go, test/gke/client.go, test/gke/wait.go, test/helpers/dryrun.go, test/junit/junit_test.go, test/mako/alerter/github/issue.go, test/webhook-apicoverage/resourcetree/test_util.go, testutils/clustermanager/e2e-tests/gke.go, webhook/resourcesemantics/resourcesemantics_test.go, webhook/testing/testing.go, webhook/webhook.go, webhook/webhook_test.go
There's a lot of linter juice in knative.dev/pkg. This fixes almost all of the warnings except for capitalized error strings.
=> Assorted linting fixes.

controller/controller.go, controller/controller_test.go
This changes introduces Impl.EnqueueSentinel which returns an enqueue function which only ever enqueues a single predefined key.
Fixes #839.
=> add EnqueueSentinel to pkg/controller

apis/condition_types.go, apis/duck/v1/status_types.go, apis/duck/v1beta1/status_types.go, apis/volatile_time.go
`openapi-gen` is not used anymore in Knative.
=> Remove openapi-gen annotations

reconciler/testing/sorter.go
Not having this causes the listers to log an annoying log message like
```
W1108 02:48:54.848573  211995 listers.go:77] can not retrieve list of objects using index : Index with name namespace does not exist
```
That message doesn't cause the tests to fail because the cache logic works around by doing a "slow indexing". I was very confused by this log though and sunk a bit of time into debugging it, so here we go.
=> Add Namespace index to listers in tests.

reconciler/testing/tracker.go, tracker/enqueue.go, tracker/enqueue_test.go, tracker/interface.go, tracker/interface_test.go
`TrackReference` is the same as `Track`, but takes a `tracker.Reference` instead.  This type has been seeded with the subset of `corev1.ObjectReference` that the tracker currently consumes / supports, but the intention is to expand this type to allow inexact references that (optionally) use label selectors in place of name to reference objects.
See also: https://github.com/knative/pkg/issues/859
/hold
for the downstream changes to be staged.
=> Expand the tracker interface to include a variant with its own type.

injection/sharedmain/main.go
This PR should be the most straightforward fix by NOT adding the ConfigMaps into the config map watcher, if config-logging or config-observability is missing.
=> Skip watching the ConfigMaps if they are missing

logging/config.go
In every log we get the ugly string printed:
2019-11-13T08:44:42.421-0800    info    logging/config.go:50
Successfully created the logger.    {"knative.dev/jsonconfig": "{\n\t
\"level\": \"debug\",\n\t  \"encoding\": \"console\",\n\t
\"outputPaths\": [\"stdout\"],\n\t  \"errorOutputPaths\":
[\"stderr\"],\n\t  \"encoderConfig\": {\n\t    \"timeKey\":
\"ts\",\n\t    \"messageKey\": \"message\",\n\t    \"levelKey\":
\"level\",\n\t    \"nameKey\": \"logger\",\n\t    \"callerKey\":
\"caller\",\n\t    \"messageKey\": \"msg\",\n\t    \"stacktraceKey\":
\"stacktrace\",\n\t    \"lineEnding\": \"\",\n\t    \"levelEncoder\":
\"\",\n\t    \"timeEncoder\": \"iso8601\",\n\t    \"durationEncoder\":
\"\",\n\t    \"callerEncoder\": \"\"\n\t  }\n\t}"}
It's all a constant (see …
=> Remove ugly constant string being printed in every log.

apis/interfaces.go, testing/resource.go, webhook/resourcesemantics/defaulting/controller.go, webhook/resourcesemantics/defaulting/defaulting.go, webhook/resourcesemantics/defaulting/defaulting_test.go, webhook/resourcesemantics/defaulting/table_test.go, webhook/resourcesemantics/defaulting/user_info.go, webhook/resourcesemantics/defaulting/user_info_test.go, webhook/resourcesemantics/interface.go, webhook/resourcesemantics/validation/controller.go, webhook/resourcesemantics/validation/table_test.go, webhook/resourcesemantics/validation/validation.go, webhook/resourcesemantics/validation/validation_deprecated_test.go, webhook/resourcesemantics/validation/validation_test.go, webhook/webhook.go
By combining our validation logic into our mutating webhook we were previously allowing for mutating webhooks evaluated after our own to modify our resources into invalid shapes.  There are no guarantees around ordering of mutating webhooks (that I could find), so the only way to remedy this properly is to split apart the two into separate webhook configurations:
- `defaulting`: which runs during the mutating admission webhook phase
- `validation`: which runs during the validating admission webhook phase.
The diagram in [this post](https://kubernetes.io/blog/2019/03/21/a-guide-to-kubernetes-admission-controllers/) is very helpful in illustrating the flow of webhooks.
Fixes: https://github.com/knative/pkg/issues/847
/hold
I need to stage downstream PRs for this.
=> Split the resource semantic webhooks into separate AdmissionControllers

Gopkg.lock, test/e2e_flags.go, test/e2e_flags_test.go
glog isn't used in our repos with good reason, but performance tests
use it, for now. This commit removes the ability to set klog flags
that aren't shared with glog, in return for the ability of glog to be imported.
/assign @chizhg
=> Allow glog to coexist with klog

websocket/connection.go
The original handshake timeout is too short to dial connection
successfully under some situation. So the activator pod can not be
active. And the log message just say "Failed to send ping message to
ws://autoscaler.knative-serving.svc.cluster.local:8080", not easy to
figure out what's the problem underneeth.
The fix switch to websocket default dial, so the default handle shake
time is 45 seconds, and once dial error found, the error will be
reported as error.
=> Fixed knative activator handshake timeout issue

apis/duck/unstructured.go, apis/duck/unstructured_test.go, testing/resource.go
This adds a ToUnstructured method to complement the FromUnstructured method
we have had for some time.  The ToUnstructured method is effectively scoped
to Knative-style types since we expect it to implement both kmeta.Accessor
and kmeta.OwnerRefable in order to ensure that the TypeMeta is always
properly populated.
=> Add a simple ToUnstructured method for converting our types to unstructured.

resolver/addressable_resolver.go, resolver/addressable_resolver_test.go
Fixes #890 
Add a new method URIFromDestinationV1 for resolving v1.Destination
Since v1beta1 and v1 Addressable are the same, watch for v1 duck addressable.
=> Resolvev1destination

apis/duck/typed.go, apis/duck/typed_test.go
Related on issue in eventing repo
[#2047](https://github.com/knative/eventing/issues/2047) sources-controller can't recover from faulty sink 
If there has an invalid resource, the controller will keep showing error and not process new sources until the controller pod is deleted.
The root cause is explained in this [comment](https://github.com/knative/eventing/issues/2047#issuecomment-554084211)
=> Add check in informer to make controllers work when process invalid resources

reconciler/testing/table.go, webhook/testing/listers.go
I'm splitting this off of another change that needed them, the three changes are:
1. Give the PostConditions callbacks in TableRow access to the Reconciler
resource.  It turns out this is incredibly useful to have the `TableRow`
program an admission controller and then test that programming by calling
`Admit()`.
1. Surface the test resources in our webhook "listers", and add the testing
scheme.
1. Change the `objKey` to only use reflection as a fallback.  The existing logic
doesn't work properly when a mix of real resources and unstructured.Unstructured
is used for the same resource.
=> This has three small table testing changes.

testutils/clustermanager/e2e-tests/gke.go, testutils/clustermanager/e2e-tests/gke_test.go
**Bug:** Cannot get cluster from kubeconfig when the cluster name in the kubeconfig is different from [getResourceName](https://github.com/knative/pkg/blob/2ec0f8da50578dcc3d830571d0de24de834579c8/testutils/clustermanager/e2e-tests/util.go#L35). 
In [Setup](https://github.com/knative/pkg/blob/master/testutils/clustermanager/e2e-tests/gke.go#L94), it sets the ClusterName if it's "". Then in [checkEnvironment](https://github.com/knative/pkg/blob/master/testutils/clustermanager/e2e-tests/gke.go#L325), the cluster name check fails. 
**Repro steps:** Run `go run knative.dev/pkg/testutils/clustermanager/prow-cluster-operation --get  --project="" --name="" `
**Current behaviour:** Returns an error
```
go run knative.dev/pkg/testutils/clustermanager/prow-cluster-operation --get  --project="" …
```
=> Moved cluster name check to later so --get can use cluster name in kubeconfig

testutils/clustermanager/e2e-tests/boskos/boskos.go, testutils/clustermanager/e2e-tests/boskos/boskos_test.go, testutils/clustermanager/e2e-tests/boskos/fake/fake.go, testutils/clustermanager/e2e-tests/gke.go, testutils/clustermanager/e2e-tests/gke_test.go, testutils/clustermanager/prow-cluster-operation/options/options.go
Currently, the boskos library always acquire resource type "gke-project".
https://github.com/knative/pkg/blob/master/testutils/clustermanager/e2e-tests/boskos/boskos.go#L63
This change makes the boskos resource type customizable in Acquire. 
Test PR: https://github.com/knative/test-infra/pull/1570
/cc @chaodaiG
=> modify boskos in cluster manager to make the boskos resource type customizable

Gopkg.lock, network/OWNERS, network/error_handler.go, network/h2c.go, network/network.go, network/prober/doc.go, network/prober/prober.go, network/prober/prober_test.go, network/transports.go, network/transports_test.go, vendor/golang.org/x/net/http2/h2c/h2c.go
I was asked to move this to do some re-use in Eventing.
This is 1 to 1 move with:
- one import line change in prober.
- removing most of network.go, since it was serving/istio specific.
/cc @chizh
/assign mattmoor @tcnghia
=> Move generic packages from serving to pkg.

kmeta/names.go, kmeta/names_test.go
If suffix name itself contained dashes, when we append the trimmed suffix
we might end up on the dash, which is a non valid k8s name.
So fix that.
=> Fix the childname where trimming caused a dash in the end.

test/README.md, test/e2e_flags.go
Fix https://github.com/knative/test-infra/issues/1568
Remove `emit-metrics` as the relevant job has been deprecated.
/cc @adrcunha 
/cc @chaodaiG
=> Remove emit-metrics flag in e2e tests base library

reconciler/testing/table.go
- Needed to pass any extra arbitrary test information. For example, to mock some client calls.
/cc @grantr 
/cc @n3wscott
=> Adding OtherTestData attribute to TableRow

webhook/webhook.go, webhook/webhook_integration_test.go
Webhook integration tests occasionally fail with on testgrid, e.g.
https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-pkg-continuous/1204193472353931264
https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-pkg-continuous/1203166664988823552
Fix this by waiting for all goroutines to finish before each test ends.
=> De-race webhook integration tests

apis/testing/conditions.go, apis/testing/v1/conditions.go, apis/testing/v1beta1/conditions.go, metrics/metricstest/metricstest.go, test/helpers/name.go, test/logstream/interface.go, test/logstream/kubelogs.go, test/tinterface.go
Working to introduce structured logging to our tests. See #907
This work allows these test functions to be called by objects other
than *testing.T. The t.Error() calls are made compatible with
structured logging (wrapping Zap sugared logger calls) or code using
testing.T.
=> Switch *testing.T uses to equivalent interface + structured logging

Gopkg.lock, Gopkg.toml, profiling/server.go, test/spoof/spoof.go, test/webhook-apicoverage/tools/tools.go, webhook/psbinding/reconciler.go
Title has it all. We don't really need this anymore since go1.13.
=> Remove all occurrences of github.com/pkg/errors.

testutils/clustermanager/perf-tests/pkg/cluster.go, testutils/clustermanager/perf-tests/pkg/cluster_test.go
Modify the logic for `RecreateClusters` a bit, to let it also create new clusters when they do not exist.
NOTE:
This change is made to allow users to create clusters from scratch against a new repo that needs performance tests. It won't impact the existing benchmark runnings.
/cc @adrcunha
=> RecreateClusters function also create new clusters if they do not exist

test/spoof/spoof.go
Add option to have spoofing client always retry regardless what error encountered.
Prepare for https://github.com/knative/serving/issues/6224
/cc vagababov
=> Spoofing client to retry on all error

test/README.md
Add flags and their explaination.
=> Update test README.md

testutils/clustermanager/prow-cluster-operation/actions/create.go, testutils/clustermanager/prow-cluster-operation/actions/get.go, testutils/clustermanager/prow-cluster-operation/main.go
Returns gkeOps in `create`, `get` in prow-cluster-operation actions to fetch the Cluster info that's just created/fetched without reading the metadata file when calling from Go directly.
=> Return GKECluster info in PCO

profiling/server.go, profiling/server_test.go
The profiling handler is in the path of our most performance critical components (especially the activator). Taking a write-lock on each request is probably a bad idea.
Replaced the mutex with an atomic flag. Lost reads are not critical in this code path and that should be the quickest solution in terms of avoiding contention.
=> Optimize locking behavior of the profiling handler.

test/banned_deps_test.go, test/imports/banned_deps_test.go
Eventing had some bad merges where we almost shipped `github.com/knative/eventing/` imports in `0.9.0`.
Adding a test for Knative to never have this be possible again.
=> Ban importing aliased domains.

apis/url.go
url.URL has an unexported type (UserInfo) which causes semantic
equality to panic unless we add a custom equality function
=> Provide an semantic equality func for apis.URL

test/gke/endpoint.go, test/gke/endpoint_test.go, testutils/clustermanager/perf-tests/main.go, testutils/clustermanager/perf-tests/pkg/cluster.go
perf-tests cluster manager tool supports creating clusters in other environment, including `test`, `staging`, `prod` or with any other custom endpoint.
Note:
1. Part of the code is borrowed from `kubetest` in kubernetes test-infra - https://github.com/kubernetes/test-infra/blob/9d3c810352d830d3a29b8625df7f5dab25924eb7/kubetest/gke.go#L184, thanks @yt3liu for digging it out 
2. I believe the e2e-tests cluster manager tool will also need this, but I did not make the change in this PR as I do want to keep it smaller.
/cc @adrcunha 
/cc @yt3liu 
/cc @chaodaiG
=> perf-tests cluster manager supports creating clusters in other environment

Gopkg.lock, configmap/informed_watcher.go, configmap/informed_watcher_test.go, configmap/manual_watcher.go, injection/sharedmain/main.go, system/env.go
Ensure the ConfigMap watcher only tracks the ConfigMaps which contain the label defined by the optional `SYSTEM_RESOURCE_LABEL` env var if the latter is set and not empty.
Custom components (event sources, channels, ...) may be deployed to various namespaces which sometimes contain a large amount of ConfigMaps. For example, a typical [Kyma](https://kyma-project.io/) installation deploys >80 ConfigMaps inside the `kyma-system` namespace. This creates a surge of memory usage when watches expire and get re-instantiated.
_jumps from 9MiB to **25MiB**_
_stable-ish usage between 9MiB and **11MiB** with a label selector applied_
=> Filter tracked sharedmain ConfigMaps based on optional label selector

metrics/config_observability.go, metrics/config_observability_test.go
updating `config_observability.go` to match [serving/pkg/metrics/config.go](https://github.com/knative/serving/blob/master/pkg/metrics/config.go#L28) before getting rid of `config.go` in serving.
required for https://github.com/knative/serving/pull/5841
/cc @markusthoemmes @yanweiguo
=> Add default metrics backend to observability config

apis/duck/v1/status_types.go, apis/duck/v1/status_types_test.go
the intent is to allow the inclusion of addition ConditionTypes to be copied over if a
a predicate returns true
Motivation: https://github.com/knative/serving/pull/6542/files?file-filters%5B%5D=.go#r368663116
=> status.ConvertTo can optionally accept predicates

webhook/psbinding/psbinding.go, webhook/psbinding/table_test.go
This removes the built-in types from being hard-coded, and we will now only intercept them if they are used in a Binding.
cc @bbrowning @vaikas
=> Only intercept types that appear in Bindings.

testutils/clustermanager/perf-tests/pkg/cluster.go
This PR partially reverts https://github.com/knative/pkg/pull/954, do not enable workload identity for perf tests GKE clusters.
Explanation:
[Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) is still in beta, and it's brittle. And it has a caveat that "when Workload Identity is enabled, you can no longer use the Compute Engine default service account", so all workloads on that cluster will not use any Google service account by default.
Specially, GKE released `1.15.7-gke.23` last Friday, and all benchmarks were broken due to Workload Identity. The root cause is because the `prometheus-stackdriver` Pod cannot start since no Google service account is provided.
It was a wrong decision to use Workload Identity, and for our internal use, I've found …
=> Do not enable workload identity for perf tests GKE clusters

test/gke/request.go, testutils/clustermanager/e2e-tests/gke_test.go
Background:
When we create a GKE cluster, we can specify the scopes, which means the set of Google API scopes to be made available on all of the node VMs under the "default" service account. If it's not specified, no scopes will be added.
Plus, communicating and authenticating with **gcr.io** requires `https://www.googleapis.com/auth/devstorage.read_only`. If it's not specified, the workloads on that cluster won't be able to pull images from private GCR.
This PR adds CloudPlatformScope in the base gke lib, so all clusters will be able to talk to all Google APIs. We can make it more fine granular in the future if needed.
/cc @chaodaiG 
/cc @yt3liu 
/cc @adrcunha
=> Give cloud-platform scope by default in creating GKE clusters

apis/url_test.go
The error formatting changed, so update the tests so they work with both 1.13
and 1.14.
=> Fix the URL errors for go1.14

hack/update-deps.sh
Same as knative/serving#6361
Usual workflow for updating custom deps is running dep ensure -update some/go/path, followed by running ./hack/update-deps.sh. This
results in dep ensure being called a second time and slows the
process down an annoying amount. Now user can just run
./hack/update-deps.sh -update some/go/path and it works.
=> Allow Custom `dep ensure` args in hack/update-deps.sh

metrics/config.go, metrics/record.go, metrics/record_test.go
In serving we have many places where we try to record several metrics at the same time.
Besides very repetetive code, this also brings inefficiences, since metrics code has to do _some_ work
for every call, which is completely avoidable.
This way we can record N measurements with one hit.
If we agree in principle, I'll extend the unit tests.
/assign @evankanderson @anniefu
=> Add RecordN method to permit recording of N measurements simultaneously.

apis/duck/v1/destination_test.go, apis/duck/v1/knative_reference.go, apis/duck/v1/knative_reference_test.go
Make namespace optional for two reasons:
- Existing objects will keep working without this restriction
- This will allow us to have references to cluster level resources.
=> make namespace optional so existing objects keep working and we have flexibility for cluster level objects.

test/gke/request.go, test/gke/request_test.go, testutils/clustermanager/e2e-tests/gke.go, testutils/clustermanager/perf-tests/pkg/cluster.go, testutils/clustermanager/prow-cluster-operation/main.go
Support `--enable-workload-identity` and `--service-account` for cluster creation request.
I add them in the gke lib as all the tools built on it will automatically support these two flags.
/cc @chaodaiG
=> Add extra flags for cluster creation in test

metrics/metricstest/metricstest.go
Currently the function aptly named `CheckLastValueData` does not only check that, but
also checks that it's the _single_ entry, which is not necessarily true,
especially if run as part of a bigger test suite.
So change it to actually verify the last row and remove the check for the singular entry.
Given that all the tests pass, this probably was not intended anyway.
/assign @evankanderson @yanweiguo
=> Make sure we actually check the last value.

codegen/cmd/injection-gen/generators/packages.go, codegen/cmd/injection-gen/generators/reconciler_controller.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go
In attempting to integrate with a more complicated reconciler, I found two issues:
1. If the reconciler does not use reconciler.Base, then the scheme is not added to the k8s scheme.Scheme and k8s events can not be created. This is fixed by adding the init method.
1. If the reconciler uses reconciler.Events, and returns a non-nil event the reconciler will report these as errors in the log. To prevent this the wrapped error logic nils out handled errors.
=> BugFix: Returning errors and adding scheme.

apis/contexts.go, apis/contexts_test.go, apis/duck/v1/destination.go, apis/duck/v1/knative_reference.go, apis/duck/v1/knative_reference_test.go
- Add a check to see if KReference namespace matches that of the encapsulating object via context.
- skip the check if the namespace is null to ensure legacy objects will keep working.
=> check KReference namespace matches parent. Allow escape hatch.

codegen/cmd/injection-gen/generators/reconciler_controller.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Knative normally sets up a base for the reconciler, if this happens then there is a recorder watch registered and is pulled from the context. The original gen reconciler was not checking for a nil event recorder and events were not being logged if reconciler.Base (from serving or eventing) was not used.
This fixes that issue.
Working events with sample-controller in https://github.com/knative/sample-source/pull/11
=> [Gen Reconciler] Fix issue found with controllers without reconciler.Base

test/e2e_flags.go
Signed-off-by: Doug Davis <dug@us.ibm.com>
=> Add support for KUBECONFIG env var in the tests

apis/duck/v1alpha1/addressable_types.go, apis/duck/v1alpha1/addressable_types_test.go, apis/duck/v1beta1/addressable_types_test.go
attempting to use the addressable converters in another test, I ran into the issue with an empty addressable object:
```
- 			Addressable: v1beta1.Addressable{},
+ 			Addressable: v1beta1.Addressable{URL: s"http:"},
```
Which means something was adding a non-nil url in the addressable. It was the usage of `GetURL`. So that is removed.
=> Fix defaulting bug in the converter for empty addressables.

apis/duck/v1alpha1/addressable_types.go, apis/duck/v1alpha1/addressable_types_test.go
found an assumption in eventing where the hostname is still in play.
=> Fix a upconvert with empty url

version/version.go, version/version_test.go
Kubernetes 1.15.0 has a bug in openapi and conversion webhook does not
allow to deploy Knative resources by kubectl at all.
To avoid hit the issue, this patch bumps the minimum version to
1.15.1.
Please refer to https://github.com/knative/serving/issues/6787 for more detail.
=> bump the minimum version to 1.15.1

codegen/cmd/injection-gen/generators/packages.go, codegen/cmd/injection-gen/generators/reconciler_controller.go, codegen/cmd/injection-gen/generators/reconciler_controller_stub.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
fixes https://github.com/knative/pkg/issues/1065
Implements option 1. 
Example integration: https://github.com/knative/sample-controller/pull/213/
Integrators have the option to use either managed finalizers by implementing `FinalizeKind`:
```go
func (r *Reconciler) FinalizeKind(ctx context.Context, o *v1alpha1.AddressableService) reconciler.Event {
// TODO: add custom finalization logic here.
return nil
}
```
or without finalizers:
```go
// no change
```
=> Generate Managed Finalizers for Reconcilers

codegen/cmd/injection-gen/generators/packages.go, codegen/cmd/injection-gen/generators/reconciler_controller.go, codegen/cmd/injection-gen/generators/reconciler_controller_stub.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
I never saw the filter for generators work because I have only been doing one at a time integrations. With two, the filter for type was wrong and would always pick the first one. 
this fixes that filter issue.
=> fix filtering for reconcilers gen.

webhook/psbinding/reconciler.go, webhook/psbinding/table_test.go
If [r.Factory.Get(gvr)](https://github.com/knative/pkg/blob/76b1a0d8134f5a5d4172a8b95b0e6ce47b92c0f7/webhook/psbinding/reconciler.go#L253) fails, set SinkBinding `Ready` condition to False with `SubjectUnavailable` Reason and underlying error in Message field. 
On SinkBinding deletion request, If underlying error is of `IsForbidden` type (which may be caused by GVR misspell), consider Subject as non-existing and remove SinkBinding 
knative/eventing#2464
=> Handle wrong apiVersion/kind in SinkBinding subject  

codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Fix for the following:
```
/home/prow/go/src/knative.dev/serving/tmpdiffroot.mjvj8H/pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
--- /home/prow/go/src/knative.dev/serving/pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go	2020-02-11 15:29:04.303257604 +0000
+++ /home/prow/go/src/knative.dev/serving/tmpdiffroot.mjvj8H/pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go	2020-02-11 15:22:38.423932268 +0000
@@ -29,9 +29,9 @@ import (
errors "k8s.io/apimachinery/pkg/api/errors"
metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
"k8s.io/apimachinery/pkg/types"
-	"k8s.io/apimachinery/pkg/util/sets"
cache "k8s.io/client-go/tools/cache"
record "k8s.io/client-go/tools/record"
+ …
```
=> set the import for sets

injection/README.md
Adding documentation on how to use and what to expect from the generated reconciler code added to client injection gen.
=> Document genreconciler.

controller/controller.go, controller/controller_test.go
In addition deprecated usage of `Filter` with the introduction of `FilterGroupVersionKind`
=> allow filtering on schema.GroupKind

codegen/cmd/injection-gen/generators/reconciler_controller.go, codegen/cmd/injection-gen/generators/reconciler_controller_stub.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go, controller/options.go, injection/README.md, reconciler/configstore.go
Serving uses snapshot config files all over the place, this change allows the context to be modified by a passed on configStore decorator.
=> [Reconciler Generators] Adding support for configStore.ToContext

tracker/enqueue.go
This came up here: https://github.com/knative/pkg/pull/861#discussion_r344574547
=> Avoid callback calls while lock is held.

apis/duck/v1/source_types.go
Update was discussed in eventing [PR 2564](https://github.com/knative/eventing/pull/2564), because it's no longer a domain name, but merely a URI.
/assign @n3wscott  
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
=> Updating comment on Destination

reconciler/filter.go, reconciler/filter_test.go, reconciler/retry.go, reconciler/retry_test.go
- This is useful for eventing (and other repos) as well, to filter annotations, labels, etc. 
- Modified the tests to use v1.Pod, instead of serving Configuration.
- We will be able to improve things like [this](https://github.com/knative/eventing/blob/e3495dc8f2ea1b24737837f7886d33de61c85264/pkg/reconciler/namespace/namespace.go#L102)
I'll follow up and remove serving code once this is merged.
=> Upstreaming Serving filter functions

codegen/cmd/injection-gen/generators/reconciler_reconciler.go
some reconcilers need access to a recorder from context.
=> adding recorder to context.

apis/test/pub/v1alpha1/bar_types.go, codegen/cmd/injection-gen/generators/packages.go, codegen/cmd/injection-gen/generators/reconciler_controller.go, codegen/cmd/injection-gen/generators/reconciler_controller_stub.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go, injection/README.md
Fixes: https://github.com/knative/pkg/issues/1098
Adding a new annotation config to allow us to configure strongly classed reconcilers, such as Eventing's Broker, or Serving's Ingress.
This will be a breaking API change for types that opt into this behavior. The main changes are the addition of ` classValue string` to `NewImpl` and `NewReconciler` (for tests)
```go
NewImpl(ctx context.Context, r Interface, classValue string, optionsFns ...controller.OptionsFn) *controller.Impl
```
```go
NewReconciler(ctx context.Context, logger *zap.SugaredLogger, client versioned.Interface, lister pubv1alpha1.BarLister, recorder record.EventRecorder, r Interface, classValue string, options ...controller.Options) controller.Reconciler
```
This feature is enabled with a golang annotation argument:
```go
// …
```
=> Implement strongly typed class reconcilers

apis/condition_set.go, apis/condition_set_impl_test.go
If you have the case:
Foo False
Bar Unknown
Baz False
And Foo was the last to be set, Ready will be set as Foo (message and reason)
If Foo is cleared, Baz should propagate to Ready reason and message.
This PR does that ^
=> Realized a corner case on ordering and False > Unknown states.

injection/sharedmain/main.go
WebhookMain* now implements the old main flow - while Main* no longer serves webhooks. This allows us to retain the existing behavior for webhooks - which require additional investigation / decision making on how to deal with HA concerns.
Related to #1007
=> Introduce sharedmain.WebhookMain*

test/webhook-apicoverage/webhook/webhook.go, webhook/certificates/certificates.go, webhook/certificates/certificates_test.go, webhook/certificates/resources/certs.go, webhook/certificates/resources/certs_test.go, webhook/certificates/resources/secret.go, webhook/webhook.go
This will remove the webhook secret(webhook-certs) so that a new secret is created if the NotAfter/Expiration date is less than a week.
=> Renews a webhook cert before it expires

apis/convert.go, apis/convert_test.go, apis/duck/v1/addressable_types.go, apis/duck/v1/addressable_types_test.go, apis/duck/v1alpha1/addressable_types.go, apis/duck/v1alpha1/addressable_types_test.go, apis/duck/v1beta1/addressable_types.go, apis/duck/v1beta1/addressable_types_test.go, apis/interfaces.go, apis/testing/roundtrip/roundtrip.go, webhook/resourcesemantics/conversion/controller.go, webhook/resourcesemantics/conversion/conversion.go, webhook/resourcesemantics/conversion/conversion_test.go, webhook/resourcesemantics/conversion/internal/types.go
=> Fixed #1057 - Rename ConvertUp/Down to ConvertTo/From

Gopkg.lock, injection/sharedmain/main.go, leaderelection/config.go, leaderelection/config_test.go, vendor/k8s.io/apimachinery/pkg/util/uuid/uuid.go, vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go, vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go, vendor/k8s.io/client-go/tools/leaderelection/metrics.go, vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go, vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go, vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go, vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
Cherry-pick of #1019 into release0.13
* Add leader election config and to sharedmain
* Add new dependencies
* Extract method for RunLeaderElected
* Make leader election config constructor validate
* Rename leader election files
* Always start profiling server whether component has LE lock or not
* Fix entering unreachable section when leader election is disabled
* Address PR feedback
=> release-0.13: add leader election support to sharedmain (#1019)

metrics/metricskey/constants.go
Those are used in many places and thus deserve to be named constants.
First class citizenship for pod name! :hammer: 
=> Add standard pod and container name keys

reconciler/testing/context.go
Pretty much as the title says. This allows us to pass in `testing.T` and `testing.B`, thus allowing us to use correct loggers etc. in benchmarks as well.
=> Generalize SetupFakeContext to be able to serve tests and benchmarks.

codegen/cmd/injection-gen/generators/reconciler_controller.go, codegen/cmd/injection-gen/generators/reconciler_controller_stub.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Breaking this out from the broader discussion I started on Slack around class-based reconcilers.
Regardless of what the outcome is, I think we should encourage users to add the class filters to their informers to reduce churn.
=> Add filtering to class based controller stubs.

injection/sharedmain/main.go
This fixes an issue where a controller will crashloop if a leader election config doesn't exist.
=> Fix crash looping when leader election config doesn't exist

metrics/exporter.go, metrics/exporter_test.go
Passing `-` in will create invalid metric names for prometheus (at least); mutate it on the way in.
As a follow-up, we need to add validation for the component name on the way into metrics.
=> Mutate `-` to `_` in component names for metrics

test/clients.go, test/e2e_flags.go, test/request.go, test/spoof/spoof.go
It might be handy to configure the values in different environments or different kinds of tests. For example, sometimes I want to be able to send requests more frequently than once per second, like in the prober.test in knative/serving which runs during rolling upgrades.
=> Configurable SpoofRequestInterval and SpoofRequestTimeout

webhook/certificates/certificates.go, webhook/resourcesemantics/conversion/conversion.go
In general, imo, it's prettier to return things as is, rather than the pattern that was
there. Also net negative code :). But, this is debatable, I guess 🤷‍♂ 
Also handle one more error case, which was kind of ignored before (probably in practice
impossible, but idk)
=> Remove named returns, since they look icky :)

webhook/certificates/certificates.go, webhook/certificates/certificates_test.go
This is a carry-over from when this was originally written and we had webhooks and secrets being GC'd due to a bad owner reference.
=> Drop the logic to create missing secrets.

apis/condition_set.go, apis/condition_set_impl_test.go, apis/condition_set_test.go
Currently we cannot set a condition to true with the reason.
When using `MarkTrue()` function, it does not allow us to add the reason and message.
Also, if we use `SetCondition()` instead, it does not update the happy condition.
So, this PR adds new `MarkTrueWithReason(reason, message)` function to solve it.
For example in the Serving project, we want to manage KCert's condition, like below:
```
$ kubectl get rt hello-example -o yaml
...
conditions:
- lastTransitionTime: "2020-03-07T08:30:11Z"
message: autoTLS is not enabled
reason: AutoTLSNotEnabled
status: "True"
type: CertificateProvisioned
$ kubectl get rt
NAME            URL                                        READY   REASON
hello-example   http://hello-example.default.example.com   True
```
=> Add MarkTrueWithReason function to ConditionManager

Gopkg.lock, Gopkg.toml, vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go, vendor/github.com/google/go-cmp/cmp/compare.go, vendor/github.com/google/go-cmp/cmp/export_panic.go, vendor/github.com/google/go-cmp/cmp/export_unsafe.go, vendor/github.com/google/go-cmp/cmp/internal/value/sort.go, vendor/github.com/google/go-cmp/cmp/internal/value/zero.go, vendor/github.com/google/go-cmp/cmp/options.go, vendor/github.com/google/go-cmp/cmp/path.go, vendor/github.com/google/go-cmp/cmp/report_compare.go, vendor/github.com/google/go-cmp/cmp/report_reflect.go, vendor/github.com/google/go-cmp/cmp/report_slices.go, vendor/github.com/google/go-cmp/cmp/report_text.go, vendor/golang.org/x/xerrors/LICENSE, vendor/golang.org/x/xerrors/PATENTS, vendor/golang.org/x/xerrors/adaptor.go, vendor/golang.org/x/xerrors/doc.go, vendor/golang.org/x/xerrors/errors.go, vendor/golang.org/x/xerrors/fmt.go, vendor/golang.org/x/xerrors/format.go, vendor/golang.org/x/xerrors/frame.go, vendor/golang.org/x/xerrors/internal/internal.go, vendor/golang.org/x/xerrors/wrap.go
Mostly to fix https://github.com/google/go-cmp/issues/167, but we also pinned at some
random commit, rather than at a release version.
As is upgrade to  go1.14 would cause `go test -race` fail in a few places.
=> update go-cmpt to work with 1.14.

injection/sharedmain/main.go, webhook/admission.go, webhook/admission_integration_test.go, webhook/configmaps/configmaps.go, webhook/resourcesemantics/defaulting/defaulting.go, webhook/resourcesemantics/validation/validation.go, webhook/webhook.go, webhook/webhook_integration_test.go
Some webhooks (e.g. conversion) are required to list resources, so by delaying those until after informers have synced, we create a deadlock when they run in the same process.  This change has two key parts:
1. Start the webhook immediately when our process starts, and issue a callback from sharedmain when the informers have synced.
2. Block `Admit` calls until informers have synced (all conversions are exempt), unless they have been designated by implementing `webhook.StatelessAdmissionController`.
Our built-in admission controllers (defaulting, validation, configmap validation) have all been marked as stateless, the main case where we want to block `Admit` calls is when we require the informer to have synchronized to populate indices for Bindings.
=> Start the webhook before informers sync.

leaderelection/config.go, leaderelection/config_test.go
- Add defaulting for all but the component, which are system dependent
- Improve test coverage
- Clean up formatting
- Other test changes
/assign mattmoor @pmorie 
@pmorie , Paul do you have a bug for this cleanup?
=> Fix the defaulting for the leader election config map

testutils/clustermanager/e2e-tests/config.go, testutils/clustermanager/e2e-tests/gke.go, testutils/clustermanager/e2e-tests/gke_test.go, testutils/clustermanager/e2e-tests/util.go, testutils/clustermanager/prow-cluster-operation/actions/create.go, testutils/clustermanager/prow-cluster-operation/actions/delete.go, testutils/metahelper/client/client.go, testutils/metahelper/client/client_test.go, testutils/metahelper/main.go
1. Add cluster retry logic, and the error patterns are copied from https://github.com/knative/test-infra/blob/master/scripts/e2e-tests.sh#L312-L315 (I think it shares the same error pattern as `gcloud`, at least I tried the `unsupported GKE version` error, and the error message is the same)
2. If it's on boskos, delete cluster asynchronously. If it's on local, make it a blocking operation (Not sure if it's the desired logic, I'll need to fix the unit tests if so)
=> Retry cluster creation if there's an error

apis/condition_set.go, apis/condition_set_impl_test.go
`accessor.GetConditions()` in `findUnhappyDependent()` gets status
filed from runtime. So, if an object has following status:
```
status:
address:
url: http://hello-example.default.svc.cluster.local
conditions:
- lastTransitionTime: "2020-04-02T09:49:03Z"
status: "True"
type: AllTrafficAssigned
- lastTransitionTime: "2020-04-02T09:49:03Z"
message: autoTLS is not enabled
reason: AutoTLSNotEnabled
severity: Info
status: "True"
type: CertificateProvisioned
- lastTransitionTime: "2020-04-02T09:49:05Z"
status: "True"
type: IngressReady
- lastTransitionTime: "2020-04-02T09:49:05Z"
status: "True"
type: Ready
```
`accessor.GetConditions()` returns `AllTrafficAssigned`,
`CertificateProvisioned`, `IngressReady` (and `Ready`).
Now, current code (`len(r.dependents) != len(conditions)`) sets to …
=> Do not set to unknown status when all dependents passed happy check

injection/sharedmain/main.go
When deploying pods with Istio sidecar, it takes a few seconds until
network is configured. In fact, Serving's system pods always fail when
Istio sidecar is enbled.
To fix it, this patch changes to retry to get logging configmap for 5
seconds.
Fixes https://github.com/knative/serving/issues/7486
=> Retry to get logging configmap when failed

metrics/config.go, metrics/config_observability.go, metrics/exporter.go, metrics/exporter_test.go
This is useful if you want to disable any surfacing of metrics whatsoever.
=> Allow a 'None' metrics backend, to basically do nothing.

metrics/record_test.go
The test names have been unused before. We can also reuse the `cases` type instead of redefining it inline.
=> Actually use the subtest names in recorder test.

codegen/cmd/injection-gen/generators/packages.go, leaderelection/config.go, metrics/exporter_test.go, metrics/monitored_resources.go, test/e2e_flags.go, test/logging/logging_test.go, test/logging/sugar.go, test/logging/tlogger.go, test/testgrid/testgrid.go, webhook/psbinding/table_test.go, webhook/resourcesemantics/defaulting/defaulting_test.go, webhook/webhook_test.go
=> Fix a few simple linter warnings: unused code, govet warnings etc.

webhook/resourcesemantics/conversion/conversion.go
Otherwise it's just unused (the reference is never picked up anywhere).
=> Add augmented logger to the context to pass it down.

webhook/admission_integration_test.go
> A test ends when its Test function returns or calls any of the methods FailNow, Fatal, Fatalf, SkipNow, Skip, or Skipf. Those methods, as well as the Parallel method, must be called only from the goroutine running the Test function.
=> t.Fatal must not be called in a goroutine.

Gopkg.lock, apiextensions/OWNERS, apiextensions/storageversion/cmd/migrate/config.go, apiextensions/storageversion/cmd/migrate/main.go, apiextensions/storageversion/migrator.go, apiextensions/storageversion/migrator_test.go
See https://github.com/knative/serving/pull/7499 for context
Essentially, the tool is generic enough it's possible to use on any CRD
=> Include utility to migrate a CRD's storage version

configmap/testing/configmap.go
Mostly this is to cover tabs, but also other strange things, like carriage return :-)
/assign mattmoor @mdemirhan
=> Make a proper check when checking for spaces.

OWNERS_ALIASES, logging/config, tracing/config/OWNERS
Make sure they're uniform more or less.
Also add myself for CM approvers, given I've rewrote most of them recently.
=> Normalize CM owners across CM directories

test/helpers/name.go
In serving, when running e2e test after changing the domainTempalte to
`{{.Name}}-{{.Namespace}}.{{Domain}}`, some tests failed with
following error:
```
Retrying for DNS error: Get http://service-to-service-call-via-activator-a-disabled-qgoluwzd-serving-tests.apps.ci-op-y42hx5lj-23b3e.origin-ci-int-aws.dev.rhcloud.com: dial tcp: lookup service-to-service-call-via-activator-a-disabled-qgoluwzd-serving-tests.apps.ci-op-y42hx5lj-23b3e.origin-ci-int-aws.dev.rhcloud.com: no such host
```
This is because DNS
label(`service-to-service-call-via-activator-a-disabled-qgoluwzd-serving-tests`)
became longer than 63 characters and breaches RFC 1035.
To fix it, this patch adds `kmeta.ChildNam` to `ObjectNameForTest()`.
=> Shorten object name to avoid DNS issue defined (RFC 1035)

apis/contexts.go, apis/contexts_test.go, webhook/resourcesemantics/validation/reconcile_config.go, webhook/resourcesemantics/validation/reconcile_config_test.go, webhook/resourcesemantics/validation/validation_admit.go, webhook/resourcesemantics/validation/validation_admit_test.go
Issue #1207
Issue  #1140
**Proposed Changes**
- Allow Delete verb on validation callbacks
- Include IsInDelete on the context
- Note: I'm not a huge fan of the pattern of IfInVerb on context  rather than just storing the verb. It robs us of the ability to Switch on verb and  allows for the possibility of more than one set. That said, its how it is.
- Test callback on a delete verb
=> Allow Delete verb on validation callbacks

apis/duck/cached.go, apis/duck/cached_test.go
As described in https://github.com/knative/eventing/issues/2924#issuecomment-612600796, running the `init` function for a  given GVR _only once_ is a bit too optimistic. If that `init` function fails for any reason, the failure is then cached forever.
Instead of guarding the execution of `init` behind a `sync.Once`, we can simply assert that an informer has already been acquired and, if not, try `init()` again in the next call to `informerCache.Get()`. A `RWMutex` was added to avoid race conditions during calls to `init`.
Fixes knative/eventing#2924
---
**Test run**
Broker controller running with the changes from this PR, InMemoryChannel not deployed:
```console
$ kn dev get broker
NAME      READY   REASON                  URL   AGE
default   False   ChannelTemplateFailed         36s
``` …
=> Allow retry of informer cache init upon error

reconciler/testing/table.go, webhook/psbinding/reconciler.go, webhook/psbinding/table_test.go
By labelling a target namespace `bindings.knative.dev/inclusion: true` we can then set the psbinding webhook to exlusion and not have the webhook hit every single request to the apiserver (but still allow the psbinding requests we *want* to reconcile).
=> Sinkbinding Webhook should label namespace for inclusion

injection/sharedmain/main.go
This releases the lease as soon as the provided context is cancelled.
While we're technically not quite done exiting once we see the cancel signal, the time overlap should be good enough as we'll stop the controller as soon as we see the cancel signal and the newly acquired leaders need to launch their informers etc. first. That should be close enough to being already shut down.
In the worst worst case, we have a very brief time of two controllers stamping each other. I think that's seldom enough to not warrant more orchestration logic.
Note: There's currently a bug in releasing the lock successfully, being fixed here: https://github.com/kubernetes/kubernetes/pull/88192
=> Release leader election lock as soon as we exit.

client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go
These lines are printed fairly heavily, especially when we delete resources without issues. They definitely are not error worthy at this point and given their misleading nature, DEBUG might be best.
=> Drop 'no longer exist' line to DEBUG.

tracing/config/tracing.go, tracing/config/tracing_test.go
Needed for passing the configuration from the adapter controller to the receive adapter https://github.com/knative/eventing/issues/2978
=> Tracing configuration json marshal/unmarshal

client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go, client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/controller.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_controller.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go, controller/options.go
Adds an option to the controller to optionally override the finalizer name to use in the generated reconciler.
Fixes #1227.
**Note:** This is a quick hackup without actually bikeshedding it with peeps. Feel free to bin if this is entirely the wrong direction.
=> Add a controller option to specify a custom finalizer name.

codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Also it seems in the test logs this is manifested as `returned an event` and nothing else...
but I blame it to the testing log configuration, perhaps.
I'll try to find out more about empty logs independently
/assign mattmoor @n3wscott
=> Fix the logging to be a sentence

reconciler/testing/tracker.go, reconciler/testing/tracker_test.go, tracker/enqueue.go, tracker/enqueue_test.go, tracker/interface.go
Currently, eviction of keys is timing based which results in unexpected enqueues of items that no longer exist, especially if you create, delete, recreate objects quickly.
This adds a specific `OnDelete` function to the tracker to eagerly delete items and adds helpers to create a respective event handler.
=> Add specific callback for the tracker to delete items eagerly.

webhook/webhook_test.go
A lot of systems have something running that responds on 443, i.e. a local test environment or a webserver. The test fails in that case because it succeeds dialing 443, even though it shouldn't.
=> Change default port in webhook test to 8443.

injection/sharedmain/main.go
Fixes #1225
https://github.com/knative/pkg/blob/08b31df9e66a7ed7dbbfaf65de817f09d66cb79d/injection/sharedmain/main.go#L139
https://github.com/knative/pkg/blob/08b31df9e66a7ed7dbbfaf65de817f09d66cb79d/injection/sharedmain/main.go#L216
These lines:
```
log.Printf("Registering %d clients", len(injection.Default.GetClients()))
log.Printf("Registering %d informer factories", len(injection.Default.GetInformerFactories()))
log.Printf("Registering %d informers", len(injection.Default.GetInformers()))
log.Printf("Registering %d controllers", len(ctors))
```
Should use the zap logger, instead of printing directly to stderr
=> Use loggers when emitting count messages

injection/sharedmain/main.go
Reverts knative/pkg#1239
Line 151 is what sets up the clients on context, so the way this is set up fetching the kubeclient fails and we `OrDie` all the time. 🤦
=> Revert "Use loggers when emitting count messages"

controller/controller.go, controller/controller_test.go, injection/sharedmain/main.go
This has bugged me since we started using `ctx`, which containers a `stopCh` of sorts as `Done()`.  This is somewhat for consistency, but by using `ctx` explicitly we enable ourselves to take advantage of more contextual information.
I did a quick scan of call sites under knative.dev and github.com/tektoncd on my local GOPATH (I have many repos cloned) and the good news is that the `sharedmain` change should be the place through which the vast majority of calls occur, however, the one outlier I found is the KPA which calls this manually.  I will stage a PR to manually import pkg into serving to fix this once this lands.
=> Change StartAll to take context.

injection/context.go, injection/context_test.go, injection/sharedmain/main.go
This makes the config used to start all the clients available on the context starting the controllers. That enables us to use that config to create secondary clients in the controllers with the same config.
/assign @mattmoor @n3wscott
=> Inject config into controller context.

client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go, client/injection/kube/reconciler/core/v1/namespace/controller.go, codegen/cmd/injection-gen/generators/reconciler_controller.go
This changes the names we give workqueues in genreconciler to avoid collisions when multiple reconcilers in a single process use the same generated reconciler base.
There are a few examples of this in serving, both route and configuration have collisions.  Right now I think this mainly affects metrics published by the workqueues, but I noticed this leveraging the same for resource lock naming.
=> Generate unique workqueue names.

apis/field_error.go, apis/field_error_test.go
1. if no errors are passed skip doing stuff (checks, allocations, etc)
2. if there's one error passed and it's empty (the same)
- this is a quite popular pattern where in API validation we do:
`x.Also(validateY())` and if that succeeded then it'll be an empty
error. Which is in reality most of the time.
3. Improve tests by better printing
4. better test coverage shows commutativity of Also(a, b) and
Also(a).Also(b)
=> Skip doing any work if `Also` receives no errors

controller/controller.go
Everytime I read the generic "Filter" or "FilterGroupVersionKind" my brain needs to do an extra roundtrip to realize that this actually filters on the **controller** having that GVK/GK. This adds new functions that explictly state that to avoid that roundtrip.
Old functions are just deprecated so this can be rolled out without a downstream break.
=> Explicitly name controller filters.

apis/duck/v1alpha1/addressable_types.go, apis/duck/v1alpha1/addressable_types_test.go
As discovered as part of the move to v1beta1 reconcile work, the v1alpha1 down conversion is dropping the Hostname from the Status.
https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_eventing/3070/pull-knative-eventing-integration-tests/1255611066595938304
```
--- FAIL: TestChannelStatus/TestChannelStatus-{Channel_messaging.knative.dev/v1alpha1} (2.34s)
test_runner.go:95: namespace is : "v1alpha1-lhmqk"
channel_status_test_helper.go:50: Running channel status conformance test with channel {"Channel" "messaging.knative.dev/v1alpha1"}
channel_status_test_helper.go:54: Creating channel {Kind:Channel APIVersion:messaging.knative.dev/v1alpha1}-channel-req-labels
creation.go:52: Creating channel &TypeMeta{Kind:Channel,APIVersion:messaging.knative.dev/v1alpha1,}-channel-req-label …
```
=> populate the v1alpha1.Hostname from the URI as per the spec

network/transports.go, network/transports_test.go
I'd like to use this to retry TCP dial error in conformance/ingress tests.
=> Expose the `dialWithBackOff` utility

metrics/config.go, metrics/config_test.go, metrics/exporter.go, metrics/opencensus_exporter.go, metrics/opencensus_exporter_test.go, metrics/stackdriver_exporter.go, metrics/stackdriver_exporter_test.go
Avoid using an out-of-date metrics config with a newly created exporter when config-observability is updated. See #1263 for description of potential race condition issues.
This change also works around the potential deadlock with using k8s.io/client-go/kubernetes library within the metrics package described in #807.
The tl;dr of the deadlock cycle is the kubeclient will try and record a latency metric using knative/pkg metrics.record while knative/pkg UpdateExporter will try and use kubeclient to get a Secret for new exporters.
=> Make updating metrics config and metrics exporter atomic

network/transports.go, network/transports_test.go
This would give us some ideas about the total wait time when we look at logs, to make it easier to decide if we want to adjust the timeout setting.
=> Add elapsed wait time in timeout message.

go.mod, vendor/modules.txt
From https://github.com/golang/go/wiki/Modules
> When the main module contains a top-level vendor directory and its go.mod file specifies go 1.14 or higher, the go command now defaults to -mod=vendor for operations that accept that flag.
This preserves our prior behaviour of using packages from our vendor dir
```release-note
NONE
```
=> bump go.mod to go 1.14

test/helpers/name.go, testutils/metahelper/client/client.go
1. It can be annoying if a public function returns a private struct, so change `client` to `Client`
2. Remove one log message as it's just a noise.
/cc @chaodaiG
=> Small change to testutils/metahelper

apis/duck/v1/kresource_type.go, apis/duck/v1/kresource_type_test.go, apis/test/example/v1alpha1/fiz_types.go, apis/test/example/v1alpha1/foo_types.go, apis/test/pub/v1alpha1/bar_types.go
Issue #1226
- Each type will report its expected happy condition
- KRShaped will detect its happy type by looking at its own conditions.
- Added a unit test
At the moment each implementer either makes a LivingConditionSet manager or a BatchConditionSet manager within each resource. However this allows for polymorphic logic since each type will report its own happy condition.
Longer term we could simplify by just having GetConditionSet(resource) and the manager can figure out what the condition ought to be. This will make it easier to share common logic.
=> Include GetTopLevelConditionType for KRShaped

hack/generate-knative.sh, hack/update-codegen.sh
It should be safe to assume that these scripts are run from within the target repo.
=> Do not cd inside update-codegen

testutils/metahelper/client/client_test.go
There was a comment on the PR I merged earlier.
To add cmp.diff to the tests,
but when I actually looked, the tests look pretty bleak,
so I beefed them up and used t rather log
/assign @chizhg @chaodaiG
=> Properly fix the tests for the client

apis/duck/v1/kresource_type.go, apis/duck/v1/kresource_type_test.go, apis/test/example/v1alpha1/fiz_types.go, apis/test/example/v1alpha1/foo_types.go, apis/test/pub/v1alpha1/bar_types.go
Issue #1226
- Switch interface to retrieve the entire conditions set
As I looked at integrating this downstream I've realized this will be more flexible so that we can have generic awareness of all the conditions that exist for a resource. This will also allow us to ensure they are initialized.
=> Switch KRShaped interface to retrieve entire condition set

client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Currently it is possible for the generator to omit these imports, although this behavior appears to depend on the generator dependency versions.
=> Ensure that all needed imports are tracked in reconciler generator

controller/controller.go, injection/sharedmain/main.go, logging/config.go, websocket/connection.go
- use more performant functions (mostly remove formatters were possible)
- move zap.Error() to the call site, rather than creating a new sugared logger with a key attached (not cheap)
- fix *w usages where the key was not provided.
=> Fix logging around pkg

apis/volatile_time.go
This adds a doc comment describing why `VolatileTime` wraps `metav1.Time`, to ignore equality when diffing them in tests.
=> Document VolatileTime

apis/test/example/v1alpha1/foo_types.go, apis/test/pub/v1alpha1/bar_types.go, codegen/cmd/injection-gen/generators/packages.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go, injection/README.md
Issue #1226
The plan here is to opt-in downstream repos by adding the `krshapedlogic=true` tag to genreconciler. Later we can invert this and make it default (which will nudge future implementers to implement krshaped for all resources and use common logic) and opt out with 'krshapedlogic=false'
Alternatively we could instead code-generate the following with a runtime check which would compile for non-krshaped resources:
```
krshaped, isKRShaped := interface{}(resource).(duckv1.KRShaped)
if (isKRShaped) {
reconciler.PreProcessReconcile(ctx, resource)
}
```
However I slightly prefer compile-time checks. Thoughts from reviewers appreciated.
=> Generate common logic for krshaped resources

codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Allows errors to be re-enqueued event if they wrap a `ReconcilerEvent`.
The event is recorded whether it's wrapped or not, but a non-wrapped `ReconcilerEvent` is not considered as a `Reconcile()` error (current behaviour).
Too bad Kubernetes doesn't have a `corev1.EventTypeError`, _sighs_.
Closes #1266
---
examples:
```golang
// causes a re-enqueue
myevent := reconciler.NewEvent(corev1.EventTypeWarning, oopsReason, "oops")
return fmt.Errorf("this is bad: %w", myEvent)
```
```golang
// does NOT cause a re-enqueue
return reconciler.NewEvent(corev1.EventTypeWarning, oopsReason, "oops")
```
```golang
// reminder: permanentError can be used to prevent a re-enqueue regardless
// of the contents of the error
myevent := reconciler.NewEvent(corev1.EventTypeWarning, oopsReason, "oops")
return …
```
=> Fail reconciliation when a ReconcileEvent is wrapped inside an error

apis/volatile_time.go, apis/volatile_time_test.go
And provide a UT and an example how to do this with go-cmp
/assign @n3wscott mattmoor
/cc @ImJasonH
=> Fix the comment for volatile time

network/network.go, network/network_test.go, webhook/webhook.go, webhook/webhook_test.go
The webhook never properly implemented the Kubernetes SIGTERM/SIGKILL lifecycle, and doesn't even really support readiness probes today.  This change enables folks to use a block like this on their webhook container:
```yaml
readinessProbe: &probe
periodSeconds: 1
httpGet:
scheme: HTTPS
port: 8443
httpHeaders:
- name: k-kubelet-probe
value: "webhook"
livenessProbe: *probe
```
With this, the webhook won't report as `Ready` until a probe has succeeded, and when the SIGTERM is received, we will start failing probes for a grace period (so our Endpoint drops) before shutting down the webhook's HTTP Server.
This was uncovered by running the webhook across 10 replicas in Serving with the "Goose" (https://github.com/knative/pkg/pull/1316) enabled for the e2e tests.  The failure mode I saw was …
=> Implement the K8s lifecycle in webhook.

codegen/cmd/injection-gen/generators/packages.go
Previously we used the k8s tag parser which splits on '=' to look for
"+genreconciler" or "+genreconciler:class"
Now we have a parser that splits on ':' and expects a comma separated list so we can simplify the search.
The old parser leads to a bug if we try to do things in this order without more hardcoding:
"+genreconciler:krshaped=true,class=foo"
=> Use our new tag parser to find genreconciler

codegen/cmd/injection-gen/generators/packages.go
- make sure we allocate proper amount of slice space
-  `t:=t` is needed only if you're doing goroutines in the loop
- extract constants outside of the loops.
- reformat
/assign @n3wscott mattmoor
=> Some nits in the genreconciler

client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go, client/injection/kube/reconciler/core/v1/namespace/reconciler.go, codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Backport of 5036c917e57219394482615050ee92ed9cf687d9 for the 0.14 release line.
=> [RELEASE-0.14] Drop 'no longer exist' line to DEBUG.

codegen/cmd/injection-gen/generators/reconciler_reconciler.go
Backport of 5036c917e57219394482615050ee92ed9cf687d9 for the 0.13 release line.
=> [RELEASE-0.13] Drop 'no longer exist' line to DEBUG.

kmp/reporters_test.go, network/transports.go, test/e2e_flags.go, test/logging/example_tlogger_test.go, test/webhook-apicoverage/resourcetree/test_util.go
As per title, a few small touchups removing unused code, using common code constructs and adding a few linter annotations to false alarms.
=> Code hygiene: Remove unused, use common constructs.
